# 7zr
# Autogenerated from man page /usr/share/man/man1/7zr.1.gz
complete -c 7zr -o 'ai[r[-' --description 'Include archives.'
complete -c 7zr -o 'ax[r[-' --description 'Exclude archives.'
complete -c 7zr -o an --description 'Disable archive_name field.'
complete -c 7zr -o bb --description 'Set output log level.'
complete -c 7zr -o bd --description 'Disable progress indicator.'
complete -c 7zr -o bt --description 'Show execution time statistics.'
complete -c 7zr -o 'i[r[-' --description 'Include filenames.'
complete -c 7zr -o 'r[-' --description 'Recurse subdirectories (CAUTION: this flag does not do what you think, avoid …'
complete -c 7zr -o 'scrc[CRC32' --description 'Set hash function for x, e, h commands.'
complete -c 7zr -o sdel --description 'Delete files after compression.'
complete -c 7zr -o seml --description 'Send archive by email.'
complete -c 7zr -o sfx --description 'Create SFX archive.'
complete -c 7zr -o si --description 'Read data from stdin (e. g.  tar cf - directory | 7zr a -si directory. tar.'
complete -c 7zr -o slp --description 'Set Large Pages mode.'
complete -c 7zr -o slt --description 'Show technical information for l (List) command.'
complete -c 7zr -o snh --description 'Store hard links as links.'
complete -c 7zr -o snl --description 'Store symbolic links as links.'
complete -c 7zr -o sni --description 'Store NT security information.'
complete -c 7zr -o sns --description 'Store NTFS alternate streams.'
complete -c 7zr -o so --description 'Write data to stdout (e. g.  7zr x -so directory. tar. 7z | tar xf -).'
complete -c 7zr -o spd --description 'Disable wildcard matching for file names.'
complete -c 7zr -o spe --description 'Eliminate duplication of root folder for extract command.'
complete -c 7zr -o spf --description 'Use fully qualified file paths.'
complete -c 7zr -o ssc --description 'Set sensitive case mode.'
complete -c 7zr -o ssw --description 'Compress shared files.'
complete -c 7zr -o stl --description 'Set archive timestamp from the most recently modified file.'
complete -c 7zr -s u --description 'Update options.'
complete -c 7zr -s w --description 'Set working directory.  Empty path means a temporary directory.'
complete -c 7zr -o 'x[r[-' --description 'Exclude filenames.'
complete -c 7zr -s y --description 'Assume Yes on all queries.'
complete -c 7zr -o t7z --description '7z archive.'
complete -c 7zr -o m0 --description 'lzma method.'
complete -c 7zr -o mx --description 'level of compression = 9 (Ultra).'
complete -c 7zr -o mfb --description 'number of fast bytes for LZMA = 64.'
complete -c 7zr -o md --description 'dictionary size = 32 megabytes.'
complete -c 7zr -o ms --description 'solid archive = on EXAMPLE 2 7zr a -sfx archive.'

