# a2disconf
# Autogenerated from man page /usr/share/man/man8/a2disconf.8.gz
complete -c a2disconf -s q -l quiet --description 'Don\'t show informative messages.'
complete -c a2disconf -s m -l maintmode --description 'Enables the maintainer mode, that is the program invocation is effectuated au…'
complete -c a2disconf -s p -l purge --description 'When disabling a module, purge all traces of the module in the internal state…'

