# a2enmod
# Autogenerated from man page /usr/share/man/man8/a2enmod.8.gz
complete -c a2enmod -s q -l quiet --description 'Don\'t show informative messages.'
complete -c a2enmod -s f -l force --description 'When disabling a module, also cascade disables all modules that depends on it.'
complete -c a2enmod -s m -l maintmode --description 'Enables the maintainer mode, that is the program invocation is effectuated au…'
complete -c a2enmod -s p -l purge --description 'When disabling a module, purge all traces of the module in the internal state…'

