# aa-enabled
# Autogenerated from man page /usr/share/man/man1/aa-enabled.1.gz
complete -c aa-enabled -s h -l help --description 'Display a brief usage guide.'
complete -c aa-enabled -s q -l quiet --description 'Do not output anything to stdout.'

