# aa-features-abi
# Autogenerated from man page /usr/share/man/man1/aa-features-abi.1.gz
complete -c aa-features-abi -s h -l help --description 'Display a brief usage guide.'
complete -c aa-features-abi -s d -l debug --description 'show messages with debugging information.'

