# addftinfo
# Autogenerated from man page /usr/share/man/man1/addftinfo.1.gz
complete -c addftinfo -o x-height --description 'The height of lowercase letters without ascenders such as x.'
complete -c addftinfo -o fig-height --description 'The height of figures (digits).'
complete -c addftinfo -o asc-height --description 'The height of characters with ascenders, such as b, d or l.'
complete -c addftinfo -o body-height --description 'The height of characters such as parentheses.'
complete -c addftinfo -o cap-height --description 'The height of uppercase letters such as A.'
complete -c addftinfo -o comma-depth --description 'The depth of a comma.'
complete -c addftinfo -o desc-depth --description 'The depth of characters with descenders, such as p, q, or y.'
complete -c addftinfo -s v --description 'prints the version number.'
complete -c addftinfo -o body-depth --description 'The depth of characters such as parentheses.'

