# airscan-discover
# Autogenerated from man page /usr/share/man/man1/airscan-discover.1.gz
complete -c airscan-discover -s h --description 'Print help screen .'
complete -c airscan-discover -s d --description 'Print debug messages to console .'

