# alsaucm
# Autogenerated from man page /usr/share/man/man1/alsaucm.1.gz
complete -c alsaucm -s h -l help --description 'this help.'
complete -c alsaucm -s c -l card --description 'open card NAME.'
complete -c alsaucm -s i -l interactive --description 'interactive mode.'
complete -c alsaucm -s b -l batch --description 'batch mode (use \\(aq-\\(aq for the stdin input).'
complete -c alsaucm -s n -l no-open --description 'do not open first card found.'

