# alsatplg
# Autogenerated from man page /usr/share/man/man1/alsatplg.1.gz
complete -c alsatplg -s h -l help --description 'this help.'
complete -c alsatplg -s V -l version --description 'show the utility version and versions of used libraries.'
complete -c alsatplg -s c -l compile --description 'source configuration file for the compilation.'
complete -c alsatplg -s d -l decode --description 'source binary topology file for the decode.'
complete -c alsatplg -s n -l normalize --description 'parse and save the configuration file in the normalized format.'
complete -c alsatplg -s u -l dump --description 'parse and save the configuration file in the specified format.'
complete -c alsatplg -s o -l output --description 'output file.'
complete -c alsatplg -s v -l verbose --description 'set verbose level.'
complete -c alsatplg -s s -l sort --description 'sort the configuration identifiers (set for normalization).'
complete -c alsatplg -s x -l nocheck --description 'save the configuration without additional integrity check.'
complete -c alsatplg -s z -l dapm-nosort --description 'do not sort DAPM graph items (like in version 1. 2. 1-).'

