# anacron
# Autogenerated from man page /usr/share/man/man8/anacron.8.gz
complete -c anacron -s f --description 'Force execution of the jobs, ignoring the timestamps.'
complete -c anacron -s u --description 'Only update the timestamps of the jobs, to the current date, but don\'t run an…'
complete -c anacron -s s --description 'Serialize execution of jobs.'
complete -c anacron -s n --description 'Run jobs now.   Ignore the delay specifications in the  /etc/anacrontab file.'
complete -c anacron -s d --description 'Don\'t fork to the background.'
complete -c anacron -s q --description 'Suppress messages to standard error.   Only applicable with -d.'
complete -c anacron -s t --description 'Use specified anacrontab, rather than the default.'
complete -c anacron -s T --description 'Anacrontab testing.  The configuration file will be tested for validity.'
complete -c anacron -s S --description 'Use the specified spooldir to store timestamps in.'
complete -c anacron -s V --description 'Print version information, and exit.'
complete -c anacron -s h --description 'Print short usage message, and exit.'

