# apport-cli
# Autogenerated from man page /usr/share/man/man1/apport-cli.1.gz
complete -c apport-cli -s f -l file-bug --description 'Report a (non-crash) problem.'
complete -c apport-cli -s s -l symptom --description 'When being used in  --file-bug mode, specify the symptom to report the proble…'
complete -c apport-cli -s p -l package --description 'When being used in  --file-bug mode, specify the package to report the proble…'
complete -c apport-cli -s P -l pid --description 'When being used in  --file-bug mode, specify the PID (process ID) of a runnin…'
complete -c apport-cli -s c -l crash-file --description 'Upload a previously processed stored report in an arbitrary file location.'
complete -c apport-cli -s u -l update-report --description 'Run apport information collection on an already existing problem report.'
complete -c apport-cli -l save --description 'In --file-bug mode, save the collected information into a file instead of rep…'
complete -c apport-cli -s w -l window --description 'Point and click at the application window against which you wish to report th…'

