# appstreamcli
# Autogenerated from man page /usr/share/man/man1/appstreamcli.1.gz
complete -c appstreamcli -l details --description 'Print out more information about a found component.'
complete -c appstreamcli -l no-color --description 'Don\\*(Aqt print colored output.'
complete -c appstreamcli -l no-net --description 'Do not access the network when validating metadata.'
complete -c appstreamcli -l version --description 'Display the version number of appstreamcli.'
complete -c appstreamcli -l force --description 'flag.'
complete -c appstreamcli -l pedantic --description 'flag triggers a more pedantic validation of the file, including minor and sty…'
complete -c appstreamcli -l from-desktop --description 'option can be used to use a .'
complete -c appstreamcli -l exec --description 'flag can be used to explicitly define a binary to launch.'
complete -c appstreamcli -l format --description 'option can be used to enforce reading the input file in a specific format ("t…'
complete -c appstreamcli -l limit --description 'option is used to limit the amount of release entries written (the newest ent…'

