# apt-ftparchive
# Autogenerated from man page /usr/share/man/man1/apt-ftparchive.1.gz
complete -c apt-ftparchive -l md5 -l sha1 -l sha256 -l sha512 --description 'Generate the given checksum.'
complete -c apt-ftparchive -s d -l db --description 'Use a binary caching DB.  This has no effect on the generate command.'
complete -c apt-ftparchive -s q -l quiet --description 'Quiet; produces output suitable for logging, omitting progress indicators.'
complete -c apt-ftparchive -l delink --description 'Perform Delinking.'
complete -c apt-ftparchive -l contents --description 'Perform contents generation.'
complete -c apt-ftparchive -s s -l source-override --description 'Select the source override file to use with the sources command.'
complete -c apt-ftparchive -l readonly --description 'Make the caching databases read only.'
complete -c apt-ftparchive -s a -l arch --description 'Accept in the packages and contents commands only package files matching *_ar…'
complete -c apt-ftparchive -s h -l help --description 'Show a short usage summary.'
complete -c apt-ftparchive -s v -l version --description 'Show the program version.'
complete -c apt-ftparchive -s c -l config-file --description 'Configuration File; Specify a configuration file to use.'
complete -c apt-ftparchive -s o -l option --description 'Set a Configuration Option; This will set an arbitrary configuration option.'
complete -c apt-ftparchive -o f- -l no-f --description '.'
complete -c apt-ftparchive -s f --description 'or several other variations.'
complete -c apt-ftparchive -l no-delink --description 'APT::FTPArchive::DeLinkAct.'

