# apt-cdrom
# Autogenerated from man page /usr/share/man/man8/apt-cdrom.8.gz
complete -c apt-cdrom -l no-auto-detect -l cdrom --description 'Do not try to auto-detect the CD-ROM path.'
complete -c apt-cdrom -s d --description 'Mount point; specify the location to mount the CD-ROM.'
complete -c apt-cdrom -s r -l rename --description 'Rename a disc; change the label of a disc or override the disc\\*(Aqs given la…'
complete -c apt-cdrom -s m -l no-mount --description 'No mounting; prevent apt-cdrom from mounting and unmounting the mount point.'
complete -c apt-cdrom -s f -l fast --description 'Fast Copy; Assume the package files are valid and do not check every package.'
complete -c apt-cdrom -s a -l thorough --description 'Thorough Package Scan; This option may be needed with some old Debian 1. 1/1.'
complete -c apt-cdrom -s n -l just-print -l recon -l no-act --description 'No Changes; Do not change the sources.'
complete -c apt-cdrom -s h -l help --description 'Show a short usage summary.'
complete -c apt-cdrom -s v -l version --description 'Show the program version.'
complete -c apt-cdrom -s c -l config-file --description 'Configuration File; Specify a configuration file to use.'
complete -c apt-cdrom -s o -l option --description 'Set a Configuration Option; This will set an arbitrary configuration option.'
complete -c apt-cdrom -o f- -l no-f --description '.'

