# apt-config
# Autogenerated from man page /usr/share/man/man8/apt-config.8.gz
complete -c apt-config -l empty --description 'Include options which have an empty value.'
complete -c apt-config -l format --description 'Defines the output of each config option.'
complete -c apt-config -s h -l help --description 'Show a short usage summary.'
complete -c apt-config -s v -l version --description 'Show the program version.'
complete -c apt-config -s c -l config-file --description 'Configuration File; Specify a configuration file to use.'
complete -c apt-config -s o -l option --description 'Set a Configuration Option; This will set an arbitrary configuration option.'
complete -c apt-config -s f --description '.'
complete -c apt-config -o f- -l no-f --description '.'

