# apt-sortpkgs
# Autogenerated from man page /usr/share/man/man1/apt-sortpkgs.1.gz
complete -c apt-sortpkgs -s s -l source --description 'Use source index field ordering.  Configuration Item: APT::SortPkgs::Source.'
complete -c apt-sortpkgs -s h -l help --description 'Show a short usage summary.'
complete -c apt-sortpkgs -s v -l version --description 'Show the program version.'
complete -c apt-sortpkgs -s c -l config-file --description 'Configuration File; Specify a configuration file to use.'
complete -c apt-sortpkgs -s o -l option --description 'Set a Configuration Option; This will set an arbitrary configuration option.'
complete -c apt-sortpkgs -o f- -l no-f --description '.'
complete -c apt-sortpkgs -s f --description 'or several other variations.'

