# arp
# Autogenerated from man page /usr/share/man/man8/arp.8.gz
complete -c arp -s v -l verbose --description 'Tell the user what is going on by being verbose.'
complete -c arp -s n -l numeric --description 'shows numerical addresses instead of trying to determine symbolic host, port …'
complete -c arp -s H -l hw-type -s t --description 'When setting or reading the ARP cache, this optional parameter tells  arp whi…'
complete -c arp -s a --description 'Use alternate BSD style output format (with no fixed columns).'
complete -c arp -s e --description 'Use default Linux style output format (with fixed columns).'
complete -c arp -s D -l use-device --description 'Instead of a hw_addr, the given argument is the name of an interface.'
complete -c arp -s i -l device --description 'Select an interface.'
complete -c arp -s f -l file --description 'Similar to the.'
complete -c arp -s s --description 'option, only this time the address info is taken from file filename .'

