# automake
# Autogenerated from man page /usr/share/man/man1/automake.1.gz
complete -c automake -l help --description 'print this help, then exit.'
complete -c automake -l version --description 'print version number, then exit.'
complete -c automake -s v -l verbose --description 'verbosely list files processed.'
complete -c automake -l no-force --description 'only update Makefile. in\'s that are out of date.'
complete -c automake -s W -l warnings --description 'report the warnings falling in CATEGORY . SS "Dependency tracking:".'
complete -c automake -s i -l ignore-deps --description 'disable dependency tracking code.'
complete -c automake -l include-deps --description 'enable dependency tracking code . SS "Flavors:".'
complete -c automake -l foreign --description 'set strictness to foreign.'
complete -c automake -l gnits --description 'set strictness to gnits.'
complete -c automake -l gnu --description 'set strictness to gnu . SS "Library files:".'
complete -c automake -s a -l add-missing --description 'add missing standard files to package.'
complete -c automake -l libdir --description 'set directory storing library files.'
complete -c automake -l print-libdir --description 'print directory storing library files.'
complete -c automake -s c -l copy --description 'with -a, copy missing files (default is symlink).'
complete -c automake -s f -l force-missing --description 'force update of standard files . SS "Warning categories include:".'

