# axfer
# Autogenerated from man page /usr/share/man/man1/axfer.1.gz
complete -c axfer -s l --description ',.'
complete -c axfer -l list-devices --description ',.'
complete -c axfer -s L --description ',.'
complete -c axfer -l list-pcms --description 'are acknowledged as list subcommand.'

