# axfer-list
# Autogenerated from man page /usr/share/man/man1/axfer-list.1.gz
complete -c axfer-list -s l --description ',.'
complete -c axfer-list -l list-devices --description 'are handled as device operation.  Options of.'
complete -c axfer-list -s L --description ',.'
complete -c axfer-list -l list-pcms --description 'are handled as pcm operation.'

