# axi-cache
# Autogenerated from man page /usr/share/man/man1/axi-cache.1.gz
complete -c axi-cache -l version --description 'show program\'s version number and exit.'
complete -c axi-cache -s h -l help --description 'show this help message and exit.'
complete -c axi-cache -s s -l sort --description 'sort by the given value, as listed in \\,/var/lib/apt-xapian-index/values\\/.'
complete -c axi-cache -l tags --description 'show matching tags, rather than packages.'
complete -c axi-cache -l tabcomplete --description 'suggest words for tab completion of the current command line (type is \'plain\'…'
complete -c axi-cache -l last --description 'use \'show --last\' to limit tab completion to only the packages from the last …'
complete -c axi-cache -l all --description 'disable pagination and always show all results.'

