# bleachbit
# Autogenerated from man page /usr/share/man/man1/bleachbit.1.gz
complete -c bleachbit -s h -l help --description 'show this help message and exit.'
complete -c bleachbit -s l -l list-cleaners --description 'list cleaners.'
complete -c bleachbit -s c -l clean --description 'run cleaners to delete files and make other permanent changes.'
complete -c bleachbit -l debug --description 'set log level to verbose.'
complete -c bleachbit -l debug-log --description 'log debug messages to file.'
complete -c bleachbit -s s -l shred --description 'shred specific files or folders.'
complete -c bleachbit -l sysinfo --description 'show system information.'
complete -c bleachbit -l gui --description 'launch the graphical interface.'
complete -c bleachbit -s p -l preview --description 'preview files to be deleted and other changes.'
complete -c bleachbit -l preset --description 'use options set in the graphical interface.'
complete -c bleachbit -s w -l wipe-free-space --description 'wipe free space in the given paths.'
complete -c bleachbit -s v -l version --description 'output version information and exit.'
complete -c bleachbit -s o -l overwrite --description 'overwrite files to hide contents COPYRIGHT This manual page is Copyright Â© 2…'

