# bluetoothctl
# Autogenerated from man page /usr/share/man/man1/bluetoothctl.1.gz
complete -c bluetoothctl -l agent --description 'Register agent handler: <capability>.'
complete -c bluetoothctl -l timeout --description 'Timeout in seconds for non-interactive mode.'
complete -c bluetoothctl -l version --description 'Display version.'
complete -c bluetoothctl -l help --description 'Display help.'

