# bluemoon
# Autogenerated from man page /usr/share/man/man1/bluemoon.1.gz
complete -c bluemoon -s A -l bdaddr --description 'Set Bluetooth address.'
complete -c bluemoon -s F -l firmware --description 'Load firmware.'
complete -c bluemoon -s C -l check --description 'Check firmware image.'
complete -c bluemoon -s R -l reset --description 'Reset controller.'
complete -c bluemoon -s B -l coldboot --description 'Cold boot controller.'
complete -c bluemoon -s E -l exception --description 'Trigger exception.'
complete -c bluemoon -s i -l index --description 'Use specified controller.'
complete -c bluemoon -s h -l help --description 'Show help options.'

