# boltctl
# Autogenerated from man page /usr/share/man/man1/boltctl.1.gz
complete -c boltctl -l version --description 'Print version information and exit.'
complete -c boltctl -s U -l uuid --description '.'
complete -c boltctl -s F -l first-time --description '.'
complete -c boltctl -l policy --description '.'
complete -c boltctl -s a -l all --description '.'
complete -c boltctl -s t -l timeout --description '.'
complete -c boltctl -s q -l query --description '.'

