# boltd
# Autogenerated from man page /usr/share/man/man8/boltd.8.gz
complete -c boltd -s h -l help --description 'Prints a short help text and exits.'
complete -c boltd -l version --description 'Shows the version number and exits.'
complete -c boltd -s r -l replace --description 'Replace the currently running boltd instance.'
complete -c boltd -l journal --description 'Force logging to the journal.'
complete -c boltd -s v -l verbose --description 'Print debug output.'

