# btmgmt
# Autogenerated from man page /usr/share/man/man1/btmgmt.1.gz
complete -c btmgmt -l index --description 'Specify adapter index.'
complete -c btmgmt -l timeout --description 'Timeout in seconds for non-interactive mode.'
complete -c btmgmt -l version --description 'Display version.'
complete -c btmgmt -l help --description 'Display help.'

