# btmon
# Autogenerated from man page /usr/share/man/man1/btmon.1.gz
complete -c btmon -s r -l read --description 'Read traces in btsnoop format.'
complete -c btmon -s w -l write --description 'Save traces in btsnoop format.'
complete -c btmon -s a -l analyze --description 'Analyze traces in btsnoop format.'
complete -c btmon -s s -l server --description 'Start monitor server socket .'
complete -c btmon -s i -l index --description 'Show only specified controller.'
complete -c btmon -s d -l tty --description 'Read data from TTY . HP -B, --tty-speed <rate> Set TTY speed (default 115200).'
complete -c btmon -s t -l time --description 'Show time instead of time offset.'
complete -c btmon -s T -l date --description 'Show time and date information.'
complete -c btmon -s S -l sco --description 'Dump SCO traffic.'
complete -c btmon -s A -l a2dp --description 'Dump A2DP stream traffic.'
complete -c btmon -s E -l ellisys --description 'Send Ellisys HCI Injection.'
complete -c btmon -s p -l priority --description '.'
complete -c btmon -s B -l tty-speed --description '.'
complete -c btmon -s h -l help --description 'Show help options.'

