# catdoc
# Autogenerated from man page /usr/share/man/man1/catdoc.1.gz
complete -c catdoc -s a --description '- shortcut for -f ascii.  Produces ASCII text as output.'
complete -c catdoc -s b --description '- process broken MS-Word file.'
complete -c catdoc -s d --description '- specifies destination charset name.'
complete -c catdoc -s f --description '- specifies output format as described in CHARACTER SUBSTITUTION below.'
complete -c catdoc -s l --description 'Causes   catdoc to list names of available charsets to the stdout and exit su…'
complete -c catdoc -s m --description 'Specifies right margin for text  (default 72).    -m 0 is equivalent to  -w.'
complete -c catdoc -s s --description 'Specifies source charset.'
complete -c catdoc -s t --description '- shortcut for   -f tex  converts all printable chars, which have special mea…'
complete -c catdoc -s u --description '- declares that Word  document  contain  UNICODE   (UTF-16) representation of…'
complete -c catdoc -s 8 --description '- declares is Word document is 8 bit.'
complete -c catdoc -s w --description 'disables word wrapping.'
complete -c catdoc -s x --description 'causes catdoc to output unknown UNICODE character as \\\\xNNNN, instead of ques…'
complete -c catdoc -s v --description 'causes catdoc to print some useless information about word document structure…'
complete -c catdoc -s V --description 'outputs catdoc version.'

