# catppt
# Autogenerated from man page /usr/share/man/man1/catppt.1.gz
complete -c catppt -s l --description 'list known charsets and exit successfully.'
complete -c catppt -s b --description 'slides break string.'
complete -c catppt -s d --description '- specifies destination charset name.'
complete -c catppt -s s --description '- specifies source charset.'

