# chem
# Autogenerated from man page /usr/share/man/man1/chem.1.gz
complete -c chem -s h --description 'and.'
complete -c chem -l help --description 'display a usage message, whereas.'
complete -c chem -s v --description 'and.'
complete -c chem -l version --description 'display version information; all exit.'
complete -c chem -s p --description 'for the activation of pic : chem [file ] | groff -p  THE LANGUAGE The chem in…'

