# chvt
# Autogenerated from man page /usr/share/man/man1/chvt.1.gz
complete -c chvt -s V -l version --description 'print program version and exit.'
complete -c chvt -s h -l help --description 'show this text and exit.'

