# clang-include-fixer-12
# Autogenerated from man page /usr/share/man/man1/clang-include-fixer-12.1.gz
complete -c clang-include-fixer-12 -l insert-header --description 'The result is written to stdout.  It is currently used for editor integration.'
complete -c clang-include-fixer-12 -o insert-header --description 'FilePath: "/path/to/foo. cc", QuerySymbolInfos: [.'
complete -c clang-include-fixer-12 -l output-headers --description 'JSON format to stdout:.'
complete -c clang-include-fixer-12 -l query-symbol --description 'database directly without parsing the file.'
complete -c clang-include-fixer-12 -l stdin --description 'virtual file system) with input from <stdin> and run the tool on the new cont…'
complete -c clang-include-fixer-12 -l help -l help-hidden --description '.'
complete -c clang-include-fixer-12 -l help-list -l help-list-hidden --description '.'
complete -c clang-include-fixer-12 -l version --description '.'
complete -c clang-include-fixer-12 -l db --description '.'
complete -c clang-include-fixer-12 -l extra-arg --description '.'
complete -c clang-include-fixer-12 -l extra-arg-before --description '.'
complete -c clang-include-fixer-12 -l input --description '.'
complete -c clang-include-fixer-12 -l minimize-paths --description '.'
complete -c clang-include-fixer-12 -s p --description '.'
complete -c clang-include-fixer-12 -s q --description '.'
complete -c clang-include-fixer-12 -l style --description 'headers if there is no clang-format config file found.'

