# clang-reorder-fields-12
# Autogenerated from man page /usr/share/man/man1/clang-reorder-fields-12.1.gz
complete -c clang-reorder-fields-12 -l help -l help-hidden --description '.'
complete -c clang-reorder-fields-12 -l help-list -l help-list-hidden --description '.'
complete -c clang-reorder-fields-12 -l version --description '.'
complete -c clang-reorder-fields-12 -l extra-arg --description '.'
complete -c clang-reorder-fields-12 -l extra-arg-before --description '.'
complete -c clang-reorder-fields-12 -l fields-order --description '.'
complete -c clang-reorder-fields-12 -s i --description '.'
complete -c clang-reorder-fields-12 -s p --description '.'
complete -c clang-reorder-fields-12 -l record-name --description '.'

