# clang-apply-replacements-12
# Autogenerated from man page /usr/share/man/man1/clang-apply-replacements-12.1.gz
complete -c clang-apply-replacements-12 -l format --description 'Use -style to choose formatting style.'
complete -c clang-apply-replacements-12 -l style --description 'LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.'
complete -c clang-apply-replacements-12 -o style --description 'clang-format file located in one of the parent directories of the source file…'
complete -c clang-apply-replacements-12 -l style-config --description 'describing a formatting style to use for formatting code when -style=\\,file\\/.'
complete -c clang-apply-replacements-12 -l help -l help-hidden --description '.'
complete -c clang-apply-replacements-12 -l help-list -l help-list-hidden --description '.'
complete -c clang-apply-replacements-12 -l version --description '.'
complete -c clang-apply-replacements-12 -l remove-change-desc-files --description 'merging/replacing.'

