# clang-query-12
# Autogenerated from man page /usr/share/man/man1/clang-query-12.1.gz
complete -c clang-query-12 -l help -l help-hidden --description '.'
complete -c clang-query-12 -l help-list -l help-list-hidden --description '.'
complete -c clang-query-12 -l version --description '.'
complete -c clang-query-12 -s c --description '.'
complete -c clang-query-12 -l extra-arg --description '.'
complete -c clang-query-12 -l extra-arg-before --description '.'
complete -c clang-query-12 -s f --description '.'
complete -c clang-query-12 -s p --description '.'
complete -c clang-query-12 -l preload --description '.'
complete -c clang-query-12 -l use-color --description 'will be used if the terminal connected to standard output supports colors.'

