# clang-check-12
# Autogenerated from man page /usr/share/man/man1/clang-check-12.1.gz
complete -c clang-check-12 -l help -l help-hidden --description '.'
complete -c clang-check-12 -l help-list -l help-list-hidden --description '.'
complete -c clang-check-12 -l version --description '.'
complete -c clang-check-12 -l analyze --description '.'
complete -c clang-check-12 -l ast-dump --description '.'
complete -c clang-check-12 -l ast-dump-filter -o ast-dump -o ast-print -o ast-list --description '.'
complete -c clang-check-12 -l ast-list --description '.'
complete -c clang-check-12 -l ast-print --description '.'
complete -c clang-check-12 -l extra-arg --description '.'
complete -c clang-check-12 -l extra-arg-before --description '.'
complete -c clang-check-12 -l fix-what-you-can --description '.'
complete -c clang-check-12 -l fixit --description '.'
complete -c clang-check-12 -s p --description '.'

