# clang-rename-12
# Autogenerated from man page /usr/share/man/man1/clang-rename-12.1.gz
complete -c clang-rename-12 -l help -l help-hidden --description '.'
complete -c clang-rename-12 -l help-list -l help-list-hidden --description '.'
complete -c clang-rename-12 -l version --description '.'
complete -c clang-rename-12 -l export-fixes --description '.'
complete -c clang-rename-12 -l extra-arg --description '.'
complete -c clang-rename-12 -l extra-arg-before --description '.'
complete -c clang-rename-12 -l force --description '.'
complete -c clang-rename-12 -s i --description '.'
complete -c clang-rename-12 -l input --description '.'
complete -c clang-rename-12 -l new-name --description '.'
complete -c clang-rename-12 -l offset --description '.'
complete -c clang-rename-12 -s p --description '.'
complete -c clang-rename-12 -l pl --description '.'
complete -c clang-rename-12 -l pn --description '.'
complete -c clang-rename-12 -l qualified-name --description '.'

