# clang-format-diff
# Autogenerated from man page /usr/share/man/man1/clang-format-diff.1.gz
complete -c clang-format-diff -o iregex --description '[-style STYLE] [-binary BINARY] .'
complete -c clang-format-diff -s h -l help --description 'show this help message and exit.'
complete -c clang-format-diff -s i --description 'apply edits to files instead of displaying a diff.'
complete -c clang-format-diff -s p --description 'strip the smallest prefix containing P slashes.'
complete -c clang-format-diff -o regex --description 'custom pattern selecting file paths to reformat (case sensitive, overrides -i…'
complete -c clang-format-diff -o sort-includes --description 'let clang-format sort include blocks.'
complete -c clang-format-diff -s v -l verbose --description 'be more verbose, ineffective without -i.'
complete -c clang-format-diff -o style --description 'formatting style to apply (LLVM, GNU, Google, Chromium, Microsoft, Mozilla, W…'
complete -c clang-format-diff -o binary --description 'location of binary to use for clang-format.'

