# composer
# Autogenerated from man page /usr/share/man/man1/composer.1.gz
complete -c composer -s h -l help --description 'Display this help message.'
complete -c composer -s q -l quiet --description 'Do not output any message.'
complete -c composer -s V -l version --description 'Display this application version.'
complete -c composer -l ansi --description 'Force ANSI output.'
complete -c composer -l no-ansi --description 'Disable ANSI output.'
complete -c composer -s n -l no-interaction --description 'Do not ask any interactive question.'
complete -c composer -l profile --description 'Display timing and memory usage information.'
complete -c composer -l no-plugins --description 'Whether to disable plugins.'
complete -c composer -s d -l working-dir --description 'If specified, use the given directory as working directory.'
complete -c composer -l no-cache --description 'Prevent use of the cache.'
complete -c composer -s v -l verbose --description 'Increase the verbosity of messages: 1 for normal output, 2 for more verbose o…'

