# cron
# Autogenerated from man page /usr/share/man/man8/cron.8.gz
complete -c cron -s f --description 'Stay in foreground mode, don\'t daemonize.'
complete -c cron -s P --description 'Don\'t set PATH for child processes.   Let it inherit instead.'
complete -c cron -s l --description 'Enable LSB compliant names for /etc/cron. d files.'
complete -c cron -s n --description 'Include the FQDN in the subject when sending mails.'
complete -c cron -s L --description 'Tell cron what to log about jobs (errors are logged regardless of this value)…'
complete -c cron -l lsbsysinit --description 'option in run-parts .'

