# cryfs
# Autogenerated from man page /usr/share/man/man1/cryfs.1.gz
complete -c cryfs -s h -l help --description ' Show a help message containing short descriptions for all options.'
complete -c cryfs -l show-ciphers --description ' Show a list of all supported encryption ciphers.'
complete -c cryfs -l version --description ' Show the CryFS version number. SS Encryption parameters .'
complete -c cryfs -l blocksize --description ' Set the block size to arg bytes.  Defaults to  32768 .'
complete -c cryfs -l cipher --description ' Use arg as the cipher for the encryption.  Defaults to  aes-256-gcm .'
complete -c cryfs -s c -l config --description ' Use file as configuration file for this CryFS storage instead of basedir/cry…'
complete -c cryfs -s f -l foreground --description ' Run CryFS in the foreground.  Stop using CTRL-C.'
complete -c cryfs -l allow-filesystem-upgrade --description ' Allow upgrading the file system if it was created with an old CryFS version.'
complete -c cryfs -l allow-integrity-violations --description ' By default, CryFS checks for integrity violations, i. e.'
complete -c cryfs -l allow-replaced-filesystem --description ' By default, CryFS remembers file systems it has seen in this base directory …'
complete -c cryfs -l missing-block-is-integrity-violation --description ' When CryFS encounters a missing ciphertext block, it cannot cannot (yet) kno…'
complete -c cryfs -l logfile --description ' Write status information to file.'
complete -c cryfs -l unmount-idle --description '.'

