# ctstat
# Autogenerated from man page /usr/share/man/man8/ctstat.8.gz
complete -c ctstat -s h -l help --description 'Show summary of options.'
complete -c ctstat -s V -l version --description 'Show version of program.'
complete -c ctstat -s c -l count --description 'Print <count> number of intervals.'
complete -c ctstat -s d -l dump --description 'Dump list of available files/keys.'
complete -c ctstat -s f -l file --description 'Statistics file to use, may be specified multiple times.'
complete -c ctstat -s i -l interval --description 'Set interval to \'intv\' seconds.'
complete -c ctstat -s j -l json --description 'Display results in JSON format.'
complete -c ctstat -s k -l keys --description 'Display only keys specified.  Each key k is of the form [file:]key.'
complete -c ctstat -s s -l subject --description 'Specify display of subject/header.'
complete -c ctstat -s w -l width --description 'Width for each field.  USAGE EXAMPLES.'

