# cvtenc
# Autogenerated from man page /usr/share/man/man1/cvtenc.1.gz
complete -c cvtenc -o Encoding --description 'Specify non-unicode encoding to be used.'
complete -c cvtenc -o EscapeIn --description 'Specify \'-EscapeIn YES\' (the default is \'NO\') to parse the input for \\\\u esca…'
complete -c cvtenc -o EscapeOut --description 'Specify \'-EscapeOut YES\' (the default is \'NO\') to generate \\\\u escape sequenc…'
complete -c cvtenc -o Unicode --description 'Specify \'-Unicode IN\' (or \'-Unicode OUT\') to control the direction of convers…'

