# dbxtool
# Autogenerated from man page /usr/share/man/man1/dbxtool.1.gz
complete -c dbxtool -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c dbxtool -s v -l verbose --description 'Show extra debugging information.'
complete -c dbxtool -l version --description 'Show the calculated version of the dbx.'
complete -c dbxtool -s l -l list --description 'List entries in dbx.'
complete -c dbxtool -s a -l apply --description 'Apply update files.'
complete -c dbxtool -s d -l dbx --description 'Specify the dbx database file.'
complete -c dbxtool -s f -l force --description 'Apply update even when not advised.'

