# ddstdecode
# Autogenerated from man page /usr/share/man/man1/ddstdecode.1.gz
complete -c ddstdecode -s d --description 'Basename of . pbm file for saving decompressed planes.'
complete -c ddstdecode -s h --description 'Print hex file offsets.'
complete -c ddstdecode -s o --description 'Print file offsets.'
complete -c ddstdecode -s D --description 'Set Debug level [0].'

