# debconf-copydb
# Autogenerated from man page /usr/share/man/man1/debconf-copydb.1.gz
complete -c debconf-copydb -s p -l pattern --description 'If this is specified, only items in sourcedb whose names match the pattern wi…'
complete -c debconf-copydb -l owner-pattern --description 'If this is specified, only items in sourcedb whose owners match the pattern w…'

