# debconf
# Autogenerated from man page /usr/share/man/man1/debconf.1.gz
complete -c debconf -o opackage -l owner --description 'Tell debconf what package the command it is running is a part of.'
complete -c debconf -o ftype -l frontend --description 'Select the frontend to use.'
complete -c debconf -o pvalue -l priority --description 'Specify the minimum priority of question that will be displayed.'

