# debian-distro-info
# Autogenerated from man page /usr/share/man/man1/debian-distro-info.1.gz
complete -c debian-distro-info -l date --description 'date for calculating the version (default: today).'
complete -c debian-distro-info -s h -l help --description 'display help message and exit.'
complete -c debian-distro-info -l alias --description 'print the alias (oldstable, stable, testing, unstable) relative to the distri…'
complete -c debian-distro-info -s a -l all --description 'list all known versions.'
complete -c debian-distro-info -s y -l days --description 'display number of days until specified version reaches the specified mileston…'
complete -c debian-distro-info -s d -l devel --description 'latest development version.'
complete -c debian-distro-info -s o -l old --description 'latest old (stable) version.'
complete -c debian-distro-info -l series --description 'series to calculate the version for.'
complete -c debian-distro-info -s s -l stable --description 'latest stable version.'
complete -c debian-distro-info -l supported --description 'list of all supported stable versions.'
complete -c debian-distro-info -s t -l testing --description 'latest testing version.'
complete -c debian-distro-info -l unsupported --description 'list of all unsupported stable versions.'
complete -c debian-distro-info -s c -l codename --description 'print the codename (default).'
complete -c debian-distro-info -s r -l release --description 'print the release version.'
complete -c debian-distro-info -s f -l fullname --description 'print the full name SEE ALSO distro-info (1), ubuntu-distro-info (1) AUTHOR T…'

