# debugapp
# Autogenerated from man page /usr/share/man/man1/debugapp.1.gz
complete -c debugapp -l debug --description 'option; we recommend using openapp directly.'
complete -c debugapp -l gdb --description 'option or through the GDB environment variable.'

