# debugedit
# Autogenerated from man page /usr/share/man/man8/debugedit.8.gz
complete -c debugedit -s b -l base-dir --description 'base build directory of objects.'
complete -c debugedit -s d -l dest-dir --description 'directory to rewrite base-dir into.'
complete -c debugedit -s l -l list-file --description 'file where to put list of source and header file names.'
complete -c debugedit -s i -l build-id --description 'recompute build ID note and print ID on stdout.'
complete -c debugedit -s s -l build-id-seed --description 'if recomputing the build ID note use this string as hash seed.'
complete -c debugedit -s n -l no-recompute-build-id --description 'do not recompute build ID note even when-i or -s are given .'
complete -c debugedit -s '?' -l help --description 'Show this help message.'
complete -c debugedit -s u -l usage --description 'Display brief usage message.'
complete -c debugedit -s V -l version --description 'Show debugedit version OPTIONS These programs follow the usual GNU command li…'

