# delaunay
# Autogenerated from man page /usr/share/man/man1/delaunay.1.gz
complete -c delaunay -s b -l hull --description 'Do not keep convex hull.'
complete -c delaunay -s e -l noconst --description 'Do not add constrained edges.'
complete -c delaunay -s S -l split --description 'Split constraints (experimental).'
complete -c delaunay -s H -l holes --description 'Remove holes from the triangulation.'
complete -c delaunay -s d -l duplicates --description 'Remove duplicate vertices.'
complete -c delaunay -s r -l randomize --description 'Shuffle input vertex list.'
complete -c delaunay -s c -l check --description 'Check Delaunay property.'
complete -c delaunay -s f -l files --description 'Generate evolution files.'
complete -c delaunay -s o -l conform --description 'Generate conforming triangulation.'
complete -c delaunay -s s -l steiner --description 'Maximum number of Steiner points for conforming triangulation (default is no …'
complete -c delaunay -s q -l quality --description 'Set the minimum acceptable face quality.'
complete -c delaunay -s a -l area --description 'Set the maximum acceptable face area.'
complete -c delaunay -s v -l verbose --description 'Print statistics about the triangulation.'
complete -c delaunay -s h -l help --description 'Display the help and exit.'

