# delgroup
# Autogenerated from man page /usr/share/man/man8/delgroup.8.gz
complete -c delgroup -l conf --description 'Use FILE instead of the default files R /etc/deluser. conf and R /etc/adduser.'
complete -c delgroup -l group --description 'Remove a group.'
complete -c delgroup -l help --description 'Display brief instructions.'
complete -c delgroup -l quiet --description 'Suppress progress messages.'
complete -c delgroup -l system --description 'Only delete if user/group is a system user/group.'
complete -c delgroup -l only-if-empty --description 'Only remove if no members are left.'
complete -c delgroup -l backup --description 'Backup all files contained in the userhome and the mailspool-file to a file n…'
complete -c delgroup -l backup-to --description 'Place the backup files not in / but in the directory specified by this parame…'
complete -c delgroup -l remove-home --description 'Remove the home directory of the user and its mailspool.'
complete -c delgroup -l remove-all-files --description 'Remove all files from the system owned by this user.'
complete -c delgroup -l force --description 'parameter; this may prevent to remove the root user by accident.'
complete -c delgroup -l version --description 'Display version and copyright information.  RETURN VALUE.'

