# devlink-trap
# Autogenerated from man page /usr/share/man/man8/devlink-trap.8.gz
complete -c devlink-trap -s v --description '.'
complete -c devlink-trap -s s --description 'devlink trap show [  DEV trap TRAP  ] devlink trap set  DEV  trap  TRAP [  ac…'

