# devlink-dpipe
# Autogenerated from man page /usr/share/man/man8/devlink-dpipe.8.gz
complete -c devlink-dpipe -s V --description 'devlink dpipe table show  DEV [   name TABLE_NAME  ] devlink dpipe table set …'

