# dh_autoreconf
# Autogenerated from man page /usr/share/man/man1/dh_autoreconf.1.gz
complete -c dh_autoreconf -o Xitem -l exclude --description 'Exclude files that contain \\*(L"item\\*(R" anywhere in their filename from bei…'
complete -c dh_autoreconf -l mode --description 'Change the way in which modifications to files are detected.'
complete -c dh_autoreconf -l as-needed --description 'Enable support for -Wl,--as-needed in all ltmain.'
complete -c dh_autoreconf -o Ddir -l sourcedirectory --description 'Run everything in the source directory.'

