# dh_compress
# Autogenerated from man page /usr/share/man/man1/dh_compress.1.gz
complete -c dh_compress -o Xitem -l exclude --description 'Exclude files that contain item anywhere in their filename from being compres…'
complete -c dh_compress -s A -l all --description 'Compress all files specified by command line parameters in \\s-1ALL\\s0 package…'

