# dh_dwz
# Autogenerated from man page /usr/share/man/man1/dh_dwz.1.gz
complete -c dh_dwz -l dwz-multifile -l no-dwz-multifile --description 'Whether dwz\\|(1) should generate a multifile from the \\s-1ELF\\s0 binaries in …'
complete -c dh_dwz -o Xitem -l exclude --description 'Exclude files that contain item anywhere in their filename from being strippe…'

