# dh_installwm
# Autogenerated from man page /usr/share/man/man1/dh_installwm.1.gz
complete -c dh_installwm -l priority --description 'Set the priority of the window manager.'
complete -c dh_installwm -s n -l no-scripts --description 'Do not modify postinst/prerm scripts.  Turns this command into a no-op.'
complete -c dh_installwm -s A -l all --description 'Modify scripts for window managers specified by command line parameters in \\s…'

