# dh_installdocs
# Autogenerated from man page /usr/share/man/man1/dh_installdocs.1.gz
complete -c dh_installdocs -s A -l all --description 'Install all files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_installdocs -o Xitem -l exclude --description 'Exclude files that contain item anywhere in their filename from being install…'
complete -c dh_installdocs -l sourcedir --description 'Look in the specified directory for files to be installed.'
complete -c dh_installdocs -l doc-main-package --description 'Set the main package for a documentation package.'
complete -c dh_installdocs -l link-doc --description 'Make the documentation directory of all packages acted on be a symlink to the…'

