# dh_installudev
# Autogenerated from man page /usr/share/man/man1/dh_installudev.1.gz
complete -c dh_installudev -l name --description 'When this parameter is used, dh_installudev looks for and installs files name…'

