# dh_installexamples
# Autogenerated from man page /usr/share/man/man1/dh_installexamples.1.gz
complete -c dh_installexamples -s A -l all --description 'Install any files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_installexamples -l sourcedir --description 'Look in the specified directory for files to be installed.'
complete -c dh_installexamples -l doc-main-package --description 'Set the main package for a documentation package.'
complete -c dh_installexamples -o Xitem -l exclude --description 'Exclude files that contain item anywhere in their filename from being install…'

