# dh_installman
# Autogenerated from man page /usr/share/man/man1/dh_installman.1.gz
complete -c dh_installman -s A -l all --description 'Install all files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_installman -l language --description 'Use this to specify that the man pages being acted on are written in the spec…'
complete -c dh_installman -l sourcedir --description 'Look in the specified directory for files to be installed.'

