# dh_install
# Autogenerated from man page /usr/share/man/man1/dh_install.1.gz
complete -c dh_install -l list-missing --description 'Deprecated: Please use dh_missing --list-missing instead.'
complete -c dh_install -l fail-missing --description 'Deprecated: Please use dh_missing --fail-missing instead.'
complete -c dh_install -l sourcedir --description 'Look in the specified directory for files to be installed.'
complete -c dh_install -l autodest --description 'Guess as the destination directory to install things to.'

