# dh_installdirs
# Autogenerated from man page /usr/share/man/man1/dh_installdirs.1.gz
complete -c dh_installdirs -s A -l all --description 'Create any directories specified by command line parameters in \\s-1ALL\\s0 pac…'
complete -c dh_installdirs -l create-in-sourcedir -l no-create-in-sourcedir --description 'Whether to create the specified directories in the source directory (usually …'
complete -c dh_installdirs -l sourcedir --description 'Consider dir the source directory for the packages acted on instead of the de…'

