# dh_installinfo
# Autogenerated from man page /usr/share/man/man1/dh_installinfo.1.gz
complete -c dh_installinfo -s A -l all --description 'Install all files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_installinfo -l sourcedir --description 'Look in the specified directory for files to be installed.'

