# dh_installmodules
# Autogenerated from man page /usr/share/man/man1/dh_installmodules.1.gz
complete -c dh_installmodules -s n -l no-scripts --description 'Do not modify preinst/postinst/postrm scripts.'

