# dh_movefiles
# Autogenerated from man page /usr/share/man/man1/dh_movefiles.1.gz
complete -c dh_movefiles -l sourcedir --description 'Instead of moving files out of debian/tmp (the default), this option makes it…'
complete -c dh_movefiles -o Xitem -l exclude --description 'Exclude files that contain item anywhere in their filename from being install…'

