# dh_perl
# Autogenerated from man page /usr/share/man/man1/dh_perl.1.gz
complete -c dh_perl -s d --description 'In some specific cases you may want to depend on perl-base rather than the fu…'
complete -c dh_perl -s V --description 'By default, scripts and architecture independent modules don\'t depend on any …'

