# dh_strip
# Autogenerated from man page /usr/share/man/man1/dh_strip.1.gz
complete -c dh_strip -o Xitem -l exclude --description 'Exclude files that contain item anywhere in their filename from being strippe…'
complete -c dh_strip -l dbg-package --description 'This option is a now special purpose option that you normally do not need.'
complete -c dh_strip -s k -l keep-debug --description 'This option is a now special purpose option that you normally do not need.'
complete -c dh_strip -l dbgsym-migration --description 'This option is used to migrate from a manual \\*(L"-dbg\\*(R" package (created …'
complete -c dh_strip -l automatic-dbgsym -l no-automatic-dbgsym --description 'Control whether dh_strip should be creating debug symbol packages when possib…'
complete -c dh_strip -l ddebs -l no-ddebs --description 'Historical name for --automatic-dbgsym and --no-automatic-dbgsym.'
complete -c dh_strip -l ddeb-migration --description 'Historical name for --dbgsym-migration.'

