# dh_systemd_enable
# Autogenerated from man page /usr/share/man/man1/dh_systemd_enable.1.gz
complete -c dh_systemd_enable -l no-enable --description 'Disable the service(s) on purge, but do not enable them on install.'

