# dh_systemd_start
# Autogenerated from man page /usr/share/man/man1/dh_systemd_start.1.gz
complete -c dh_systemd_start -l restart-after-upgrade --description 'Do not stop the unit file until after the package upgrade has been completed.'
complete -c dh_systemd_start -l no-restart-after-upgrade --description 'Undo a previous --restart-after-upgrade (or the default of compat 10).'
complete -c dh_systemd_start -s r -l no-stop-on-upgrade -l no-restart-on-upgrade --description 'Do not stop service on upgrade.'

