# dh_ucf
# Autogenerated from man page /usr/share/man/man1/dh_ucf.1.gz
complete -c dh_ucf -s A -l all --description 'Install all files specified by command line parameters in \\s-1ALL\\s0 packages…'
complete -c dh_ucf -s n -l no-scripts --description 'Do not modify postinst/postrm scripts.  Turns this command into a no-op.'

