# distro-info
# Autogenerated from man page /usr/share/man/man1/distro-info.1.gz
complete -c distro-info -l date --description 'date for calculating the version (default: today).'
complete -c distro-info -s h -l help --description 'display help message and exit.'
complete -c distro-info -s a -l all --description 'list all known versions.'
complete -c distro-info -s y -l days --description 'display number of days until specified version reaches the specified mileston…'
complete -c distro-info -s d -l devel --description 'latest development version.'
complete -c distro-info -l series --description 'series to calculate the version for.'
complete -c distro-info -s s -l stable --description 'latest stable version.'
complete -c distro-info -l supported --description 'list of all supported stable versions.'
complete -c distro-info -l unsupported --description 'list of all unsupported stable versions.'
complete -c distro-info -s c -l codename --description 'print the codename (default).'
complete -c distro-info -s r -l release --description 'print the release version.'
complete -c distro-info -s f -l fullname --description 'print the full name SEE ALSO debian-distro-info (1), ubuntu-distro-info (1) A…'

