# do-release-upgrade
# Autogenerated from man page /usr/share/man/man8/do-release-upgrade.8.gz
complete -c do-release-upgrade -s h -l help --description 'show help message and exit.'
complete -c do-release-upgrade -s d -l devel-release --description 'If using the latest supported release, upgrade to the development release.'
complete -c do-release-upgrade -s p -l proposed --description 'Try upgrading to the latest release using the upgrader from Ubuntu-proposed.'
complete -c do-release-upgrade -s m -l mode --description 'Run in a special upgrade mode.'

