# docker-ps
# Autogenerated from man page /usr/share/man/man1/docker-ps.1.gz
complete -c docker-ps -s a -l all --description '	Show all containers (default shows just running).'
complete -c docker-ps -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-ps -l format --description '	Pretty-print containers using a Go template.'
complete -c docker-ps -s h -l help --description '	help for ps.'
complete -c docker-ps -s n -l last -s 1 --description '	Show n last created containers (includes all states).'
complete -c docker-ps -s l -l latest --description '	Show the latest created container (includes all states).'
complete -c docker-ps -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-ps -s q -l quiet --description '	Only display container IDs.'
complete -c docker-ps -s s -l size --description '	Display total file sizes SEE ALSO.'

