# docker-plugin-create
# Autogenerated from man page /usr/share/man/man1/docker-plugin-create.1.gz
complete -c docker-plugin-create -l compress --description '	Compress the context using gzip.'
complete -c docker-plugin-create -s h -l help --description '	help for create SEE ALSO.'

