# docker-commit
# Autogenerated from man page /usr/share/man/man1/docker-commit.1.gz
complete -c docker-commit -s a -l author --description '	Author (e. g. , "John Hannibal Smith hannibal@a-team.'
complete -c docker-commit -s c -l change --description '	Apply Dockerfile instruction to the created image.'
complete -c docker-commit -s h -l help --description '	help for commit.'
complete -c docker-commit -s m -l message --description '	Commit message.'
complete -c docker-commit -s p -l pause --description '	Pause container during commit SEE ALSO.'

