# docker-node-rm
# Autogenerated from man page /usr/share/man/man1/docker-node-rm.1.gz
complete -c docker-node-rm -s f -l force --description '	Force remove a node from the swarm.'
complete -c docker-node-rm -s h -l help --description '	help for rm SEE ALSO.'

