# docker-plugin-disable
# Autogenerated from man page /usr/share/man/man1/docker-plugin-disable.1.gz
complete -c docker-plugin-disable -s f -l force --description '	Force the disable of an active plugin.'
complete -c docker-plugin-disable -s h -l help --description '	help for disable SEE ALSO.'

