# docker-container-exec
# Autogenerated from man page /usr/share/man/man1/docker-container-exec.1.gz
complete -c docker-container-exec -l privileged --description 'USER.'
complete -c docker-container-exec -s d -l detach --description '	Detached mode: run command in the background.'
complete -c docker-container-exec -l detach-keys --description '	Override the key sequence for detaching a container.'
complete -c docker-container-exec -s e -l env --description '	Set environment variables.'
complete -c docker-container-exec -l env-file --description '	Read in a file of environment variables.'
complete -c docker-container-exec -s h -l help --description '	help for exec.'
complete -c docker-container-exec -s i -l interactive --description '	Keep STDIN open even if not attached.'
complete -c docker-container-exec -s t -l tty --description '	Allocate a pseudo-TTY.'
complete -c docker-container-exec -s u -l user --description '	Username or UID (format: [:]).'
complete -c docker-container-exec -s w -l workdir --description '	Working directory inside the container SEE ALSO.'

