# docker-swarm-ca
# Autogenerated from man page /usr/share/man/man1/docker-swarm-ca.1.gz
complete -c docker-swarm-ca -l ca-cert --description '	Path to the PEM-formatted root CA certificate to use for the new cluster.'
complete -c docker-swarm-ca -l ca-key --description '	Path to the PEM-formatted root CA key to use for the new cluster.'
complete -c docker-swarm-ca -l cert-expiry --description '	Validity period for node certificates (ns|us|ms|s|m|h).'
complete -c docker-swarm-ca -s d -l detach --description '	Exit immediately instead of waiting for the root rotation to converge.'
complete -c docker-swarm-ca -l external-ca --description '	Specifications of one or more certificate signing endpoints.'
complete -c docker-swarm-ca -s h -l help --description '	help for ca.'
complete -c docker-swarm-ca -s q -l quiet --description '	Suppress progress output.'
complete -c docker-swarm-ca -l rotate --description '	Rotate the swarm CA - if no certificate or key are provided, new ones will b…'

