# docker-cp
# Autogenerated from man page /usr/share/man/man1/docker-cp.1.gz
complete -c docker-cp -s a -l archive --description '	Archive mode (copy all uid/gid information).'
complete -c docker-cp -s L -l follow-link --description '	Always follow symbol link in SRC_PATH.'
complete -c docker-cp -s h -l help --description '	help for cp SEE ALSO.'

