# docker-volume-create
# Autogenerated from man page /usr/share/man/man1/docker-volume-create.1.gz
complete -c docker-volume-create -s o -l opt --description '$ docker volume create --driver fake --opt tardis=blue --opt timey=wimey Thes…'
complete -c docker-volume-create -s d -l driver --description '	Specify volume driver name.'
complete -c docker-volume-create -s h -l help --description '	help for create.'
complete -c docker-volume-create -l label --description '	Set metadata for a volume.'

