# docker-plugin-push
# Autogenerated from man page /usr/share/man/man1/docker-plugin-push.1.gz
complete -c docker-plugin-push -l disable-content-trust --description '	Skip image signing.'
complete -c docker-plugin-push -s h -l help --description '	help for push SEE ALSO.'

