# docker-image-import
# Autogenerated from man page /usr/share/man/man1/docker-image-import.1.gz
complete -c docker-image-import -l platform --description 'daemon.  # docker image import --platform=linux . \\linuximage. tar See also.'
complete -c docker-image-import -s c -l change --description '	Apply Dockerfile instruction to the created image.'
complete -c docker-image-import -s h -l help --description '	help for import.'
complete -c docker-image-import -s m -l message --description '	Set commit message for imported image.'

