# docker-checkpoint-rm
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-rm.1.gz
complete -c docker-checkpoint-rm -l checkpoint-dir --description '	Use a custom checkpoint storage directory.'
complete -c docker-checkpoint-rm -s h -l help --description '	help for rm SEE ALSO.'

