# docker-images
# Autogenerated from man page /usr/share/man/man1/docker-images.1.gz
complete -c docker-images -s a -l all --description '	Show all images (default hides intermediate images).'
complete -c docker-images -l digests --description '	Show digests.'
complete -c docker-images -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-images -l format --description '	Pretty-print images using a Go template.'
complete -c docker-images -s h -l help --description '	help for images.'
complete -c docker-images -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-images -s q -l quiet --description '	Only show image IDs SEE ALSO.'

