# docker-context-create
# Autogenerated from man page /usr/share/man/man1/docker-context-create.1.gz
complete -c docker-context-create -l default-stack-orchestrator --description '	Default orchestrator for stack operations to use with this context (swarm|ku…'
complete -c docker-context-create -l description --description '	Description of the context.'
complete -c docker-context-create -l docker --description '	set the docker endpoint.'
complete -c docker-context-create -l from --description '	create context from a named context.'
complete -c docker-context-create -s h -l help --description '	help for create.'
complete -c docker-context-create -l kubernetes --description '	set the kubernetes endpoint SEE ALSO.'

