# docker-context-ls
# Autogenerated from man page /usr/share/man/man1/docker-context-ls.1.gz
complete -c docker-context-ls -l format --description '	Pretty-print contexts using a Go template.'
complete -c docker-context-ls -s h -l help --description '	help for ls.'
complete -c docker-context-ls -s q -l quiet --description '	Only show context names SEE ALSO.'

