# docker-history
# Autogenerated from man page /usr/share/man/man1/docker-history.1.gz
complete -c docker-history -l format --description '	Pretty-print images using a Go template.'
complete -c docker-history -s h -l help --description '	help for history.'
complete -c docker-history -s H -l human --description '	Print sizes and dates in human readable format.'
complete -c docker-history -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-history -s q -l quiet --description '	Only show image IDs SEE ALSO.'

