# docker-compose
# Autogenerated from man page /usr/share/man/man1/docker-compose.1.gz
complete -c docker-compose -s f -l file --description 'Specify an alternate compose file (default: docker-compose. yml).'
complete -c docker-compose -s p -l project-name --description 'Specify an alternate project name (default: directory name).'
complete -c docker-compose -l verbose --description 'Show more output.'
complete -c docker-compose -s v -l version --description 'Print version and exit COMMANDS build Build or rebuild services.'
complete -c docker-compose -l no-cache --description 'Do not use cache when building the image.'
complete -c docker-compose -s s --description 'SIGNAL to send to the container.  Default signal is SIGKILL.'
complete -c docker-compose -l no-color --description 'Produce a monochrome output.'
complete -c docker-compose -l protocol --description 'Choose the 4th layer protocol, tcp or udp.  Default is tcp.'
complete -c docker-compose -l index --description 'Index of the container if there are multiple instances of a service.'
complete -c docker-compose -s q --description 'Only display IDs.  pull Pulls service images from Docker registry.'
complete -c docker-compose -l allow-insecure-ssl --description 'Allow insecure connections to the Docker registry.'
complete -c docker-compose -s t -l timeout --description 'Specify a shutdown timeout in seconds.  Default is 10.'
complete -c docker-compose -l force --description 'Do not ask to confirm removal.'
complete -c docker-compose -s d --description 'Detached mode.  Run container in the background, print new container name.'
complete -c docker-compose -l entrypoint --description 'Override the entrypoint of the image with CMD.'
complete -c docker-compose -s e --description 'Set an environment variable.  Can be used multiple times.'
complete -c docker-compose -s u -l user --description 'Run as a specific USER, a username or uid.'
complete -c docker-compose -l no-deps --description 'Do not start linked services.'
complete -c docker-compose -l rm --description 'Remove container after run.  This option is ignored in the detached mode.'
complete -c docker-compose -l service-ports --description 'Run command with the service\'s ports enabled and mapped to the host.'
complete -c docker-compose -s T --description 'Disable pseudo tty allocation.  By default a tty is allocated.'
complete -c docker-compose -l x-smart-recreate --description 'Only recreate containers whose configuration or image needs to be updated.'
complete -c docker-compose -l no-recreate --description 'If containers already exist, do not recreate them.'
complete -c docker-compose -l no-build --description 'Do not build an image even if it is missing.'

