# docker-save
# Autogenerated from man page /usr/share/man/man1/docker-save.1.gz
complete -c docker-save -s h -l help --description '	help for save.'
complete -c docker-save -s o -l output --description '	Write to a file, instead of STDOUT SEE ALSO.'

