# docker-network-inspect
# Autogenerated from man page /usr/share/man/man1/docker-network-inspect.1.gz
complete -c docker-network-inspect -s f -l format --description '	Format the output using the given Go template.'
complete -c docker-network-inspect -s h -l help --description '	help for inspect.'
complete -c docker-network-inspect -s v -l verbose --description '	Verbose output for diagnostics SEE ALSO.'

