# docker-pull
# Autogenerated from man page /usr/share/man/man1/docker-pull.1.gz
complete -c docker-pull -s a -l all-tags --description '	Download all tagged images in the repository.'
complete -c docker-pull -l disable-content-trust --description '	Skip image verification.'
complete -c docker-pull -s h -l help --description '	help for pull.'
complete -c docker-pull -l platform --description '	Set platform if server is multi-platform capable.'
complete -c docker-pull -s q -l quiet --description '	Suppress verbose output SEE ALSO.'

