# docker-trust-revoke
# Autogenerated from man page /usr/share/man/man1/docker-trust-revoke.1.gz
complete -c docker-trust-revoke -s h -l help --description '	help for revoke.'
complete -c docker-trust-revoke -s y -l yes --description '	Do not prompt for confirmation SEE ALSO.'

