# docker-secret-ls
# Autogenerated from man page /usr/share/man/man1/docker-secret-ls.1.gz
complete -c docker-secret-ls -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-secret-ls -l format --description '	Pretty-print secrets using a Go template.'
complete -c docker-secret-ls -s h -l help --description '	help for ls.'
complete -c docker-secret-ls -s q -l quiet --description '	Only display IDs SEE ALSO.'

