# docker-image-prune
# Autogenerated from man page /usr/share/man/man1/docker-image-prune.1.gz
complete -c docker-image-prune -s a -l all --description '	Remove all unused images, not just dangling ones.'
complete -c docker-image-prune -l filter --description '	Provide filter values (e. g.  \'until=\').'
complete -c docker-image-prune -s f -l force --description '	Do not prompt for confirmation.'
complete -c docker-image-prune -s h -l help --description '	help for prune SEE ALSO.'

