# docker-volume-ls
# Autogenerated from man page /usr/share/man/man1/docker-volume-ls.1.gz
complete -c docker-volume-ls -l filter --description 'more than one filter,  pass multiple flags (for example,.'
complete -c docker-volume-ls -s f --description '	Provide filter values (e. g.  \'dangling=true\').'
complete -c docker-volume-ls -l format --description '	Pretty-print volumes using a Go template.'
complete -c docker-volume-ls -s h -l help --description '	help for ls.'
complete -c docker-volume-ls -s q -l quiet --description '	Only display volume names SEE ALSO.'

