# docker-network-connect
# Autogenerated from man page /usr/share/man/man1/docker-network-connect.1.gz
complete -c docker-network-connect -l alias --description '	Add network-scoped alias for the container.'
complete -c docker-network-connect -l driver-opt --description '	driver options for the network.'
complete -c docker-network-connect -s h -l help --description '	help for connect.'
complete -c docker-network-connect -l ip --description '	IPv4 address (e. g. , 172. 30. 100. 104).'
complete -c docker-network-connect -l ip6 --description '	IPv6 address (e. g. , 2001:db8::33).'
complete -c docker-network-connect -l link --description '	Add link to another container.'
complete -c docker-network-connect -l link-local-ip --description '	Add a link-local address for the container SEE ALSO.'

