# docker-system-df
# Autogenerated from man page /usr/share/man/man1/docker-system-df.1.gz
complete -c docker-system-df -l format --description '	Pretty-print images using a Go template.'
complete -c docker-system-df -s h -l help --description '	help for df.'
complete -c docker-system-df -s v -l verbose --description '	Show detailed information on space usage SEE ALSO.'

