# docker-search
# Autogenerated from man page /usr/share/man/man1/docker-search.1.gz
complete -c docker-search -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-search -l format --description '	Pretty-print search using a Go template.'
complete -c docker-search -s h -l help --description '	help for search.'
complete -c docker-search -l limit --description '	Max number of search results.'
complete -c docker-search -l no-trunc --description '	Don\'t truncate output SEE ALSO.'

