# docker-service-logs
# Autogenerated from man page /usr/share/man/man1/docker-service-logs.1.gz
complete -c docker-service-logs -l details --description '	Show extra details provided to logs.'
complete -c docker-service-logs -s f -l follow --description '	Follow log output.'
complete -c docker-service-logs -s h -l help --description '	help for logs.'
complete -c docker-service-logs -l no-resolve --description '	Do not map IDs to Names in output.'
complete -c docker-service-logs -l no-task-ids --description '	Do not include task IDs in output.'
complete -c docker-service-logs -l no-trunc --description '	Do not truncate output.'
complete -c docker-service-logs -l raw --description '	Do not neatly format logs.'
complete -c docker-service-logs -l since --description '	Show logs since timestamp (e. g.  2013-01-02T13:23:37Z) or relative (e. g.'
complete -c docker-service-logs -s n -l tail --description '	Number of lines to show from the end of the logs.'
complete -c docker-service-logs -s t -l timestamps --description '	Show timestamps SEE ALSO.'

