# docker-plugin-rm
# Autogenerated from man page /usr/share/man/man1/docker-plugin-rm.1.gz
complete -c docker-plugin-rm -s f -l force --description '	Force the removal of an active plugin.'
complete -c docker-plugin-rm -s h -l help --description '	help for rm SEE ALSO.'

