# docker-stack-ls
# Autogenerated from man page /usr/share/man/man1/docker-stack-ls.1.gz
complete -c docker-stack-ls -l all-namespaces --description '	List stacks from all Kubernetes namespaces.'
complete -c docker-stack-ls -l format --description '	Pretty-print stacks using a Go template.'
complete -c docker-stack-ls -s h -l help --description '	help for ls.'
complete -c docker-stack-ls -l namespace --description '	Kubernetes namespaces to use OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c docker-stack-ls -l kubeconfig --description '	Kubernetes config file.'
complete -c docker-stack-ls -l orchestrator --description '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO.'

