# docker
# Autogenerated from man page /usr/share/man/man1/docker.1.gz
complete -c docker -l help --description '  Print usage statement.'
complete -c docker -l config --description '  Specifies the location of the Docker client configuration files.'
complete -c docker -s D -l debug --description '  Enable debug mode.  Default is false.'
complete -c docker -s H -l host --description 'unix://[/path/to/socket] to use.'
complete -c docker -s l -l log-level --description '  Set the logging level.  Default is info.'
complete -c docker -l tls --description '  Use TLS; implied by --tlsverify.  Default is false.'
complete -c docker -l tlscacert --description '  Trust certs signed only by this CA.'
complete -c docker -l tlscert --description '  Path to TLS certificate file.'
complete -c docker -l tlskey --description '  Path to TLS key file.'
complete -c docker -l tlsverify --description '  Use TLS and verify the remote (daemon: verify client, client: verify daemon…'
complete -c docker -s v -l version --description '  Print version information and quit.  Default is false.  COMMANDS.'

