# docker-node-ls
# Autogenerated from man page /usr/share/man/man1/docker-node-ls.1.gz
complete -c docker-node-ls -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-node-ls -l format --description '	Pretty-print nodes using a Go template.'
complete -c docker-node-ls -s h -l help --description '	help for ls.'
complete -c docker-node-ls -s q -l quiet --description '	Only display IDs SEE ALSO.'

