# docker-volume-prune
# Autogenerated from man page /usr/share/man/man1/docker-volume-prune.1.gz
complete -c docker-volume-prune -l filter --description '	Provide filter values (e. g.  \'label=\').'
complete -c docker-volume-prune -s f -l force --description '	Do not prompt for confirmation.'
complete -c docker-volume-prune -s h -l help --description '	help for prune SEE ALSO.'

