# docker-builder-prune
# Autogenerated from man page /usr/share/man/man1/docker-builder-prune.1.gz
complete -c docker-builder-prune -s a -l all --description '	Remove all unused build cache, not just dangling ones.'
complete -c docker-builder-prune -l filter --description '	Provide filter values (e. g.  \'until=24h\').'
complete -c docker-builder-prune -s f -l force --description '	Do not prompt for confirmation.'
complete -c docker-builder-prune -s h -l help --description '	help for prune.'
complete -c docker-builder-prune -l keep-storage --description '	Amount of disk space to keep for cache SEE ALSO.'

