# docker-service-ls
# Autogenerated from man page /usr/share/man/man1/docker-service-ls.1.gz
complete -c docker-service-ls -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-service-ls -l format --description '	Pretty-print services using a Go template.'
complete -c docker-service-ls -s h -l help --description '	help for ls.'
complete -c docker-service-ls -s q -l quiet --description '	Only display IDs SEE ALSO.'

