# docker-stack-rm
# Autogenerated from man page /usr/share/man/man1/docker-stack-rm.1.gz
complete -c docker-stack-rm -s h -l help --description '	help for rm.'
complete -c docker-stack-rm -l namespace --description '	Kubernetes namespace to use OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c docker-stack-rm -l kubeconfig --description '	Kubernetes config file.'
complete -c docker-stack-rm -l orchestrator --description '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO.'

