# docker-plugin-upgrade
# Autogenerated from man page /usr/share/man/man1/docker-plugin-upgrade.1.gz
complete -c docker-plugin-upgrade -l disable-content-trust --description '	Skip image verification.'
complete -c docker-plugin-upgrade -l grant-all-permissions --description '	Grant all permissions necessary to run the plugin.'
complete -c docker-plugin-upgrade -s h -l help --description '	help for upgrade.'
complete -c docker-plugin-upgrade -l skip-remote-check --description '	Do not check if specified remote plugin matches existing plugin image SEE AL…'

