# docker-node-ps
# Autogenerated from man page /usr/share/man/man1/docker-node-ps.1.gz
complete -c docker-node-ps -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-node-ps -l format --description '	Pretty-print tasks using a Go template.'
complete -c docker-node-ps -s h -l help --description '	help for ps.'
complete -c docker-node-ps -l no-resolve --description '	Do not map IDs to Names.'
complete -c docker-node-ps -l no-trunc --description '	Do not truncate output.'
complete -c docker-node-ps -s q -l quiet --description '	Only display task IDs SEE ALSO.'

