# docker-trust-inspect
# Autogenerated from man page /usr/share/man/man1/docker-trust-inspect.1.gz
complete -c docker-trust-inspect -s h -l help --description '	help for inspect.'
complete -c docker-trust-inspect -l pretty --description '	Print the information in a human friendly format SEE ALSO.'

