# docker-plugin-install
# Autogenerated from man page /usr/share/man/man1/docker-plugin-install.1.gz
complete -c docker-plugin-install -l alias --description '	Local name for plugin.'
complete -c docker-plugin-install -l disable --description '	Do not enable the plugin on install.'
complete -c docker-plugin-install -l disable-content-trust --description '	Skip image verification.'
complete -c docker-plugin-install -l grant-all-permissions --description '	Grant all permissions necessary to run the plugin.'
complete -c docker-plugin-install -s h -l help --description '	help for install SEE ALSO.'

