# docker-image-ls
# Autogenerated from man page /usr/share/man/man1/docker-image-ls.1.gz
complete -c docker-image-ls -s a -l all --description '	Show all images (default hides intermediate images).'
complete -c docker-image-ls -l digests --description '	Show digests.'
complete -c docker-image-ls -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-image-ls -l format --description '	Pretty-print images using a Go template.'
complete -c docker-image-ls -s h -l help --description '	help for ls.'
complete -c docker-image-ls -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-image-ls -s q -l quiet --description '	Only show image IDs SEE ALSO.'

