# docker-service-scale
# Autogenerated from man page /usr/share/man/man1/docker-service-scale.1.gz
complete -c docker-service-scale -s d -l detach --description '	Exit immediately instead of waiting for the service to converge.'
complete -c docker-service-scale -s h -l help --description '	help for scale SEE ALSO.'

