# docker-manifest-inspect
# Autogenerated from man page /usr/share/man/man1/docker-manifest-inspect.1.gz
complete -c docker-manifest-inspect -s h -l help --description '	help for inspect.'
complete -c docker-manifest-inspect -l insecure --description '	Allow communication with an insecure registry.'
complete -c docker-manifest-inspect -s v -l verbose --description '	Output additional info including layers and platform SEE ALSO.'

