# docker-stack-deploy
# Autogenerated from man page /usr/share/man/man1/docker-stack-deploy.1.gz
complete -c docker-stack-deploy -s c -l compose-file --description '	Path to a Compose file, or "-" to read from stdin.'
complete -c docker-stack-deploy -s h -l help --description '	help for deploy.'
complete -c docker-stack-deploy -l namespace --description '	Kubernetes namespace to use.'
complete -c docker-stack-deploy -l prune --description '	Prune services that are no longer referenced.'
complete -c docker-stack-deploy -l resolve-image --description '	Query the registry to resolve image digest and supported platforms ("always"…'
complete -c docker-stack-deploy -l with-registry-auth --description '	Send registry authentication details to Swarm agents OPTIONS INHERITED FROM …'
complete -c docker-stack-deploy -l kubeconfig --description '	Kubernetes config file.'
complete -c docker-stack-deploy -l orchestrator --description '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO.'

