# docker-image-push
# Autogenerated from man page /usr/share/man/man1/docker-image-push.1.gz
complete -c docker-image-push -s a -l all-tags --description '	Push all tagged images in the repository.'
complete -c docker-image-push -l disable-content-trust --description '	Skip image signing.'
complete -c docker-image-push -s h -l help --description '	help for push.'
complete -c docker-image-push -s q -l quiet --description '	Suppress verbose output SEE ALSO.'

