# docker-trust-signer-add
# Autogenerated from man page /usr/share/man/man1/docker-trust-signer-add.1.gz
complete -c docker-trust-signer-add -s h -l help --description '	help for add.'
complete -c docker-trust-signer-add -l key --description '	Path to the signer\'s public key file SEE ALSO.'

