# docker-context-rm
# Autogenerated from man page /usr/share/man/man1/docker-context-rm.1.gz
complete -c docker-context-rm -s f -l force --description '	Force the removal of a context in use.'
complete -c docker-context-rm -s h -l help --description '	help for rm SEE ALSO.'

