# docker-stack-ps
# Autogenerated from man page /usr/share/man/man1/docker-stack-ps.1.gz
complete -c docker-stack-ps -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-stack-ps -l format --description '	Pretty-print tasks using a Go template.'
complete -c docker-stack-ps -s h -l help --description '	help for ps.'
complete -c docker-stack-ps -l namespace --description '	Kubernetes namespace to use.'
complete -c docker-stack-ps -l no-resolve --description '	Do not map IDs to Names.'
complete -c docker-stack-ps -l no-trunc --description '	Do not truncate output.'
complete -c docker-stack-ps -s q -l quiet --description '	Only display task IDs OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c docker-stack-ps -l kubeconfig --description '	Kubernetes config file.'
complete -c docker-stack-ps -l orchestrator --description '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO.'

