# docker-import
# Autogenerated from man page /usr/share/man/man1/docker-import.1.gz
complete -c docker-import -s c -l change --description '	Apply Dockerfile instruction to the created image.'
complete -c docker-import -s h -l help --description '	help for import.'
complete -c docker-import -s m -l message --description '	Set commit message for imported image.'
complete -c docker-import -l platform --description '	Set platform if server is multi-platform capable SEE ALSO.'

