# docker-version
# Autogenerated from man page /usr/share/man/man1/docker-version.1.gz
complete -c docker-version -s f -l format --description '	Format the output using the given Go template.'
complete -c docker-version -s h -l help --description '	help for version.'
complete -c docker-version -l kubeconfig --description '	Kubernetes config file SEE ALSO.'

