# docker-container-restart
# Autogenerated from man page /usr/share/man/man1/docker-container-restart.1.gz
complete -c docker-container-restart -s h -l help --description '	help for restart.'
complete -c docker-container-restart -s t -l time --description '	Seconds to wait for stop before killing the container SEE ALSO.'

