# docker-plugin-enable
# Autogenerated from man page /usr/share/man/man1/docker-plugin-enable.1.gz
complete -c docker-plugin-enable -s h -l help --description '	help for enable.'
complete -c docker-plugin-enable -l timeout --description '	HTTP client timeout (in seconds) SEE ALSO.'

