# docker-config-create
# Autogenerated from man page /usr/share/man/man1/docker-config-create.1.gz
complete -c docker-config-create -s h -l help --description '	help for create.'
complete -c docker-config-create -s l -l label --description '	Config labels.'
complete -c docker-config-create -l template-driver --description '	Template driver SEE ALSO.'

