# docker-container-attach
# Autogenerated from man page /usr/share/man/man1/docker-container-attach.1.gz
complete -c docker-container-attach -l detach-keys --description 'the <sequence> is either a letter [a-Z], or the ctrl- combined with any of th…'
complete -c docker-container-attach -s h -l help --description '	help for attach.'
complete -c docker-container-attach -l no-stdin --description '	Do not attach STDIN.'
complete -c docker-container-attach -l sig-proxy --description '	Proxy all received signals to the process SEE ALSO.'

