# docker-image-history
# Autogenerated from man page /usr/share/man/man1/docker-image-history.1.gz
complete -c docker-image-history -l human --description ', otherwise timestamp of when image was created T} .'
complete -c docker-image-history -l format --description '	Pretty-print images using a Go template.'
complete -c docker-image-history -s h -l help --description '	help for history.'
complete -c docker-image-history -s H --description '	Print sizes and dates in human readable format.'
complete -c docker-image-history -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-image-history -s q -l quiet --description '	Only show image IDs SEE ALSO.'

