# docker-volume-rm
# Autogenerated from man page /usr/share/man/man1/docker-volume-rm.1.gz
complete -c docker-volume-rm -s f -l force --description '	Force the removal of one or more volumes.'
complete -c docker-volume-rm -s h -l help --description '	help for rm EXAMPLE $ docker volume rm hello hello SEE ALSO.'

