# docker-system-prune
# Autogenerated from man page /usr/share/man/man1/docker-system-prune.1.gz
complete -c docker-system-prune -s a -l all --description '	Remove all unused images not just dangling ones.'
complete -c docker-system-prune -l filter --description '	Provide filter values (e. g.  \'label==\').'
complete -c docker-system-prune -s f -l force --description '	Do not prompt for confirmation.'
complete -c docker-system-prune -s h -l help --description '	help for prune.'
complete -c docker-system-prune -l volumes --description '	Prune volumes SEE ALSO.'

