# docker-events
# Autogenerated from man page /usr/share/man/man1/docker-events.1.gz
complete -c docker-events -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-events -l format --description '	Format the output using the given Go template.'
complete -c docker-events -s h -l help --description '	help for events.'
complete -c docker-events -l since --description '	Show all events created since timestamp.'
complete -c docker-events -l until --description '	Stream events until this timestamp SEE ALSO.'

