# docker-context-inspect
# Autogenerated from man page /usr/share/man/man1/docker-context-inspect.1.gz
complete -c docker-context-inspect -s f -l format --description '	Format the output using the given Go template.'
complete -c docker-context-inspect -s h -l help --description '	help for inspect SEE ALSO.'

