# docker-swarm-join
# Autogenerated from man page /usr/share/man/man1/docker-swarm-join.1.gz
complete -c docker-swarm-join -l advertise-addr --description '	Advertised address (format: [:port]).'
complete -c docker-swarm-join -l availability --description '	Availability of the node ("active"|"pause"|"drain").'
complete -c docker-swarm-join -l data-path-addr --description '	Address or interface to use for data path traffic (format: ).'
complete -c docker-swarm-join -s h -l help --description '	help for join.'
complete -c docker-swarm-join -l listen-addr --description '	Listen address (format: [:port]).'
complete -c docker-swarm-join -l token --description '	Token for entry into the swarm SEE ALSO.'

