# docker-attach
# Autogenerated from man page /usr/share/man/man1/docker-attach.1.gz
complete -c docker-attach -l detach-keys --description '	Override the key sequence for detaching a container.'
complete -c docker-attach -s h -l help --description '	help for attach.'
complete -c docker-attach -l no-stdin --description '	Do not attach STDIN.'
complete -c docker-attach -l sig-proxy --description '	Proxy all received signals to the process SEE ALSO.'

