# docker-context-export
# Autogenerated from man page /usr/share/man/man1/docker-context-export.1.gz
complete -c docker-context-export -s h -l help --description '	help for export.'
complete -c docker-context-export -l kubeconfig --description '	Export as a kubeconfig file SEE ALSO.'

