# docker-container-inspect
# Autogenerated from man page /usr/share/man/man1/docker-container-inspect.1.gz
complete -c docker-container-inspect -s f -l format --description '	Format the output using the given Go template.'
complete -c docker-container-inspect -s h -l help --description '	help for inspect.'
complete -c docker-container-inspect -s s -l size --description '	Display total file sizes SEE ALSO.'

