# docker-checkpoint-ls
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-ls.1.gz
complete -c docker-checkpoint-ls -l checkpoint-dir --description '	Use a custom checkpoint storage directory.'
complete -c docker-checkpoint-ls -s h -l help --description '	help for ls SEE ALSO.'

