# docker-login
# Autogenerated from man page /usr/share/man/man1/docker-login.1.gz
complete -c docker-login -s h -l help --description '	help for login.'
complete -c docker-login -s p -l password --description '	Password.'
complete -c docker-login -l password-stdin --description '	Take the password from stdin.'
complete -c docker-login -s u -l username --description '	Username SEE ALSO.'

