# docker-container-stop
# Autogenerated from man page /usr/share/man/man1/docker-container-stop.1.gz
complete -c docker-container-stop -s h -l help --description '	help for stop.'
complete -c docker-container-stop -s t -l time --description '	Seconds to wait for stop before killing it SEE ALSO.'

