# docker-info
# Autogenerated from man page /usr/share/man/man1/docker-info.1.gz
complete -c docker-info -s f -l format --description '	Format the output using the given Go template.'
complete -c docker-info -s h -l help --description '	help for info SEE ALSO.'

