# docker-container-prune
# Autogenerated from man page /usr/share/man/man1/docker-container-prune.1.gz
complete -c docker-container-prune -l filter --description '	Provide filter values (e. g.  \'until=\').'
complete -c docker-container-prune -s f -l force --description '	Do not prompt for confirmation.'
complete -c docker-container-prune -s h -l help --description '	help for prune SEE ALSO.'

