# docker-rm
# Autogenerated from man page /usr/share/man/man1/docker-rm.1.gz
complete -c docker-rm -s f -l force --description '	Force the removal of a running container (uses SIGKILL).'
complete -c docker-rm -s h -l help --description '	help for rm.'
complete -c docker-rm -s l -l link --description '	Remove the specified link.'
complete -c docker-rm -s v -l volumes --description '	Remove anonymous volumes associated with the container SEE ALSO.'

