# docker-container-update
# Autogenerated from man page /usr/share/man/man1/docker-container-update.1.gz
complete -c docker-container-update -l blkio-weight --description '	Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0).'
complete -c docker-container-update -l cpu-period --description '	Limit CPU CFS (Completely Fair Scheduler) period.'
complete -c docker-container-update -l cpu-quota --description '	Limit CPU CFS (Completely Fair Scheduler) quota.'
complete -c docker-container-update -l cpu-rt-period --description '	Limit the CPU real-time period in microseconds.'
complete -c docker-container-update -l cpu-rt-runtime --description '	Limit the CPU real-time runtime in microseconds.'
complete -c docker-container-update -s c -l cpu-shares --description '	CPU shares (relative weight).'
complete -c docker-container-update -l cpus --description '	Number of CPUs.'
complete -c docker-container-update -l cpuset-cpus --description '	CPUs in which to allow execution (0-3, 0,1).'
complete -c docker-container-update -l cpuset-mems --description '	MEMs in which to allow execution (0-3, 0,1).'
complete -c docker-container-update -s h -l help --description '	help for update.'
complete -c docker-container-update -l kernel-memory --description '	Kernel memory limit.'
complete -c docker-container-update -s m -l memory --description '	Memory limit.'
complete -c docker-container-update -l memory-reservation --description '	Memory soft limit.'
complete -c docker-container-update -l memory-swap --description '	Swap limit equal to memory plus swap: \'-1\' to enable unlimited swap.'
complete -c docker-container-update -l pids-limit --description '	Tune container pids limit (set -1 for unlimited).'
complete -c docker-container-update -l restart --description '	Restart policy to apply when a container exits SEE ALSO.'

