# docker-secret-inspect
# Autogenerated from man page /usr/share/man/man1/docker-secret-inspect.1.gz
complete -c docker-secret-inspect -s f -l format --description '	Format the output using the given Go template.'
complete -c docker-secret-inspect -s h -l help --description '	help for inspect.'
complete -c docker-secret-inspect -l pretty --description '	Print the information in a human friendly format SEE ALSO.'

