# docker-load
# Autogenerated from man page /usr/share/man/man1/docker-load.1.gz
complete -c docker-load -s h -l help --description '	help for load.'
complete -c docker-load -s i -l input --description '	Read from tar archive file, instead of STDIN.'
complete -c docker-load -s q -l quiet --description '	Suppress the load output SEE ALSO.'

