# docker-kill
# Autogenerated from man page /usr/share/man/man1/docker-kill.1.gz
complete -c docker-kill -s h -l help --description '	help for kill.'
complete -c docker-kill -s s -l signal --description '	Signal to send to the container SEE ALSO.'

