# docker-trust-key-load
# Autogenerated from man page /usr/share/man/man1/docker-trust-key-load.1.gz
complete -c docker-trust-key-load -s h -l help --description '	help for load.'
complete -c docker-trust-key-load -l name --description '	Name for the loaded key SEE ALSO.'

