# docker-swarm-unlock-key
# Autogenerated from man page /usr/share/man/man1/docker-swarm-unlock-key.1.gz
complete -c docker-swarm-unlock-key -s h -l help --description '	help for unlock-key.'
complete -c docker-swarm-unlock-key -s q -l quiet --description '	Only display token.'
complete -c docker-swarm-unlock-key -l rotate --description '	Rotate unlock key SEE ALSO.'

