# docker-logs
# Autogenerated from man page /usr/share/man/man1/docker-logs.1.gz
complete -c docker-logs -l details --description '	Show extra details provided to logs.'
complete -c docker-logs -s f -l follow --description '	Follow log output.'
complete -c docker-logs -s h -l help --description '	help for logs.'
complete -c docker-logs -l since --description '	Show logs since timestamp (e. g.  2013-01-02T13:23:37Z) or relative (e. g.'
complete -c docker-logs -s n -l tail --description '	Number of lines to show from the end of the logs.'
complete -c docker-logs -s t -l timestamps --description '	Show timestamps.'
complete -c docker-logs -l until --description '	Show logs before a timestamp (e. g.  2013-01-02T13:23:37Z) or relative (e. g.'

