# docker-container-export
# Autogenerated from man page /usr/share/man/man1/docker-container-export.1.gz
complete -c docker-container-export -s h -l help --description '	help for export.'
complete -c docker-container-export -s o -l output --description '	Write to a file, instead of STDOUT SEE ALSO.'

