# docker-image-rm
# Autogenerated from man page /usr/share/man/man1/docker-image-rm.1.gz
complete -c docker-image-rm -s f -l force --description '	Force removal of the image.'
complete -c docker-image-rm -s h -l help --description '	help for rm.'
complete -c docker-image-rm -l no-prune --description '	Do not delete untagged parents SEE ALSO.'

