# docker-network-disconnect
# Autogenerated from man page /usr/share/man/man1/docker-network-disconnect.1.gz
complete -c docker-network-disconnect -s f -l force --description '	Force the container to disconnect from a network.'
complete -c docker-network-disconnect -s h -l help --description '	help for disconnect SEE ALSO.'

