# docker-manifest-push
# Autogenerated from man page /usr/share/man/man1/docker-manifest-push.1.gz
complete -c docker-manifest-push -s h -l help --description '	help for push.'
complete -c docker-manifest-push -l insecure --description '	Allow push to an insecure registry.'
complete -c docker-manifest-push -s p -l purge --description '	Remove the local manifest list after push SEE ALSO.'

