# docker-manifest-create
# Autogenerated from man page /usr/share/man/man1/docker-manifest-create.1.gz
complete -c docker-manifest-create -s a -l amend --description '	Amend an existing manifest list.'
complete -c docker-manifest-create -s h -l help --description '	help for create.'
complete -c docker-manifest-create -l insecure --description '	Allow communication with an insecure registry SEE ALSO.'

