# docker-swarm-leave
# Autogenerated from man page /usr/share/man/man1/docker-swarm-leave.1.gz
complete -c docker-swarm-leave -s f -l force --description '	Force this node to leave the swarm, ignoring warnings.'
complete -c docker-swarm-leave -s h -l help --description '	help for leave SEE ALSO.'

