# docker-stack
# Autogenerated from man page /usr/share/man/man1/docker-stack.1.gz
complete -c docker-stack -s h -l help --description '	help for stack.'
complete -c docker-stack -l kubeconfig --description '	Kubernetes config file.'
complete -c docker-stack -l orchestrator --description '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO.'

