# docker-context-update
# Autogenerated from man page /usr/share/man/man1/docker-context-update.1.gz
complete -c docker-context-update -l default-stack-orchestrator --description '	Default orchestrator for stack operations to use with this context (swarm|ku…'
complete -c docker-context-update -l description --description '	Description of the context.'
complete -c docker-context-update -l docker --description '	set the docker endpoint.'
complete -c docker-context-update -s h -l help --description '	help for update.'
complete -c docker-context-update -l kubernetes --description '	set the kubernetes endpoint SEE ALSO.'

