# docker-secret-create
# Autogenerated from man page /usr/share/man/man1/docker-secret-create.1.gz
complete -c docker-secret-create -s d -l driver --description '	Secret driver.'
complete -c docker-secret-create -s h -l help --description '	help for create.'
complete -c docker-secret-create -s l -l label --description '	Secret labels.'
complete -c docker-secret-create -l template-driver --description '	Template driver SEE ALSO.'

