# docker-manifest-annotate
# Autogenerated from man page /usr/share/man/man1/docker-manifest-annotate.1.gz
complete -c docker-manifest-annotate -l arch --description '	Set architecture.'
complete -c docker-manifest-annotate -s h -l help --description '	help for annotate.'
complete -c docker-manifest-annotate -l os --description '	Set operating system.'
complete -c docker-manifest-annotate -l os-features --description '	Set operating system feature.'
complete -c docker-manifest-annotate -l os-version --description '	Set operating system version.'
complete -c docker-manifest-annotate -l variant --description '	Set architecture variant SEE ALSO.'

