# docker-swarm-init
# Autogenerated from man page /usr/share/man/man1/docker-swarm-init.1.gz
complete -c docker-swarm-init -l advertise-addr --description '	Advertised address (format: [:port]).'
complete -c docker-swarm-init -l autolock --description '	Enable manager autolocking (requiring an unlock key to start a stopped manag…'
complete -c docker-swarm-init -l availability --description '	Availability of the node ("active"|"pause"|"drain").'
complete -c docker-swarm-init -l cert-expiry --description '	Validity period for node certificates (ns|us|ms|s|m|h).'
complete -c docker-swarm-init -l data-path-addr --description '	Address or interface to use for data path traffic (format: ).'
complete -c docker-swarm-init -l data-path-port --description '	Port number to use for data path traffic (1024 - 49151).'
complete -c docker-swarm-init -l default-addr-pool --description '	default address pool in CIDR format.'
complete -c docker-swarm-init -l default-addr-pool-mask-length --description '	default address pool subnet mask length.'
complete -c docker-swarm-init -l dispatcher-heartbeat --description '	Dispatcher heartbeat period (ns|us|ms|s|m|h).'
complete -c docker-swarm-init -l external-ca --description '	Specifications of one or more certificate signing endpoints.'
complete -c docker-swarm-init -l force-new-cluster --description '	Force create a new cluster from current state.'
complete -c docker-swarm-init -s h -l help --description '	help for init.'
complete -c docker-swarm-init -l listen-addr --description '	Listen address (format: [:port]).'
complete -c docker-swarm-init -l max-snapshots --description '	Number of additional Raft snapshots to retain.'
complete -c docker-swarm-init -l snapshot-interval --description '	Number of log entries between Raft snapshots.'
complete -c docker-swarm-init -l task-history-limit --description '	Task history retention limit SEE ALSO.'

