# docker-plugin-ls
# Autogenerated from man page /usr/share/man/man1/docker-plugin-ls.1.gz
complete -c docker-plugin-ls -s f -l filter --description '	Provide filter values (e. g.  \'enabled=true\').'
complete -c docker-plugin-ls -l format --description '	Pretty-print plugins using a Go template.'
complete -c docker-plugin-ls -s h -l help --description '	help for ls.'
complete -c docker-plugin-ls -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-plugin-ls -s q -l quiet --description '	Only display plugin IDs SEE ALSO.'

