# docker-checkpoint-create
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-create.1.gz
complete -c docker-checkpoint-create -l checkpoint-dir --description '	Use a custom checkpoint storage directory.'
complete -c docker-checkpoint-create -s h -l help --description '	help for create.'
complete -c docker-checkpoint-create -l leave-running --description '	Leave the container running after checkpoint SEE ALSO.'

