# docker-container-start
# Autogenerated from man page /usr/share/man/man1/docker-container-start.1.gz
complete -c docker-container-start -s a -l attach --description '	Attach STDOUT/STDERR and forward signals.'
complete -c docker-container-start -l checkpoint --description '	Restore from this checkpoint.'
complete -c docker-container-start -l checkpoint-dir --description '	Use a custom checkpoint storage directory.'
complete -c docker-container-start -l detach-keys --description '	Override the key sequence for detaching a container.'
complete -c docker-container-start -s h -l help --description '	help for start.'
complete -c docker-container-start -s i -l interactive --description '	Attach container\'s STDIN SEE ALSO.'

