# docker-swarm-update
# Autogenerated from man page /usr/share/man/man1/docker-swarm-update.1.gz
complete -c docker-swarm-update -l autolock --description '	Change manager autolocking setting (true|false).'
complete -c docker-swarm-update -l cert-expiry --description '	Validity period for node certificates (ns|us|ms|s|m|h).'
complete -c docker-swarm-update -l dispatcher-heartbeat --description '	Dispatcher heartbeat period (ns|us|ms|s|m|h).'
complete -c docker-swarm-update -l external-ca --description '	Specifications of one or more certificate signing endpoints.'
complete -c docker-swarm-update -s h -l help --description '	help for update.'
complete -c docker-swarm-update -l max-snapshots --description '	Number of additional Raft snapshots to retain.'
complete -c docker-swarm-update -l snapshot-interval --description '	Number of log entries between Raft snapshots.'
complete -c docker-swarm-update -l task-history-limit --description '	Task history retention limit SEE ALSO.'

