# docker-trust-sign
# Autogenerated from man page /usr/share/man/man1/docker-trust-sign.1.gz
complete -c docker-trust-sign -s h -l help --description '	help for sign.'
complete -c docker-trust-sign -l local --description '	Sign a locally tagged image SEE ALSO.'

