# docker-node-update
# Autogenerated from man page /usr/share/man/man1/docker-node-update.1.gz
complete -c docker-node-update -l availability --description '	Availability of the node ("active"|"pause"|"drain").'
complete -c docker-node-update -s h -l help --description '	help for update.'
complete -c docker-node-update -l label-add --description '	Add or update a node label (key=value).'
complete -c docker-node-update -l label-rm --description '	Remove a node label if exists.'
complete -c docker-node-update -l role --description '	Role of the node ("worker"|"manager") SEE ALSO.'

