# docker-swarm-join-token
# Autogenerated from man page /usr/share/man/man1/docker-swarm-join-token.1.gz
complete -c docker-swarm-join-token -s h -l help --description '	help for join-token.'
complete -c docker-swarm-join-token -s q -l quiet --description '	Only display token.'
complete -c docker-swarm-join-token -l rotate --description '	Rotate join token SEE ALSO.'

