# docker-stats
# Autogenerated from man page /usr/share/man/man1/docker-stats.1.gz
complete -c docker-stats -s a -l all --description '	Show all containers (default shows just running).'
complete -c docker-stats -l format --description '	Pretty-print images using a Go template.'
complete -c docker-stats -s h -l help --description '	help for stats.'
complete -c docker-stats -l no-stream --description '	Disable streaming stats and only pull the first result.'
complete -c docker-stats -l no-trunc --description '	Do not truncate output SEE ALSO.'

