# docker-stack-services
# Autogenerated from man page /usr/share/man/man1/docker-stack-services.1.gz
complete -c docker-stack-services -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-stack-services -l format --description '	Pretty-print services using a Go template.'
complete -c docker-stack-services -s h -l help --description '	help for services.'
complete -c docker-stack-services -l namespace --description '	Kubernetes namespace to use.'
complete -c docker-stack-services -s q -l quiet --description '	Only display IDs OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c docker-stack-services -l kubeconfig --description '	Kubernetes config file.'
complete -c docker-stack-services -l orchestrator --description '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO.'

