# docker-container-ls
# Autogenerated from man page /usr/share/man/man1/docker-container-ls.1.gz
complete -c docker-container-ls -s a -l all --description '	Show all containers (default shows just running).'
complete -c docker-container-ls -s f -l filter --description '	Filter output based on conditions provided.'
complete -c docker-container-ls -l format --description '	Pretty-print containers using a Go template.'
complete -c docker-container-ls -s h -l help --description '	help for ls.'
complete -c docker-container-ls -s n -l last -s 1 --description '	Show n last created containers (includes all states).'
complete -c docker-container-ls -s l -l latest --description '	Show the latest created container (includes all states).'
complete -c docker-container-ls -l no-trunc --description '	Don\'t truncate output.'
complete -c docker-container-ls -s q -l quiet --description '	Only display container IDs.'
complete -c docker-container-ls -s s -l size --description '	Display total file sizes SEE ALSO.'

