# dot2gxl
# Autogenerated from man page /usr/share/man/man1/dot2gxl.1.gz
complete -c dot2gxl -s g --description 'The command name and input file extensions are ignored, the input is taken as…'
complete -c dot2gxl -s d --description 'The command name and input file extensions are ignored, the input is taken as…'
complete -c dot2gxl -s '?' --description 'Prints usage information and exits.'
complete -c dot2gxl -s o --description 'If specified, the output will be written into the file outfile.'

