# dpkg-deb
# Autogenerated from man page /usr/share/man/man1/dpkg-deb.1.gz
complete -c dpkg-deb -l showformat --description 'This option is used to specify the format of the output --show will produce.'
complete -c dpkg-deb -o zcompress-level --description 'Specify which compression level to use on the compressor backend, when buildi…'
complete -c dpkg-deb -o Scompress-strategy --description 'Specify which compression strategy to use on the compressor backend, when bui…'
complete -c dpkg-deb -o Zcompress-type --description 'Specify which compression type to use when building a package.'
complete -c dpkg-deb -l uniform-compression --description 'Specify that the same compression parameters should be used for all archive m…'
complete -c dpkg-deb -l root-owner-group --description 'Set the owner and group for each entry in the filesystem tree data to root wi…'
complete -c dpkg-deb -l deb-format --description 'Set the archive format version used when building (since dpkg 1. 17. 0).'
complete -c dpkg-deb -l nocheck --description 'Inhibits dpkg-deb --build\'s usual checks on the proposed contents of an archi…'
complete -c dpkg-deb -s v -l verbose --description 'Enables verbose output (since dpkg 1. 16. 1).'

