# dpkg-divert
# Autogenerated from man page /usr/share/man/man1/dpkg-divert.1.gz
complete -c dpkg-divert -l admindir --description 'Set the administrative directory to directory.'
complete -c dpkg-divert -l instdir --description 'Set the installation directory, which refers to the directory where packages …'
complete -c dpkg-divert -l root --description 'Set the root directory to directory, which sets the installation directory to…'
complete -c dpkg-divert -l divert --description 'divert-to is the location where the versions of file, as provided by other pa…'
complete -c dpkg-divert -l local --description 'Specifies that all packages\' versions of this file are diverted.'
complete -c dpkg-divert -l package --description 'package is the name of a package whose copy of file will not be diverted.  i.'
complete -c dpkg-divert -l quiet --description 'Quiet mode, i. e.  no verbose output.'
complete -c dpkg-divert -l rename --description 'Actually move the file aside (or back).'
complete -c dpkg-divert -l no-rename --description 'Specifies that the file should not be renamed while adding or removing the di…'
complete -c dpkg-divert -l test --description 'Test mode, i. e.  don\'t actually perform any changes, just demonstrate.'
complete -c dpkg-divert -s '?' -l help --description 'Show the usage message and exit.'

