# dpkg-architecture
# Autogenerated from man page /usr/share/man/man1/dpkg-architecture.1.gz
complete -c dpkg-architecture -s a -l host-arch --description 'Set the host Debian architecture.'
complete -c dpkg-architecture -s t -l host-type --description 'Set the host \\s-1GNU\\s0 system type.'
complete -c dpkg-architecture -s A -l target-arch --description 'Set the target Debian architecture (since dpkg 1. 17. 14).'
complete -c dpkg-architecture -s T -l target-type --description 'Set the target \\s-1GNU\\s0 system type (since dpkg 1. 17. 14).'
complete -c dpkg-architecture -s W -l match-wildcard --description 'Restrict the architectures listed by --list-known to ones matching the specif…'
complete -c dpkg-architecture -s B -l match-bits --description 'Restrict the architectures listed by --list-known to ones with the specified …'
complete -c dpkg-architecture -s E -l match-endian --description 'Restrict the architectures listed by --list-known to ones with the specified …'
complete -c dpkg-architecture -l print-format --description 'Sets the output format for --print-set and --print-unset (since dpkg 1. 20.'

