# dpkg-shlibdeps
# Autogenerated from man page /usr/share/man/man1/dpkg-shlibdeps.1.gz
complete -c dpkg-shlibdeps -o eexecutable --description 'Include dependencies appropriate for the shared libraries required by executa…'
complete -c dpkg-shlibdeps -o ldirectory --description 'Prepend directory to the list of directories to search for private shared lib…'
complete -c dpkg-shlibdeps -o ddependency-field --description 'Add dependencies to be added to the control file dependency field dependency-…'
complete -c dpkg-shlibdeps -o pvarname-prefix --description 'Start substitution variables with varname-prefix: instead of shlibs:.'
complete -c dpkg-shlibdeps -s O --description 'Print substitution variable settings to standard output (or filename if speci…'
complete -c dpkg-shlibdeps -o ttype --description 'Prefer shared library dependency information tagged for the given package typ…'
complete -c dpkg-shlibdeps -o Llocal-shlibs-file --description 'Read overriding shared library dependency information from local-shlibs-file …'
complete -c dpkg-shlibdeps -o Tsubstvars-file --description 'Write substitution variables in substvars-file; the default is debian/substva…'
complete -c dpkg-shlibdeps -s v --description 'Enable verbose mode (since dpkg 1. 14. 8).'
complete -c dpkg-shlibdeps -o xpackage --description 'Exclude the package from the generated dependencies (since dpkg 1. 14. 8).'
complete -c dpkg-shlibdeps -o Spackage-build-dir --description 'Look into package-build-dir first when trying to find a library (since dpkg 1.'
complete -c dpkg-shlibdeps -o Ipackage-build-dir --description 'Ignore package-build-dir when looking for shlibs, symbols, and shared library…'
complete -c dpkg-shlibdeps -l ignore-missing-info --description 'Do not fail if dependency information can\'t be found for a shared library (si…'
complete -c dpkg-shlibdeps -l warnings --description 'value is a bit field defining the set of warnings that can be emitted by dpkg…'
complete -c dpkg-shlibdeps -l admindir --description 'Change the location of the dpkg database (since dpkg 1. 14. 0).'
complete -c dpkg-shlibdeps -s '?' -l help --description 'Show the usage message and exit.'

