# dpkg-gensymbols
# Autogenerated from man page /usr/share/man/man1/dpkg-gensymbols.1.gz
complete -c dpkg-gensymbols -o Ppackage-build-dir --description 'Scan package-build-dir instead of debian/tmp.'
complete -c dpkg-gensymbols -o ppackage --description 'Define the package name.'
complete -c dpkg-gensymbols -o vversion --description 'Define the package version.'
complete -c dpkg-gensymbols -o elibrary-file --description 'Only analyze libraries explicitly listed instead of finding all public librar…'
complete -c dpkg-gensymbols -o ldirectory --description 'Prepend directory to the list of directories to search for private shared lib…'
complete -c dpkg-gensymbols -o Ifilename --description 'Use filename as reference file to generate the symbols file that is integrate…'
complete -c dpkg-gensymbols -s O --description 'Print the generated symbols file to standard output or to filename if specifi…'
complete -c dpkg-gensymbols -s t --description 'Write the symbol file in template mode rather than the format compatible with…'
complete -c dpkg-gensymbols -s c --description 'Define the checks to do when comparing the generated symbols file with the te…'
complete -c dpkg-gensymbols -s q --description 'Keep quiet and never generate a diff between generated symbols file and the t…'
complete -c dpkg-gensymbols -o aarch --description 'Assume arch as host architecture when processing symbol files.'
complete -c dpkg-gensymbols -s d --description 'Enable debug mode.'
complete -c dpkg-gensymbols -s V --description 'Enable verbose mode.'
complete -c dpkg-gensymbols -s '?' -l help --description 'Show the usage message and exit.'

