# dpkg-reconfigure
# Autogenerated from man page /usr/share/man/man8/dpkg-reconfigure.8.gz
complete -c dpkg-reconfigure -o ftype -l frontend --description 'Select the frontend to use.'
complete -c dpkg-reconfigure -o pvalue -l priority --description 'Specify the minimum priority of question that will be displayed.'
complete -c dpkg-reconfigure -l default-priority --description 'Use whatever the default priority of question is, instead of forcing the prio…'
complete -c dpkg-reconfigure -s u -l unseen-only --description 'By default, all questions are shown, even if they have already been answered.'
complete -c dpkg-reconfigure -l force --description 'Force dpkg-reconfigure to reconfigure a package even if the package is in an …'
complete -c dpkg-reconfigure -l no-reload --description 'Prevent dpkg-reconfigure from reloading templates.'

