# dpkg-name
# Autogenerated from man page /usr/share/man/man1/dpkg-name.1.gz
complete -c dpkg-name -s a -l no-architecture --description 'The destination filename will not have the architecture information.'
complete -c dpkg-name -s k -l symlink --description 'Create a symlink, instead of moving.'
complete -c dpkg-name -s o -l overwrite --description 'Existing files will be overwritten if they have the same name as the destinat…'
complete -c dpkg-name -s s -l subdir --description 'Files will be moved into a subdirectory.'
complete -c dpkg-name -s c -l create-dir --description 'This option can used together with the -s option.'
complete -c dpkg-name -s '?' -l help --description 'Show the usage message and exit.'

