# dtrx
# Autogenerated from man page /usr/share/man/man1/dtrx.1.gz
complete -c dtrx -s r -l recursive --description 'With this option, dtrx will search inside the archives you specify to see if …'
complete -c dtrx -l one -l one-entry --description 'Normally, if an archive only contains one file or directory with a name that …'
complete -c dtrx -s o -l overwrite --description 'Normally, dtrx will avoid extracting into a directory that already exists, an…'
complete -c dtrx -s f -l flat --description 'Extract all archive contents into the current directory, instead of their own…'
complete -c dtrx -s n -l noninteractive --description 'dtrx will normally ask the user how to handle certain corner cases, such as h…'
complete -c dtrx -s l -s t -l list -l table --description 'Don\\(aqt extract the archives; just list their contents on standard output.'
complete -c dtrx -s m -l metadata --description 'Extract the metadata from . deb and .'
complete -c dtrx -s q -l quiet --description 'Suppress warning messages.   List this option twice to make dtrx silent.'
complete -c dtrx -s v -l verbose --description 'Show the files that are being extracted.'
complete -c dtrx -l help --description 'Display basic help.'
complete -c dtrx -l version --description 'Display dtrx\\(aqs version, copyright, and license information.'
complete -c dtrx -s c --description 'downloads.'

