# dwz
# Autogenerated from man page /usr/share/man/man1/dwz.1.gz
complete -c dwz -o mFILE -l multifile --description 'Multifile mode.'
complete -c dwz -o h--hardlink --description 'Look for executables or shared libraries hardlinked together, instead of rewr…'
complete -c dwz -s M -l multifile-name --description 'Specify the name of the common file that should be put into the .'
complete -c dwz -s r -l relative --description 'Specify that the name of the common file to be put into the .'
complete -c dwz -s q -l quiet --description 'Silence up some of the most common messages.'
complete -c dwz -s o -l output --description 'This option instructs dwz not to overwrite the specified file, but instead st…'
complete -c dwz -s l -l low-mem-die-limit --description 'Handle executables or shared libraries containing more than COUNT debugging i…'
complete -c dwz -s L -l max-die-limit --description 'Don\'t attempt to optimize executables or shared libraries containing more tha…'
complete -c dwz -s 5 -l dwarf-5 --description 'Emit standard DWARF 5 Supplementary Object Files with .'
complete -c dwz -l odr -l no-odr --description 'Experimental.'
complete -c dwz -l odr-mode --description 'Set the One-Definition-Rule optimization aggressiveness: basic or link.'
complete -c dwz -l import-optimize -l no-import-optimize --description 'Enable/disable optimization that reduces the number of DW_TAG_imported_unit D…'
complete -c dwz -s '?' -l help --description 'Print short help and exit.'
complete -c dwz -s m --description 'given object (executable or shared library) individually, with the.'
complete -c dwz -s h -l hardlink --description 'Look for executables or shared libraries hardlinked together, instead of rewr…'
complete -c dwz -s v -l version --description 'Print version number and short licensing notice and exit.'

