# e2scrub
# Autogenerated from man page /usr/share/man/man8/e2scrub.8.gz
complete -c e2scrub -s n --description 'Print what commands  e2scrub would execute to check the file system.'
complete -c e2scrub -s r --description 'Remove the e2scrub snapshot and exit without checking anything.'
complete -c e2scrub -s t --description 'Run  fstrim(1) on the mounted filesystem if no errors are found.'
complete -c e2scrub -s V --description 'Print version information and exit.'

