# edit
# Autogenerated from man page /usr/share/man/man1/edit.1.gz
complete -c edit -l action --description 'Performs the specified action on the files.'
complete -c edit -l debug --description 'Turns on extra information to find out what is happening.'
complete -c edit -l nopager --description 'Ignores any "copiousoutput" directive and sends output to STDOUT.'
complete -c edit -l norun --description 'Displays the found command without actually executing it.'

