# elixirc
# Autogenerated from man page /usr/share/man/man1/elixirc.1.gz
complete -c elixirc -s o --description 'Places the output file in the specified directory.'
complete -c elixirc -l erl --description 'Serves the same purpose as ELIXIR_ERL_OPTIONS see the Sy ENVIRONMENT No secti…'
complete -c elixirc -l ignore-module-conflict --description 'Disables warnings when a module was previously defined.'
complete -c elixirc -l no-debug-info --description 'Disables producing debugging information.'
complete -c elixirc -l no-docs --description 'Disables generating documentation.'
complete -c elixirc -l warnings-as-errors --description 'Makes all warnings into errors.'
complete -c elixirc -l verbose --description 'Activates verbose mode.'

