# enchant-2
# Autogenerated from man page /usr/share/man/man1/enchant-2.1.gz
complete -c enchant-2 -s d --description 'use the given dictionary.'
complete -c enchant-2 -s a --description 'list suggestions in ispell pipe mode format.'
complete -c enchant-2 -s l --description 'list only the misspellings.'
complete -c enchant-2 -s L --description 'display line numbers.'
complete -c enchant-2 -s h --description 'display help and exit.'
complete -c enchant-2 -s v --description 'display version information and exit ENCHANT ORDERING FILE Enchant uses globa…'

