# epmd
# Autogenerated from man page /usr/share/man/man1/epmd.1.gz
complete -c epmd -o address --description 'Lets this instance of epmd listen only on the comma-separated list of IP addr…'
complete -c epmd -o port --description 'Lets this instance of epmd listen to another TCP port than default 4369.'
complete -c epmd -s d -o debug --description 'Enables debug output.'
complete -c epmd -o daemon --description 'Starts epmd detached from the controlling terminal.'
complete -c epmd -o relaxed_command_check --description 'Starts the epmd program with relaxed command checking (mostly for backward co…'
complete -c epmd -o packet_timeout --description 'Sets the number of seconds a connection can be inactive before epmd times out…'
complete -c epmd -o delay_accept --description 'To simulate a busy server, you can insert a delay between when epmd gets noti…'
complete -c epmd -o delay_write --description 'Also a simulation of a busy server.  Inserts a delay before a reply is sent.'
complete -c epmd -o names --description 'Lists names registered with the currently running epmd.'
complete -c epmd -o kill --description 'Kills the currently running epmd.'
complete -c epmd -o stop --description 'Forcibly unregisters a live node from the epmd database.'

