# eqn2graph
# Autogenerated from man page /usr/share/man/man1/eqn2graph.1.gz
complete -c eqn2graph -o format --description 'Write the image in R output-format , which must be understood by R \\%convert …'
complete -c eqn2graph -l help --description 'Display a usage message and exit.'
complete -c eqn2graph -o trim --description 'option to the smallest possible bounding box that contains all the black pixe…'
complete -c eqn2graph -s v --description '.'
complete -c eqn2graph -l version --description 'Display version information and exit.  ENVIRONMENT %GROFF_TMPDIR.'

