# escript
# Autogenerated from man page /usr/share/man/man1/escript.1.gz
complete -c escript -o include_lib --description 'to include the record definitions for the records used by function file:read_…'
complete -c escript -s c --description 'Compiles the escript regardless of the value of the mode attribute.'
complete -c escript -s d --description 'Debugs the escript.'
complete -c escript -s i --description 'Interprets the escript regardless of the value of the mode attribute.'
complete -c escript -s s --description 'Performs a syntactic and semantic check of the script file.'
complete -c escript -s n --description 'Compiles the escript using flag +native.'

