# faillock
# Autogenerated from man page /usr/share/man/man8/faillock.8.gz
complete -c faillock -l dir --description 'The directory where the user files with the failure records are kept.'
complete -c faillock -l user --description 'The user whose failure records should be displayed or cleared.'
complete -c faillock -l reset --description 'Instead of displaying the user\\*(Aqs failure records, clear them.'

