# fakeroot-tcp
# Autogenerated from man page /usr/share/man/man1/fakeroot-tcp.1.gz
complete -c fakeroot-tcp -s l -l lib --description 'Specify an alternative wrapper library.'
complete -c fakeroot-tcp -l faked --description 'Specify an alternative binary to use as faked.'
complete -c fakeroot-tcp -s s --description 'Save the fakeroot environment to save-file on exit.'
complete -c fakeroot-tcp -s i --description 'Load a fakeroot environment previously saved using -s from load-file.'
complete -c fakeroot-tcp -s u -l unknown-is-real --description 'Use the real ownership of files previously unknown to fakeroot instead of pre…'
complete -c fakeroot-tcp -s b --description 'Specify fd base (TCP mode only).'
complete -c fakeroot-tcp -s h --description 'Display help.'
complete -c fakeroot-tcp -s v --description 'Display version.'
complete -c fakeroot-tcp -o rw-r--r-- --description '.'

