# fanctl
# Autogenerated from man page /usr/share/man/man8/fanctl.8.gz
complete -c fanctl -s u -l underlay --description 'Specify the underlay network address and mask. \\".'
complete -c fanctl -s o -l overlay --description 'Specify the overlay network address and mask. \\".'
complete -c fanctl -l type --description 'Sets the encapsulation type for this Fan bridge.'
complete -c fanctl -l mode --description 'Sets the bridge mode.   May be compact (default) or sliced only.'
complete -c fanctl -l dhcp --description 'Turns on automatic address allocation for the Fan bridge.'
complete -c fanctl -l host-reserve --description 'By default the .'
complete -c fanctl -l bridge --description 'By default the bridge name is based on the overlay and underlay addresses spe…'
complete -c fanctl -l enable --description 'This option marks the Fan bridge to be automatically configured when the unde…'

