# fatlabel
# Autogenerated from man page /usr/share/man/man8/fatlabel.8.gz
complete -c fatlabel -s i -l volume-id --description 'Switch to volume ID mode.'
complete -c fatlabel -s r -l reset --description 'Remove label in label mode or generate new ID in volume ID mode.'
complete -c fatlabel -s c -l codepage --description 'Use DOS codepage PAGE to encode/decode label.'
complete -c fatlabel -s h -l help --description 'Display a help message and terminate.'
complete -c fatlabel -s V -l version --description 'Show version number and terminate.'

