# fcgistarter
# Autogenerated from man page /usr/share/man/man8/fcgistarter.8.gz
complete -c fcgistarter -s c --description 'Absolute path of the FastCGI program.'
complete -c fcgistarter -s p --description 'Port which the program will listen on.'
complete -c fcgistarter -s i --description 'Interface which the program will listen on.'

