# fig2mpdf
# Autogenerated from man page /usr/share/man/man1/fig2mpdf.1.gz
complete -c fig2mpdf -s e --description 'produce an eps output file.'
complete -c fig2mpdf -s p --description 'explicitly set the ranges of depths for splitting the input figure in multila…'
complete -c fig2mpdf -s i --description 'include the the bottommost range (that is, the one with the highest depth) in…'
complete -c fig2mpdf -s I --description 'turn on pyramid mode.'
complete -c fig2mpdf -s g --description 'set the allowed gapwidth between two used depths to decide if these depths sh…'
complete -c fig2mpdf -s s --description 'replace the default style for selecting a font family in LaTeX mode.'
complete -c fig2mpdf -s H --description 'replace the default header sequence for creating temporary LaTeX documents in…'
complete -c fig2mpdf -s G --description 'in multilayer mode change the default output file pattern to the PDF format w…'
complete -c fig2mpdf -s v --description 'be verbose and print out all executed commands.'
complete -c fig2mpdf -s V --description 'print out the version of fig2mpdf.'

