# filan
# Autogenerated from man page /usr/share/man/man1/filan.1.gz
complete -c filan -s '?' --description 'Print a help text to stdout describing command line options and available add…'
complete -c filan -o '??' --description 'Like -h, plus a list of the short names of all available address options.'
complete -c filan -o '???' --description 'Like -hh, plus a list of all available address option names.'
complete -c filan -s d --description 'Prints fatal, error, warning, and notice messages.'

