# file2brl
# Autogenerated from man page /usr/share/man/man1/file2brl.1.gz
complete -c file2brl -s h -l help --description 'display this help and exit.'
complete -c file2brl -s v -l version --description 'display version information and exit.'
complete -c file2brl -s f -l config-file --description 'name a configuration file that specifies how to do the translation.'
complete -c file2brl -s b -l backward --description 'backward translation.'
complete -c file2brl -s r -l reformat --description 'reformat a braille file.'
complete -c file2brl -s T -l text --description 'Treat as text even if xml.'
complete -c file2brl -s t -l html --description 'html document, not xhtml.'
complete -c file2brl -s p -l poorly-formatted --description 'translate a poorly formatted file.'
complete -c file2brl -s P -l paragraph-line --description 'treat each block of text ending in a newline as a paragraph.'
complete -c file2brl -s C -l config-setting --description 'specify particular configuration settings They override any settings that are…'
complete -c file2brl -s w -l writeable-path --description 'path for temp files and log file.'
complete -c file2brl -s l -l log-file --description 'write errors to file2brl. log instead of stderr AUTHOR Written by John J.'

