# find-all-symbols-12
# Autogenerated from man page /usr/share/man/man1/find-all-symbols-12.1.gz
complete -c find-all-symbols-12 -l merge-dir --description 'The directory for merging symbols.'
complete -c find-all-symbols-12 -l help -l help-hidden --description '.'
complete -c find-all-symbols-12 -l help-list -l help-list-hidden --description '.'
complete -c find-all-symbols-12 -l version --description '.'
complete -c find-all-symbols-12 -l extra-arg --description '.'
complete -c find-all-symbols-12 -l extra-arg-before --description '.'
complete -c find-all-symbols-12 -l output-dir --description 'The output directory for saving the results.'
complete -c find-all-symbols-12 -s p --description '.'

