# fish
# Autogenerated from man page /usr/share/man/man1/fish.1.gz
complete -c fish -s c -l command --description 'o 2.'
complete -c fish -s C -l init-command --description 'o 2.'
complete -c fish -s d -l debug -s d --description 'o 2.'
complete -c fish -s o -l debug-output --description 'o 2.'
complete -c fish -s i -l interactive --description 'o 2.'
complete -c fish -s l -l login --description 'o 2.'
complete -c fish -s n -l no-execute --description 'o 2.'
complete -c fish -s p -l profile --description 'o 2.'
complete -c fish -s P -l private --description 'o 2.'
complete -c fish -l print-rusage-self --description 'o 2.'
complete -c fish -l print-debug-categories --description 'o 2.'
complete -c fish -s v -l version --description 'o 2.'
complete -c fish -s D -l debug-stack-frames --description 'o 2.'
complete -c fish -s f -l features --description 'The fish exit status is generally the exit status of the last foreground comm…'

