# fish_key_reader
# Autogenerated from man page /usr/share/man/man1/fish_key_reader.1.gz
complete -c fish_key_reader -s c -l continuous --description 'o 2.'
complete -c fish_key_reader -s d -l debug -s d --description 'o 2.'
complete -c fish_key_reader -s D -l debug-stack-frames --description 'o 2.'
complete -c fish_key_reader -s h -l help --description 'o 2.'
complete -c fish_key_reader -s v -l version --description '.'

