# fish_indent
# Autogenerated from man page /usr/share/man/man1/fish_indent.1.gz
complete -c fish_indent -s w -l write --description 'o 2.'
complete -c fish_indent -s i -l no-indent --description 'o 2.'
complete -c fish_indent -s v -l version --description 'o 2.'
complete -c fish_indent -l ansi --description 'o 2.'
complete -c fish_indent -l html --description 'o 2.'
complete -c fish_indent -s d -l debug -s d --description 'o 2.'
complete -c fish_indent -s D -l debug-stack-frames --description 'o 2.'
complete -c fish_indent -l dump-parse-tree --description '.'

