# fitstopnm
# Autogenerated from man page /usr/share/man/man1/fitstopnm.1.gz
complete -c fitstopnm -o image --description 'flag is specified.'
complete -c fitstopnm -o min --description 'and .'
complete -c fitstopnm -o max --description 'can be used to override the min and max values as read from the FITS header o…'
complete -c fitstopnm -o scanmax --description 'can be used to force the program to scan the data even when DATAMIN and DATAM…'
complete -c fitstopnm -o printmax --description 'is specified, the program will just print the min and max values and quit.'
complete -c fitstopnm -o noraw --description 'can be used to force  the program to produce an ASCII portable anymap.'

