# ftp
# Autogenerated from man page /usr/share/man/man1/ftp.1.gz
complete -c ftp -s 4 --description 'Use only IPv4 to contact any host.'
complete -c ftp -s 6 --description 'Use IPv6 only.'
complete -c ftp -s p --description 'Use passive mode for data transfers.'
complete -c ftp -s i --description 'Turns off interactive prompting during multiple file transfers.'
complete -c ftp -s n --description 'Restrains ftp ftp from attempting \\*(Lqauto-login\\*(Rq upon initial connectio…'
complete -c ftp -s e --description 'Disables command editing and history support, if it was compiled into the ftp…'
complete -c ftp -s g --description 'Disables file name globbing.'
complete -c ftp -s v --description 'Verbose option forces ftp ftp to show all responses from the remote server, a…'
complete -c ftp -s d --description 'Enables debugging.'

