# fwupdate
# Autogenerated from man page /usr/share/man/man1/fwupdate.1.gz
complete -c fwupdate -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c fwupdate -s v -l verbose --description 'Show extra debugging information.'
complete -c fwupdate -l version --description 'Display version.'
complete -c fwupdate -s L -l log --description 'Show the debug log from the last attempted update.'
complete -c fwupdate -s l -l list --description 'List supported firmware updates.'
complete -c fwupdate -s s -l supported --description 'Query for firmware update support.'
complete -c fwupdate -s i -l info --description 'Show the information of firmware update status.'
complete -c fwupdate -s e -l enable --description 'Enable firmware update support on supported systems.'
complete -c fwupdate -s p -l esp-path --description 'Override the default ESP path.'
complete -c fwupdate -s d -l set-debug --description 'Set the debugging flag during update.'
complete -c fwupdate -s D -l unset-debug --description 'Unset the debugging flag during update.'
complete -c fwupdate -s a -l apply --description 'Apply firmware updates.'
complete -c fwupdate -s f -l flags --description 'Use quirk flags when installing firmware.'

