# fwupdagent
# Autogenerated from man page /usr/share/man/man1/fwupdagent.1.gz
complete -c fwupdagent -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c fwupdagent -s v -l verbose --description 'Show extra debugging information.'
complete -c fwupdagent -l force --description 'Override warnings and force the action.'

