# fwupdtpmevlog
# Autogenerated from man page /usr/share/man/man1/fwupdtpmevlog.1.gz
complete -c fwupdtpmevlog -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c fwupdtpmevlog -s v -l verbose --description 'Show extra debugging information.'
complete -c fwupdtpmevlog -s p -l pcr --description 'Only show single PCR value.'

