# g3topbm
# Autogenerated from man page /usr/share/man/man1/g3topbm.1.gz
complete -c g3topbm -o kludge --description 'Tells  g3topbm to ignore the first few lines of the file; sometimes fax files…'
complete -c g3topbm -o reversebits --description 'Tells  g3topbm to interpret bits least-significant first, instead of the defa…'
complete -c g3topbm -o stretch --description 'Tells g3topbm to stretch the image vertically by duplicating each row.'

