# gcore
# Autogenerated from man page /usr/share/man/man1/gcore.1.gz
complete -c gcore -s a --description '(Linux only) ignore /proc/PID/coredump_filter and also dump memory mappings m…'
complete -c gcore -s o --description 'write core file to filename if one PID, or filename.'

