# geqn
# Autogenerated from man page /usr/share/man/man1/geqn.1.gz
complete -c geqn -s d --description 'Specify delimiters  x and\\~\\c  y for the left and right end, respectively, of…'
complete -c geqn -s C --description 'Recognize  . EQ and  .'
complete -c geqn -s N --description 'Don\'t allow newlines within delimiters.'
complete -c geqn -s v --description 'Print the version number.'
complete -c geqn -s r --description 'Only one size reduction.'
complete -c geqn -s m --description 'The minimum point-size is\\~\\c R n .'
complete -c geqn -s T --description 'The output is for device R name .'
complete -c geqn -s M --description 'Search  dir for  eqnrc before the default directories.'
complete -c geqn -s R --description 'Don\'t load R eqnrc .'
complete -c geqn -s f --description 'This is equivalent to a  gfont F command.'
complete -c geqn -s s --description 'This is equivalent to a  gsize n command.  This option is deprecated.'
complete -c geqn -s e --description 'option of groff .'
complete -c geqn -s p --description 'This says that subscripts and superscripts should be n  points smaller than t…'

