# getcap
# Autogenerated from man page /usr/share/man/man8/getcap.8.gz
complete -c getcap -s h --description 'prints quick usage.'
complete -c getcap -s n --description 'prints any non-zero user namespace root user ID value found to be associated …'
complete -c getcap -s r --description 'enables recursive search.'
complete -c getcap -s v --description 'display all searched entries, even if the have no file-capabilities.'

