# getpcaps
# Autogenerated from man page /usr/share/man/man8/getpcaps.8.gz
complete -c getpcaps -l help -l usage --description 'Displays usage information and exits.'
complete -c getpcaps -l ugly -l legacy --description 'Displays output in a somewhat ugly legacy format.'
complete -c getpcaps -l verbose --description 'Displays usage in a legacy-like format but not quite so ugly in modern defaul…'

