# giftopnm
# Autogenerated from man page /usr/share/man/man1/giftopnm.1.gz
complete -c giftopnm -l alphaout --description 'giftopnm  creates a PGM (portable graymap) file containing the alpha channel …'
complete -c giftopnm -o verbose --description 'Produce verbose output about the GIF file input.'
complete -c giftopnm -o comments --description 'Only output GIF89 comment fields.'
complete -c giftopnm -o image --description 'Output the specified gif image from the input GIF archive (where N is \'1\', \'2…'

