# git-bugreport
# Autogenerated from man page /usr/share/man/man1/git-bugreport.1.gz
complete -c git-bugreport -s o -l output-directory --description 'Place the resulting bug report file in <path> instead of the root of the Git …'
complete -c git-bugreport -s s -l suffix --description 'Specify an alternate suffix for the bugreport name, to create a file named gi…'

