# gnome-keyring-daemon
# Autogenerated from man page /usr/share/man/man1/gnome-keyring-daemon.1.gz
complete -c gnome-keyring-daemon -s c -l components --description 'Ask the daemon to only initialize certain components.'
complete -c gnome-keyring-daemon -s C -l control-directory --description 'Use this directory for creating communication sockets.'
complete -c gnome-keyring-daemon -s d -l daemonize --description 'Run as a real daemon, disconnected from the terminal.'
complete -c gnome-keyring-daemon -s f -l foreground --description 'Run in the foreground, and do not fork or become a daemon.'
complete -c gnome-keyring-daemon -s l -l login --description 'This argument tells the daemon it is being run by PAM.'
complete -c gnome-keyring-daemon -s r -l replace --description 'Try to replace a running keyring daemon, and assume its environment variables.'
complete -c gnome-keyring-daemon -s s -l start --description 'Connect to an already running daemon and initialize it.'
complete -c gnome-keyring-daemon -l unlock --description 'Read a password from stdin, and use it to unlock the login keyring or create …'
complete -c gnome-keyring-daemon -s V -l version --description 'Print out the gnome-keyring version and then exit.'
complete -c gnome-keyring-daemon -s h -l help --description 'Show help options and exit.'

