# go-build
# Autogenerated from man page /usr/share/man/man1/go-build.1.gz
complete -c go-build -s a --description 'force rebuilding of packages that are already up-to-date.'
complete -c go-build -s n --description 'print the commands but do not run them.'
complete -c go-build -s p --description 'the number of builds that can be run in parallel.'
complete -c go-build -s v --description 'print the names of packages as they are compiled.'
complete -c go-build -o work --description 'print the name of the temporary work directory and do not delete it when exit…'
complete -c go-build -s x --description 'print the commands.'
complete -c go-build -o compiler --description 'name of compiler to use, as in runtime. Compiler (gccgo or gc).'
complete -c go-build -o gccgoflags --description 'arguments to pass on each gccgo compiler/linker invocation.'
complete -c go-build -o gcflags --description 'arguments to pass on each 5g, 6g, or 8g compiler invocation.'
complete -c go-build -o ldflags --description 'arguments to pass on each 5l, 6l, or 8l linker invocation.'
complete -c go-build -o tags --description 'a list of build tags to consider satisfied during the build.'

