# go-clean
# Autogenerated from man page /usr/share/man/man1/go-clean.1.gz
complete -c go-clean -s i --description 'The -i flag causes clean to remove the corresponding installed archive or bin…'
complete -c go-clean -s n --description 'The -n flag causes clean to print the remove commands it would execute, but n…'
complete -c go-clean -s r --description 'The -r flag causes clean to be applied recursively to all the dependencies of…'
complete -c go-clean -s x --description 'The -x flag causes clean to print remove commands as it executes them.'

