# go-get
# Autogenerated from man page /usr/share/man/man1/go-get.1.gz
complete -c go-get -s a -s n -s v -s x -s p --description 'The -a, -n, -v, -x, and -p flags have the same meaning as in \'go build\' and \'…'
complete -c go-get -s d --description 'The -d flag instructs get to stop after downloading the packages; that is, it…'
complete -c go-get -o fix --description 'The -fix flag instructs get to run the fix tool on the downloaded packages be…'
complete -c go-get -s u --description 'The -u flag instructs get to use the network to update the named packages and…'

