# go-list
# Autogenerated from man page /usr/share/man/man1/go-list.1.gz
complete -c go-list -s f --description 'The -f flag specifies an alternate format for the list, using the syntax of p…'
complete -c go-list -o json --description 'The -json flag causes the package data to be printed in JSON format instead o…'
complete -c go-list -s e --description 'The -e flag changes the handling of erroneous packages, those that cannot be …'

