# go-mtpfs
# Autogenerated from man page /usr/share/man/man1/go-mtpfs.1.gz
complete -c go-mtpfs -o allow-other --description 'Allow other users to access mounted fuse.  Default: false.'
complete -c go-mtpfs -o android --description 'Use Android extensions if available.  Default: true.'
complete -c go-mtpfs -o debug --description 'Comma-separated list of debugging options: usb, data, mtp, fuse.'
complete -c go-mtpfs -o dev --description 'Regular expression to filter device IDs, which are composed of manufacturer/p…'
complete -c go-mtpfs -o storage --description 'Regular expression to filter storage areas.'
complete -c go-mtpfs -o usb-timeout --description 'Timeout in milliseconds.  Default: 5000.'
complete -c go-mtpfs -s h -l help --description 'Show summary of options.'
complete -c go-mtpfs -o vfat --description 'Assume removable RAM media uses VFAT, and rewrite names.  Default: true.'

