# go-vet
# Autogenerated from man page /usr/share/man/man1/go-vet.1.gz
complete -c go-vet -s n --description 'The -n flag causes tool to print the command that would be executed but not e…'
complete -c go-vet -s x --description 'The -x flag causes clean to print remove commands as it executes them.'

