# gofmt
# Autogenerated from man page /usr/share/man/man1/gofmt.1.gz
complete -c gofmt -s d --description 'Do not print reformatted sources to standard output.'
complete -c gofmt -s e --description 'Print all (including spurious) errors.'
complete -c gofmt -s l --description 'Do not print reformatted sources to standard output.'
complete -c gofmt -s r --description 'Apply the rewrite rule to the source before reformatting.'
complete -c gofmt -s s --description 'Try to simplify code (after applying the rewrite rule, if any).'
complete -c gofmt -s w --description 'Do not print reformatted sources to standard output.'
complete -c gofmt -o comments --description 'Print comments; if false, all comments are elided from the output.'
complete -c gofmt -o tabs --description 'Indent with tabs; if false, spaces are used instead.'
complete -c gofmt -o tabwidth --description 'Tab width in spaces.'

