# gpg-wks-server
# Autogenerated from man page /usr/share/man/man1/gpg-wks-server.1.gz
complete -c gpg-wks-server -s C --description 'TQ   --directory dir Use dir as top level directory for domains.'
complete -c gpg-wks-server -l from --description 'Use mailaddr as the default sender address.'
complete -c gpg-wks-server -l header --description 'Add the mail header "name: value" to all outgoing mails.'
complete -c gpg-wks-server -l send --description 'Directly send created mails using the sendmail command.'
complete -c gpg-wks-server -s o --description 'TQ   --output file Write the created mail also to file.'
complete -c gpg-wks-server -l with-dir --description 'When used with the command --list-domains print for each installed domain the…'
complete -c gpg-wks-server -l with-file --description 'When used with the command --check-key print for each user-id, the address, \'…'
complete -c gpg-wks-server -l verbose --description 'Enable extra informational output.'
complete -c gpg-wks-server -l quiet --description 'Disable almost all informational output.'
complete -c gpg-wks-server -l version --description 'Print version of the program and exit.'
complete -c gpg-wks-server -s v --description 'the process returns failure; to suppress the diagnostic, use option.'
complete -c gpg-wks-server -s q --description 'with-file.'
complete -c gpg-wks-server -l directory --description 'Use dir as top level directory for domains.'
complete -c gpg-wks-server -l output --description 'Write the created mail also to file.  Note that the value.'
complete -c gpg-wks-server -l help --description 'Display a brief help page and exit.  EXAMPLES.'

