# gpg-check-pattern
# Autogenerated from man page /usr/share/man/man1/gpg-check-pattern.1.gz
complete -c gpg-check-pattern -s v -l verbose --description 'Produce verbose output.'
complete -c gpg-check-pattern -l check --description 'run only a syntax check on the patternfile.'
complete -c gpg-check-pattern -s 0 -l null --description 'input is expected to be null delimited.'

