# gpgcompose
# Autogenerated from man page /usr/share/man/man1/gpgcompose.1.gz
complete -c gpgcompose -l help --description '.'
complete -c gpgcompose -l signature --description 'will need to speak to an already-running gpg-agent .'
complete -c gpgcompose -l public-key --description 'It will do so in ~/. gnupg/keyring. kbx, or in $GNUPGHOME/keyring.'

