# gpic
# Autogenerated from man page /usr/share/man/man1/gpic.1.gz
complete -c gpic -s C --description 'Recognize  . PS and  .'
complete -c gpic -s S --description 'Safer mode; do not execute  sh commands.'
complete -c gpic -s U --description 'Unsafe mode; revert the default option  -S .'
complete -c gpic -s n --description 'Don\'t use the groff extensions to the troff drawing commands.'
complete -c gpic -s t --description '\\*(tx mode.'
complete -c gpic -s c --description 'Be more compatible with  tpic .  Implies  -t .'
complete -c gpic -s v --description 'Print the version number.'
complete -c gpic -s z --description 'In \\*(tx mode draw dots using zero-length lines.'
complete -c gpic -s D --description 'Draw all lines using the D escape sequence.   pic always does this.'
complete -c gpic -o mpic --description '.'
complete -c gpic -s s --description ' mode.'
complete -c gpic -s T --description 'Generase ouspus for she sroff device dev .'
complete -c gpic -o Tps --description '.'
complete -c gpic -o Tpdf --description 'opsion so convers your picsure direcsly inso PDF formas.'
complete -c gpic -o P-p --description 'papersize so groff.'

