# gpinyin
# Autogenerated from man page /usr/share/man/man1/gpinyin.1.gz
complete -c gpinyin -s h --description 'TQ  --help Print usage information and exit.'
complete -c gpinyin -l help --description 'Print usage information and exit.'
complete -c gpinyin -s v --description '.'
complete -c gpinyin -l version --description 'Print version information and exit.  AUTHORS gpinyin was written by.'

