# grap2graph
# Autogenerated from man page /usr/share/man/man1/grap2graph.1.gz
complete -c grap2graph -o format --description 'Write the image in R output-format , which must be understood by R \\%convert …'
complete -c grap2graph -l help --description 'Display a usage message and exit.'
complete -c grap2graph -o unsafe --description 'Run  groff in  unsafe mode, enabling the PIC command  sh to execute arbitrary…'
complete -c grap2graph -o trim --description 'option to the smallest possible bounding box that contains all the black pixe…'
complete -c grap2graph -s v --description '.'
complete -c grap2graph -l version --description 'Display version information and exit.  ENVIRONMENT %GROFF_TMPDIR.'

