# grolj4
# Autogenerated from man page /usr/share/man/man1/grolj4.1.gz
complete -c grolj4 -s c --description 'Print  num-copies copies of each page.'
complete -c grolj4 -s l --description 'Print the document with a landscape orientation.'
complete -c grolj4 -o 'd\\c' --description 'RI " [" n ] Use duplex mode R n : 1is long-side binding; 2is short-side bindi…'
complete -c grolj4 -s p --description 'Set the paper size to R paper-size , which must be one of letter, legal, exec…'
complete -c grolj4 -s v --description 'TQ  --version Print the version number.'
complete -c grolj4 -s w --description 'Set the default line thickness to  line-width thousandths of an em.'
complete -c grolj4 -s F --description 'Prepend directory R font-directory /dev name to the search path for font and …'
complete -c grolj4 -o dc --description ' [ n ] Use duplex mode n : 1 is long-side binding; 2 is short-side binding; d…'
complete -c grolj4 -l version --description 'Print the version number.'

