# grolbp
# Autogenerated from man page /usr/share/man/man1/grolbp.1.gz
complete -c grolbp -s c --description 'TQ  --copies= num-copies Print  num-copies copies of each page.'
complete -c grolbp -s F --description 'TQ  --fontdir= font-directory Prepend directory .'
complete -c grolbp -s h --description 'TQ  --help Print a short help text.'
complete -c grolbp -s l --description 'TQ  --landscape Print the document with a landscape orientation.'
complete -c grolbp -s o --description 'TQ  --orientation= orientation Print the document with  orientation orientati…'
complete -c grolbp -s p --description 'TQ  --papersize= paper-size Set the paper size to R paper-size , which must b…'
complete -c grolbp -s v --description 'TQ  --version Print the version number.'
complete -c grolbp -l copies --description 'Print num-copies copies of each page.'
complete -c grolbp -l fontdir --description 'Prepend directory font-directory /dev name to the search path for font and de…'
complete -c grolbp -l help --description 'Print a short help text.'
complete -c grolbp -l landscape --description 'Print the document with a landscape orientation.'
complete -c grolbp -l orientation --description 'Print the document with orientation orientation, which must be `portrait\' or …'
complete -c grolbp -l papersize --description 'Set the paper size to paper-size , which must be a valid paper size descripti…'
complete -c grolbp -l version --description 'Print the version number.'
complete -c grolbp -s w --description '.'
complete -c grolbp -l linewidth --description 'Set the default line thickness to width thousandths of an em.'

