# grpunconv
# Autogenerated from man page /usr/share/man/man8/grpunconv.8.gz
complete -c grpunconv -s h -l help --description 'Display help message and exit.'
complete -c grpunconv -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c grpunconv -l root --description '.'

