# grub-glue-efi
# Autogenerated from man page /usr/share/man/man1/grub-glue-efi.1.gz
complete -c grub-glue-efi -s 3 -l input32 --description 'set input filename for 32-bit part.'
complete -c grub-glue-efi -s 6 -l input64 --description 'set input filename for 64-bit part.'
complete -c grub-glue-efi -s o -l output --description 'set output filename.  Default is STDOUT.'
complete -c grub-glue-efi -s v -l verbose --description 'print verbose messages.'
complete -c grub-glue-efi -s '?' -l help --description 'give this help list.'
complete -c grub-glue-efi -l usage --description 'give a short usage message.'
complete -c grub-glue-efi -s V -l version --description 'print program version.'

