# grub-set-default
# Autogenerated from man page /usr/share/man/man8/grub-set-default.8.gz
complete -c grub-set-default -s h -l help --description 'print this message and exit.'
complete -c grub-set-default -s V -l version --description 'print the version information and exit.'
complete -c grub-set-default -l boot-directory --description 'expect GRUB images under the directory DIR/grub instead of the ,/boot/grub/ d…'

