# grub-kbdcomp
# Autogenerated from man page /usr/share/man/man1/grub-kbdcomp.1.gz
complete -c grub-kbdcomp -s h -l help --description 'print this message and exit.'
complete -c grub-kbdcomp -s V -l version --description 'print the version information and exit.'
complete -c grub-kbdcomp -s o -l output --description 'save output in FILE [required].'

