# grub-mklayout
# Autogenerated from man page /usr/share/man/man1/grub-mklayout.1.gz
complete -c grub-mklayout -s i -l input --description 'set input filename.  Default is STDIN.'
complete -c grub-mklayout -s o -l output --description 'set output filename.  Default is STDOUT.'
complete -c grub-mklayout -s v -l verbose --description 'print verbose messages.'
complete -c grub-mklayout -s '?' -l help --description 'give this help list.'
complete -c grub-mklayout -l usage --description 'give a short usage message.'
complete -c grub-mklayout -s V -l version --description 'print program version.'

