# grub-bios-setup
# Autogenerated from man page /usr/share/man/man8/grub-bios-setup.8.gz
complete -c grub-bios-setup -s a -l allow-floppy --description 'make the drive also bootable as floppy (default for fdX devices).'
complete -c grub-bios-setup -s b -l boot-image --description 'use FILE as the boot image [default=boot. img].'
complete -c grub-bios-setup -s c -l core-image --description 'use FILE as the core image [default=core. img].'
complete -c grub-bios-setup -s d -l directory --description 'use GRUB files in the directory DIR [default=/boot/grub].'
complete -c grub-bios-setup -s f -l force --description 'install even if problems are detected.'
complete -c grub-bios-setup -s m -l device-map --description 'use FILE as the device map [default=/boot/grub/device. map].'
complete -c grub-bios-setup -l no-rs-codes --description 'Do not apply any reed-solomon codes when embedding core. img.'
complete -c grub-bios-setup -s s -l skip-fs-probe --description 'do not probe for filesystems in DEVICE.'
complete -c grub-bios-setup -s v -l verbose --description 'print verbose messages.'
complete -c grub-bios-setup -s '?' -l help --description 'give this help list.'
complete -c grub-bios-setup -l usage --description 'give a short usage message.'
complete -c grub-bios-setup -s V -l version --description 'print program version.'

