# grub-mount
# Autogenerated from man page /usr/share/man/man1/grub-mount.1.gz
complete -c grub-mount -s C -l crypto --description 'Mount crypto devices.'
complete -c grub-mount -s d -l debug --description 'Set debug environment variable.'
complete -c grub-mount -s K -l zfs-key --description 'Load zfs crypto key.'
complete -c grub-mount -s r -l root --description 'Set root device.'
complete -c grub-mount -s v -l verbose --description 'print verbose messages.'
complete -c grub-mount -s '?' -l help --description 'give this help list.'
complete -c grub-mount -l usage --description 'give a short usage message.'
complete -c grub-mount -s V -l version --description 'print program version.'

