# grub-script-check
# Autogenerated from man page /usr/share/man/man1/grub-script-check.1.gz
complete -c grub-script-check -s v -l verbose --description 'print verbose messages.'
complete -c grub-script-check -s '?' -l help --description 'give this help list.'
complete -c grub-script-check -l usage --description 'give a short usage message.'
complete -c grub-script-check -s V -l version --description 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>.'

