# grub-mkimage
# Autogenerated from man page /usr/share/man/man1/grub-mkimage.1.gz
complete -c grub-mkimage -s c -l config --description 'embed FILE as an early config.'
complete -c grub-mkimage -s C -l compression --description 'choose the compression to use for core image.'
complete -c grub-mkimage -s d -l directory --description 'use images and modules under DIR [default=/usr/lib/grub/<platform>].'
complete -c grub-mkimage -s D -l dtb --description 'embed FILE as a device tree (DTB).'
complete -c grub-mkimage -s k -l pubkey --description 'embed FILE as public key for signature checking.'
complete -c grub-mkimage -s m -l memdisk --description 'embed FILE as a memdisk image .'
complete -c grub-mkimage -s n -l note --description 'add NOTE segment for CHRP IEEE1275.'
complete -c grub-mkimage -s o -l output --description 'output a generated image to FILE [default=stdout].'
complete -c grub-mkimage -s O -l format --description 'generate an image in FORMAT available formats: i386-coreboot, i386-multiboot,…'
complete -c grub-mkimage -s p -l prefix --description 'set prefix directory.'
complete -c grub-mkimage -s s -l sbat --description 'SBAT metadata.'
complete -c grub-mkimage -s v -l verbose --description 'print verbose messages.'
complete -c grub-mkimage -s '?' -l help --description 'give this help list.'
complete -c grub-mkimage -l usage --description 'give a short usage message.'
complete -c grub-mkimage -s V -l version --description 'print program version.'

