# grub-mkrelpath
# Autogenerated from man page /usr/share/man/man1/grub-mkrelpath.1.gz
complete -c grub-mkrelpath -s '?' -l help --description 'give this help list.'
complete -c grub-mkrelpath -l usage --description 'give a short usage message.'
complete -c grub-mkrelpath -s V -l version --description 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>.'

