# gtbl
# Autogenerated from man page /usr/share/man/man1/gtbl.1.gz
complete -c gtbl -s C --description 'Enable compatibility mode to recognize  . TS and  .'
complete -c gtbl -s t --description 'option of groff.'
complete -c gtbl -s v --description 'Print the version number.'
complete -c gtbl -o ms --description 'macros which provide this functionality if a table starts with .'

