# gts-config
# Autogenerated from man page /usr/share/man/man1/gts-config.1.gz
complete -c gts-config -l prefix --description '.'
complete -c gts-config -l exec-prefix --description '.'
complete -c gts-config -l version --description '.'
complete -c gts-config -l libs --description '.'
complete -c gts-config -l cflags --description '.'
complete -c gts-config -l check --description '.'

