# gts2stl
# Autogenerated from man page /usr/share/man/man1/gts2stl.1.gz
complete -c gts2stl -s r -l revert --description 'Revert face normals.'
complete -c gts2stl -s v -l verbose --description 'Display surface statistics.'
complete -c gts2stl -s h -l help --description 'Display the help and exit.'

