# gtscompare
# Autogenerated from man page /usr/share/man/man1/gtscompare.1.gz
complete -c gtscompare -s s -l symmetric --description 'Symmetric statistics.'
complete -c gtscompare -s i -l image --description 'Output visualisation mesh.'
complete -c gtscompare -s c -l cmap --description 'Load  FILE as colormap.'
complete -c gtscompare -s m -l min --description 'Use  VAL as minimum scaling value.'
complete -c gtscompare -s M -l max --description 'Use  VAL as maximum scaling value.'
complete -c gtscompare -s r -l reverse --description 'Reverse colormap.'
complete -c gtscompare -s l -l log --description 'Use log scale.'
complete -c gtscompare -s h -l help --description 'Display the help and exit.'

