# gtstemplate
# Autogenerated from man page /usr/share/man/man1/gtstemplate.1.gz
complete -c gtstemplate -l no-extra-data --description '.'
complete -c gtstemplate -l no-extra-method --description '.'
complete -c gtstemplate -l overload --description '.'

