# happrox
# Autogenerated from man page /usr/share/man/man1/happrox.1.gz
complete -c happrox -s n -l number --description 'Stop the refinement process if the number of vertices is larger than N.'
complete -c happrox -s c -l cost --description 'Stop the refinement process if the cost of insertion of a vertex is smaller t…'
complete -c happrox -s f -l flat --description 'Input is a flat file with three x,y,z columns (default is PGM file).'
complete -c happrox -s r -l relative --description 'Use relative height cost for all heights larger than Z.'
complete -c happrox -s k -l keep --description 'Keep enclosing triangle.'
complete -c happrox -s C -l closed --description 'Close the surface.'
complete -c happrox -s l -l log --description 'Log evolution of cost.'
complete -c happrox -s v -l verbose --description 'Display surface statistics.'
complete -c happrox -s h -l help --description 'Display the help and exit.'

