# hd
# Autogenerated from man page /usr/share/man/man1/hd.1.gz
complete -c hd -s b -l one-byte-octal --description 'One-byte octal display.'
complete -c hd -s c -l one-byte-char --description 'One-byte character display.'
complete -c hd -s C -l canonical --description 'Canonical hex+ASCII display.'
complete -c hd -s d -l two-bytes-decimal --description 'Two-byte decimal display.'
complete -c hd -s e -l format --description 'Specify a format string to be used for displaying data.'
complete -c hd -s f -l format-file --description 'Specify a file that contains one or more newline-separated format strings.'
complete -c hd -s L -l color --description 'Accept color units for the output.'
complete -c hd -s n -l length --description 'Interpret only  length bytes of input.'
complete -c hd -s o -l two-bytes-octal --description 'Two-byte octal display.'
complete -c hd -s s -l skip --description 'Skip  offset bytes from the beginning of the input.'
complete -c hd -s v -l no-squeezing --description 'The  -v option causes  hexdump to display all input data.'
complete -c hd -s x -l two-bytes-hex --description 'Two-byte hexadecimal display.'
complete -c hd -s V -l version --description 'Display version information and exit.'
complete -c hd -s h -l help --description 'Display help text and exit.'

