# hp-align
# Autogenerated from man page /usr/share/man/man1/hp-align.1.gz
complete -c hp-align -o 'd<device-uri>' -l device --description 'To specify a CUPS printer:.'
complete -c hp-align -o 'p<printer>' -l printer --description 'MODE Run in interactive mode:.'
complete -c hp-align -s i -l interactive --description 'OPTIONS Set the logging level:.'
complete -c hp-align -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-align -s g -o ldebug --description 'This help information:.'
complete -c hp-align -s h -l help --description 'SEE ALSO hp-clean hp-colorcal hp-linefeedcal hp-pqdiag AUTHOR HPLIP (HP Linux…'

