# hp-doctor
# Autogenerated from man page /usr/share/man/man1/hp-doctor.1.gz
complete -c hp-doctor -s i -l interactive --description 'OPTIONS This help information:.'
complete -c hp-doctor -s h -l help --description 'Set the logging level:.'
complete -c hp-doctor -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-doctor -s g -o ldebug --description 'AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP developed solution for …'

