# hp-firmware
# Autogenerated from man page /usr/share/man/man1/hp-firmware.1.gz
complete -c hp-firmware -o 'd<device-uri>' -l device --description 'To specify a CUPS printer:.'
complete -c hp-firmware -o 'p<printer>' -l printer --description 'MODE Run in interactive mode:.'
complete -c hp-firmware -s i -l interactive --description 'Run in non-interactive mode:.'
complete -c hp-firmware -s n -l non-interactive --description 'OPTIONS Set the logging level:.'
complete -c hp-firmware -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-firmware -s g -o ldebug --description 'This help information:.'
complete -c hp-firmware -s h -l help --description 'Use USB IDs to specify printer:.'
complete -c hp-firmware -s s --description 'Seconds to delay before download:.'
complete -c hp-firmware -o 'y<secs>' -l delay --description 'SEE ALSO hp-plugin hp-toolbox AUTHOR HPLIP (HP Linux Imaging and Printing) is…'

