# hp-info
# Autogenerated from man page /usr/share/man/man1/hp-info.1.gz
complete -c hp-info -o 'd<device-uri>' -l device --description 'To specify a CUPS printer:.'
complete -c hp-info -o 'p<printer>' -l printer --description 'MODE Run in interactive mode:.'
complete -c hp-info -s i -l interactive --description 'OPTIONS Set the logging level:.'
complete -c hp-info -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-info -s g -o ldebug --description 'This help information:.'
complete -c hp-info -s h -l help --description 'Device ID mode:.'
complete -c hp-info -l id --description 'Allow device URIs of uninstalled printers:.'
complete -c hp-info -s x --description 'SEE ALSO hp-toolbox AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP dev…'

