# hp-levels
# Autogenerated from man page /usr/share/man/man1/hp-levels.1.gz
complete -c hp-levels -o 'd<device-uri>' -l device --description 'To specify a CUPS printer:.'
complete -c hp-levels -o 'p<printer>' -l printer --description 'MODE Run in interactive mode:.'
complete -c hp-levels -s i -l interactive --description 'OPTIONS Set the logging level:.'
complete -c hp-levels -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-levels -s g -o ldebug --description 'This help information:.'
complete -c hp-levels -s h -l help --description 'Bar graph size:.'
complete -c hp-levels -o 's<size>' -l size --description 'Use colored bar graphs:.'
complete -c hp-levels -s c -l color --description 'Bar graph character:.'
complete -c hp-levels -o 'a<char>' -l char --description 'AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP developed solution for …'

