# hp-pkservice
# Autogenerated from man page /usr/share/man/man1/hp-pkservice.1.gz
complete -c hp-pkservice -s i -l interactive --description 'OPTIONS Set the logging level:.'
complete -c hp-pkservice -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-pkservice -s g -o ldebug --description 'This help information:.'
complete -c hp-pkservice -s h -l help --description 'OPTIONS (GENERAL) PolicyKit version:.'
complete -c hp-pkservice -o 'v<version>' -l version --description 'AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP developed solution for …'

