# hp-testpage
# Autogenerated from man page /usr/share/man/man1/hp-testpage.1.gz
complete -c hp-testpage -o 'd<device-uri>' -l device --description 'To specify a CUPS printer:.'
complete -c hp-testpage -o 'p<printer>' -l printer --description 'MODE Run in interactive mode:.'
complete -c hp-testpage -s i -l interactive --description 'OPTIONS Set the logging level:.'
complete -c hp-testpage -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*default) Run in debug mode:.'
complete -c hp-testpage -s g -o ldebug --description 'This help information:.'
complete -c hp-testpage -s h -l help --description 'AUTHOR HPLIP (HP Linux Imaging and Printing) is an HP developed solution for …'

