# hpftodit
# Autogenerated from man page /usr/share/man/man1/hpftodit.1.gz
complete -c hpftodit -s a --description 'Include characters in the TFM file that are not included in R map-file .'
complete -c hpftodit -s d --description 'Dump information about the TFM file to the standard output; this option can b…'
complete -c hpftodit -s q --description 'Suppress warnings about characters in the map file that were not found in the…'
complete -c hpftodit -s v --description 'Print the  hpftodit version number and exit.'
complete -c hpftodit -s s --description 'The font is special.'
complete -c hpftodit -s i --description 'Generate an italic correction for each character so that the character\'s widt…'

