# htdbm
# Autogenerated from man page /usr/share/man/man1/htdbm.1.gz
complete -c htdbm -s b --description 'Use batch mode; i. e.'
complete -c htdbm -s i --description 'Read the password from stdin without verification (for script usage).'
complete -c htdbm -s c --description 'Create the passwdfile.'
complete -c htdbm -s n --description 'Display the results on standard output rather than updating a database.'
complete -c htdbm -s m --description 'Use MD5 encryption for passwords.'
complete -c htdbm -s B --description 'Use bcrypt encryption for passwords.'
complete -c htdbm -s C --description 'This flag is only allowed in combination with -B (bcrypt encryption).'
complete -c htdbm -s d --description 'Use crypt() encryption for passwords.'
complete -c htdbm -s s --description 'Use SHA encryption for passwords.'
complete -c htdbm -s p --description 'Use plaintext passwords.'
complete -c htdbm -s l --description 'Print each of the usernames and comments from the database on stdout.'
complete -c htdbm -s v --description 'Verify the username and password.'
complete -c htdbm -s x --description 'Delete user.'
complete -c htdbm -s t --description 'Interpret the final parameter as a comment.'

