# HTMLLinker
# Autogenerated from man page /usr/share/man/man1/HTMLLinker.1.gz
complete -c HTMLLinker -l help --description 'Prints a short list of available options.'
complete -c HTMLLinker -l version --description 'Displays version information.'
complete -c HTMLLinker -l verbose --description 'Prints additional information while processing.'
complete -c HTMLLinker -o Warn --description 'Print additional information about unresolved links.'
complete -c HTMLLinker -o LinksMarker --description 'Only fix links with attribute rel\\f\\=xxx.'
complete -c HTMLLinker -o FixupAllLinks --description 'Attempt to fix all links (not only those that are marked with -LinksMarker.'
complete -c HTMLLinker -o PathMappingsFile --description 'Read the relocation mappings from  file (in dictionary format).'
complete -c HTMLLinker -o PathMappings --description 'Use the specified path mappings.'
complete -c HTMLLinker -s l --description 'and.'
complete -c HTMLLinker -s d --description 'options are allowed):.'
complete -c HTMLLinker -o BuildRelocationFileForDir --description 'Build a relocation file for the directory dir and save it into dir/table.'

