# i386
# Autogenerated from man page /usr/share/man/man8/i386.8.gz
complete -c i386 -l list --description 'List the architectures that setarch knows about.'
complete -c i386 -l 'uname-2.6' --description 'Causes the program to see a kernel version number beginning with 2. 6.'
complete -c i386 -s v -l verbose --description 'Be verbose.'
complete -c i386 -s 3 -l 3gb --description 'Specifies  program should use a maximum of 3GB of address space.'
complete -c i386 -l 4gb --description 'This option has no effect.'
complete -c i386 -s B -l 32bit --description 'Limit the address space to 32 bits to emulate hardware.'
complete -c i386 -s F -l fdpic-funcptrs --description 'Treat user-space function pointers to signal handlers as pointers to address …'
complete -c i386 -s I -l short-inode --description 'Obsolete bug emulation flag.   Turns on SHORT_INODE.'
complete -c i386 -s L -l addr-compat-layout --description 'Provide legacy virtual address space layout.'
complete -c i386 -s R -l addr-no-randomize --description 'Disables randomization of the virtual address space.'
complete -c i386 -s S -l whole-seconds --description 'Obsolete bug emulation flag.   Turns on WHOLE_SECONDS.'
complete -c i386 -s T -l sticky-timeouts --description 'This makes  select (2),  pselect (2), and  ppoll (2) system calls preserve th…'
complete -c i386 -s X -l read-implies-exec --description 'If this is set then  mmap (3p) PROT_READ will also add the PROT_EXEC bit - as…'
complete -c i386 -s Z -l mmap-page-zero --description 'SVr4 bug emulation that will set  mmap (3p) page zero as read-only.'
complete -c i386 -s V -l version --description 'Display version information and exit.'
complete -c i386 -s h -l help --description 'Display help text and exit.  EXAMPLE setarch --addr-no-randomize mytestprog.'

