# ifconfig
# Autogenerated from man page /usr/share/man/man8/ifconfig.8.gz
complete -c ifconfig -s a --description 'display all interfaces which are currently available, even if down.'
complete -c ifconfig -s s --description 'display a short list (like netstat -i).'
complete -c ifconfig -s v --description 'be more verbose for some error conditions.'

