# ilbmtoppm
# Autogenerated from man page /usr/share/man/man1/ilbmtoppm.1.gz
complete -c ilbmtoppm -o verbose --description 'Give some information about the ILBM file.'
complete -c ilbmtoppm -o ignore --description 'Skip a chunk.'
complete -c ilbmtoppm -o isham -o isehb --description 'Treat the input file as a HAM or Extra_Halfbrite picture, even if these flags…'
complete -c ilbmtoppm -o adjustcolors --description 'If all colors in the CMAP have a value of less then 16, ilbmtoppm assumes a 4…'

