# im-config
# Autogenerated from man page /usr/share/man/man8/im-config.8.gz
complete -c im-config -s a --description 'List all; force to list all possible input methods in menu or STDOUT even if …'
complete -c im-config -s c --description 'Use console dialogue.'
complete -c im-config -s x --description 'Use X dialogue with zenity.'
complete -c im-config -s s --description 'No action; perform a simulation of events that would occur but do not actuall…'
complete -c im-config -s l --description 'List all available input method configuration settings to STDOUT.'
complete -c im-config -s m --description 'List configuration values to STDOUT: . RS 12 . ie n \\{\\ \\h\'-04\'\\(bu\\h\'+03\'\\c .'
complete -c im-config -s n --description '<input method name>  Set input method to <input method name>.'
complete -c im-config -s o --description '<input method name>.'

