# inkview
# Autogenerated from man page /usr/share/man/man1/inkview.1.gz
complete -c inkview -s '?' -l help --description 'Show help options.'
complete -c inkview -s V -l version --description 'Print Inkview version and build date (this is usually matches the Inkscape ve…'
complete -c inkview -s f -l fullscreen --description 'Launch Inkview in fullscreen mode.'
complete -c inkview -s r -l recursive --description 'Search folders specified on the command line recursively for \\s-1SVG\\s0 files.'
complete -c inkview -s t -l timer --description 'Change to the next image every \\s-1NUMBER\\s0 seconds.'
complete -c inkview -s s -l scale --description 'Show image scaled by a factor of \\s-1NUMBER\\s0 instead of using the file\'s na…'

