# ip6tables-apply
# Autogenerated from man page /usr/share/man/man8/ip6tables-apply.8.gz
complete -c ip6tables-apply -s t -l timeout --description 'Sets the timeout in seconds after which the script will roll back to the prev…'
complete -c ip6tables-apply -s w -l write --description 'Specify the savefile where successfully applied rules will be written to (def…'
complete -c ip6tables-apply -s c -l command --description 'Run command runcmd to configure iptables instead of applying a rulesfile (def…'
complete -c ip6tables-apply -s h -l help --description 'Display usage information.'
complete -c ip6tables-apply -s V -l version --description 'Display version information.  SEE ALSO.'

