# ip6tables-restore
# Autogenerated from man page /usr/share/man/man8/ip6tables-restore.8.gz
complete -c ip6tables-restore -s c -l counters --description 'restore the values of all packet and byte counters.'
complete -c ip6tables-restore -s h -l help --description 'Print a short option summary.'
complete -c ip6tables-restore -s n -l noflush --description 'don\'t flush the previous contents of the table.'
complete -c ip6tables-restore -s t -l test --description 'Only parse and construct the ruleset, but do not commit it.'
complete -c ip6tables-restore -s v -l verbose --description 'Print additional debug info during ruleset processing.'
complete -c ip6tables-restore -s V -l version --description 'Print the program version number.'
complete -c ip6tables-restore -s w -l wait --description 'Wait for the xtables lock.'
complete -c ip6tables-restore -s W -l wait-interval --description 'Interval to wait per each iteration.'
complete -c ip6tables-restore -s M -l modprobe --description 'Specify the path to the modprobe program.'
complete -c ip6tables-restore -s T -l table --description 'Restore only the named table even if the input stream contains other ones.'

