# ip6tables-save
# Autogenerated from man page /usr/share/man/man8/ip6tables-save.8.gz
complete -c ip6tables-save -s M -l modprobe --description 'Specify the path to the modprobe program.'
complete -c ip6tables-save -s f -l file --description 'Specify a filename to log the output to.'
complete -c ip6tables-save -s c -l counters --description 'include the current values of all packet and byte counters in the output.'
complete -c ip6tables-save -s t -l table --description 'restrict output to only one table.'

