# isodump
# Autogenerated from man page /usr/share/man/man1/isodump.1.gz
complete -c isodump -s h --description 'print a summary of all options.'
complete -c isodump -s d --description 'Print information from the primary volume descriptor (PVD) of the iso9660 ima…'
complete -c isodump -s f --description 'generate output as if a \'find .'
complete -c isodump -s i --description 'Specifies the path of the iso9660 image that we wish to examine.'
complete -c isodump -s l --description 'generate output as if a \'ls -lR\' command had been run on the iso9660 image.'
complete -c isodump -s N --description 'Quick hack to help examine single session disc files that are to be written t…'
complete -c isodump -s p --description 'Print path table information.'
complete -c isodump -s R --description 'Extract information from Rock Ridge extensions (if present) for permissions, …'
complete -c isodump -s J --description 'Extract information from Joliet extensions (if present) for file names.'
complete -c isodump -s j --description 'Convert Joliet file names (if present) to the supplied charset.'
complete -c isodump -s T --description 'Quick hack to help examine multi-session images that have already been burned…'
complete -c isodump -o help -o version --description 'i =name, dev =name.  The isoinfo program has additional command line options.'
complete -c isodump -s x --description 'Extract specified file to stdout.'

