# jpegtopnm
# Autogenerated from man page /usr/share/man/man1/jpegtopnm.1.gz
complete -c jpegtopnm -o dct --description 'Use integer DCT method (default).'
complete -c jpegtopnm -o nosmooth --description 'Use a faster, lower-quality upsampling routine.'
complete -c jpegtopnm -o maxmemory --description 'Set limit on the amount of memory   jpegtopnm uses in processing large images.'
complete -c jpegtopnm -o notadobe --description 'There are two variations on the CMYK (and likewise YCCK) color space that may…'
complete -c jpegtopnm -o dumpexif --description 'Print the interpreted contents of any Exif header in the input file to the  S…'
complete -c jpegtopnm -o exif --description 'Extract the contents of the EXIF header from the input image and write it to …'
complete -c jpegtopnm -o comments --description 'Print any comments in the input file to the Standard Error file.'
complete -c jpegtopnm -o verbose --description 'Print details about the conversion to the Standard Error file.'
complete -c jpegtopnm -o adobe --description '.'
complete -c jpegtopnm -o tracelevel --description 'Turn on the JPEG library\'s trace messages to the Standard Error file.'

