# jsonlint-php
# Autogenerated from man page /usr/share/man/man1/jsonlint-php.1.gz
complete -c jsonlint-php -s q -l quiet --description 'Cause jsonlint to be quiet when no errors are found.'
complete -c jsonlint-php -s h -l help --description 'Show this message.'

