# JxrDecApp
# Autogenerated from man page /usr/share/man/man1/JxrDecApp.1.gz
complete -c JxrDecApp -s i --description 'Input JPEG XR/HD Photo file name . PP.'
complete -c JxrDecApp -s o --description 'Output image file name bmp: <=8bpc, BGR tif: >=8bpc, RGB jxr: for compress…'
complete -c JxrDecApp -s c --description 'Specifies the uncompressed output format 0: 24bppBGR 1: 1bppBlackWhite 2: …'
complete -c JxrDecApp -s r --description 'Specifies the rectangle for region decode . PP.'
complete -c JxrDecApp -s T --description 'Reduced resolution (mipmap) decode 0: Full resolution (default) 1: 1/2 res …'
complete -c JxrDecApp -s O --description '0: No transformation (default) 1: Flip vertically 2: Flip horizontally 3: …'
complete -c JxrDecApp -s s --description 'Used for compressed domain transcoding 0: All subbands included (default) 1…'
complete -c JxrDecApp -s a --description '0: Decode without alpha channel 1: Decode only alpha channel 2: Decode imag…'
complete -c JxrDecApp -s p --description 'Post processing filter strength 0: None (default) 1: Light 2: Medium 3: S…'
complete -c JxrDecApp -s C --description 'Suppress overlapping boundary macro blocks (Used for compressed domain tile …'
complete -c JxrDecApp -s t --description 'Display timing information . PP.'
complete -c JxrDecApp -s v --description 'Display verbose decoder information.'

