# JxrEncApp
# Autogenerated from man page /usr/share/man/man1/JxrEncApp.1.gz
complete -c JxrEncApp -s i --description 'Input image file name bmp: <=8bpc, BGR tif: >=8bpc, RGB hdr: 24bppRGBE onl…'
complete -c JxrEncApp -s o --description 'Output JPEG XR file name . PP.'
complete -c JxrEncApp -s q --description '[0. 0 - 1. 0) Default = 1. 0, lossless.'
complete -c JxrEncApp -s c --description 'Required to define uncompressed source pixel format 0: 24bppBGR 1: 1bppBlac…'
complete -c JxrEncApp -s d --description '0: Y-only 1: YCoCg 4:2:0 2: YCoCg 4:2:2 3: YCoCg 4:4:4 (default) P (if no…'
complete -c JxrEncApp -s l --description '0: No overlapping 1: One level overlapping (default) 2: Two level overlappi…'
complete -c JxrEncApp -s f --description 'Turn off frequency order bit stream (to spatial) . PP.'
complete -c JxrEncApp -s p --description 'Turn off progressive mode (to sequential) . PP.'
complete -c JxrEncApp -s t --description 'Display timing information . PP.'
complete -c JxrEncApp -s v --description 'Display verbose encoder information . PP.'
complete -c JxrEncApp -s V --description 'Macro block columns per tile  . PP.'
complete -c JxrEncApp -s H --description 'Macro block rows per tile . PP.'
complete -c JxrEncApp -s U --description 'Vertical & horizontal tile count for uniform tiling . PP.'
complete -c JxrEncApp -s b --description 'Applies to 1bpp black/white images 0: 0 = black (default) 1: 0 = white .'
complete -c JxrEncApp -s a --description 'Required for any pixel format with an alpha channel 2: Planar alpha (default…'
complete -c JxrEncApp -s Q --description '[1 - 255] Default = 1, lossless . PP.'
complete -c JxrEncApp -s F --description '[0 - 15]  0: no trimming (default) 15: trim all . PP.'
complete -c JxrEncApp -s s --description '0: All subbands included (default) 1: Skip flexbits 2: Skip highpass 3: Sk…'

