# kbdrate
# Autogenerated from man page /usr/share/man/man8/kbdrate.8.gz
complete -c kbdrate -s r -l rate --description 'Change the keyboard repeat rate to  NUMBER cps.'
complete -c kbdrate -s d -l delay --description 'Change the delay to  NUMBER milliseconds.'
complete -c kbdrate -s s -l silent --description 'Silent.  No messages are printed.'
complete -c kbdrate -s h -l help --description 'Display a help text.'
complete -c kbdrate -s V -l version --description 'Display a version number and exit.'

