# kbxutil
# Autogenerated from man page /usr/share/man/man1/kbxutil.1.gz
complete -c kbxutil -l from --description 'first record to export.'
complete -c kbxutil -l to --description 'last record to export.'
complete -c kbxutil -s v -l verbose --description 'verbose.'
complete -c kbxutil -s q -l quiet --description 'be somewhat more quiet.'
complete -c kbxutil -s n -l dry-run --description 'do not make any changes.'
complete -c kbxutil -l debug --description 'set debugging flags.'
complete -c kbxutil -l stats --description 'show key statistics.'
complete -c kbxutil -l import-openpgp --description 'import OpenPGP keyblocks.'
complete -c kbxutil -l find-dups --description 'find duplicates.'
complete -c kbxutil -l cut --description 'export records.'
complete -c kbxutil -l debug-all --description 'enable full debugging.'

