# kcookiejar5
# Autogenerated from man page /usr/share/man/man8/kcookiejar5.8.gz
complete -c kcookiejar5 -o h--help --description 'Show help about options.'
complete -c kcookiejar5 -o v--version --description 'Show version information.'
complete -c kcookiejar5 -l shutdown --description 'Shut down cookie jar and the D-Bus service.'
complete -c kcookiejar5 -l remove --description 'Removes cookies for domain from the cookie jar.'
complete -c kcookiejar5 -l remove-all --description 'Removes all the cookies from the cookie jar.'
complete -c kcookiejar5 -l reaload-config --description 'Reloads the configuration file.'

