# kdeinit5
# Autogenerated from man page /usr/share/man/man8/kdeinit5.8.gz
complete -c kdeinit5 -l help --description 'Show help about options.'
complete -c kdeinit5 -l no-fork --description 'Do not fork, i. e.  do not exit until all the executed programs ends.'
complete -c kdeinit5 -l no-kded --description 'Do not start kded.'
complete -c kdeinit5 -l suicide --description 'Terminate when no KDE applications are left running.'

