# keyring
# Autogenerated from man page /usr/share/man/man1/keyring.1.gz
complete -c keyring -s h -l help --description 'Show the help message and exit.'
complete -c keyring -s p -l keyring-path --description 'Specify path to the keyring backend to use.'
complete -c keyring -s b -l keyring-backend --description 'Specify name of the keyring backend to use.'
complete -c keyring -l list-backends --description 'List the available keyring backends and exit.'
complete -c keyring -l disable --description 'Create a configuration file disabling keyring and exit.'

