# kf5-config
# Autogenerated from man page /usr/share/man/man1/kf5-config.1.gz
complete -c kf5-config -l expandvars --description 'Expand ${prefix} and ${exec_prefix} in output.'
complete -c kf5-config -l prefix --description 'Compiled in prefix for Frameworks libraries.'
complete -c kf5-config -l exec-prefix --description 'Compiled in exec_prefix for Frameworks libraries.'
complete -c kf5-config -l libsuffix --description 'Compiled in library path suffix.'
complete -c kf5-config -l localprefix --description 'Prefix in $HOME used to write files.'
complete -c kf5-config -l version --description 'Version of Qt(TM) and compiled in version string for Frameworks libraries and…'
complete -c kf5-config -l kde-version --description 'Compiled in version string for Frameworks libraries.'
complete -c kf5-config -l types --description 'Print a list of all available KDE resource types.'
complete -c kf5-config -l path --description 'Search path for the specified type.'
complete -c kf5-config -l userpath --description 'User paths for the types: desktop|document.'
complete -c kf5-config -l install --description 'Prefix to install resource files to.'
complete -c kf5-config -l qt-prefix --description 'Installation prefix for Qt(TM).'
complete -c kf5-config -l qt-binaries --description 'Location of installed Qt(TM) binaries.'
complete -c kf5-config -l qt-libraries --description 'Location of installed Qt(TM) libraries.'
complete -c kf5-config -l qt-plugins --description 'Location of installed Qt(TM) plugins.'

