# kf5kross
# Autogenerated from man page /usr/share/man/man1/kf5kross.1.gz
complete -c kf5kross -o h--help --description 'Show help about options.'
complete -c kf5kross -o v--version --description 'Show version information.'
complete -c kf5kross -l author --description 'Show author information.'
complete -c kf5kross -l license --description 'Show license information.'

