# kill
# Autogenerated from man page /usr/share/man/man1/kill.1.gz
complete -c kill -o '<signal>' --description 'TQ  -s <signal> . TQ  --signal <signal> Specify the  signal to be sent.'
complete -c kill -s l -l list --description 'List signal names.'
complete -c kill -s L -l table --description 'List signal names in a nice table.'
complete -c kill -s 9 -o SIGKILL --description 'or.'
complete -c kill -o KILL --description 'Negative PID values may be used to choose whole process groups; see the PGID …'
complete -c kill -s 1 --description 'is special; it indicates all processes except the kill process itself and ini…'
complete -c kill -s s --description '.'
complete -c kill -l signal --description 'Specify the signal to be sent.'

