# kmodsign
# Autogenerated from man page /usr/share/man/man1/kmodsign.1.gz
complete -c kmodsign -s p --description 'save a copy of the p7s signature (. p7s).'
complete -c kmodsign -s d --description 'produce a detached signature file (. p7s) only.'
complete -c kmodsign -s D --description 'produce a full detached signature block (may be cat\'d onto the end of a modul…'
complete -c kmodsign -s k --description 'switch to using keyid for identification.'

