# kup-filedigger
# Autogenerated from man page /usr/share/man/man1/kup-filedigger.1.gz
complete -c kup-filedigger -s v -l version --description 'Show version information.'
complete -c kup-filedigger -s h -l help --description 'Show summary of options and basic help.'
complete -c kup-filedigger -s b -l branch --description 'Name of the branch to be opened.'
complete -c kup-filedigger -l author --description 'Show author information.'
complete -c kup-filedigger -l license --description 'Show license information.'
complete -c kup-filedigger -l desktopfile --description 'The base file name of the desktop entry for this application.  ARGUMENTS.'

