# kup-daemon
# Autogenerated from man page /usr/share/man/man1/kup-daemon.1.gz
complete -c kup-daemon -s v -l version --description 'Show version information.'
complete -c kup-daemon -s h -l help --description 'Show summary of options and basic help.'
complete -c kup-daemon -l author --description 'Show author information.'
complete -c kup-daemon -l license --description 'Show license information.'
complete -c kup-daemon -l desktopfile --description 'The base file name of the desktop entry for this application.'

