# l2test
# Autogenerated from man page /usr/share/man/man1/l2test.1.gz
complete -c l2test -s b -s i -s P -s J --description '[-I imtu] [-O omtu] [-L seconds] enable SO_LINGER [-W seconds] enable deferre…'
complete -c l2test -s r --description '.'
complete -c l2test -s w --description '.'
complete -c l2test -s d --description '.'
complete -c l2test -s x --description '.'
complete -c l2test -s t --description '.'
complete -c l2test -s q --description '.'
complete -c l2test -s s --description '.'
complete -c l2test -s u --description '.'
complete -c l2test -s n --description '.'
complete -c l2test -s y --description '.'
complete -c l2test -s c --description '.'
complete -c l2test -s m --description '.'
complete -c l2test -s p --description '.'
complete -c l2test -s z --description 'OPTIONS [-b bytes] [-i device] [-P psm] [-J cid] [-I imtu] [-O omtu] [-L seco…'

