# laptop-detect
# Autogenerated from man page /usr/share/man/man1/laptop-detect.1.gz
complete -c laptop-detect -s h -l help --description 'Output help information and exit.'
complete -c laptop-detect -s v -l verbose --description 'be verbose (messages go to STDOUT).'
complete -c laptop-detect -s V -l version --description 'Output version information and exit.'

