# libpng16-config
# Autogenerated from man page /usr/share/man/man1/libpng16-config.1.gz
complete -c libpng16-config -l prefix --description 'print libpng prefix.'
complete -c libpng16-config -l libdir --description 'print path to directory containing library.'
complete -c libpng16-config -l libs --description 'print library linking information.'
complete -c libpng16-config -l ccopts --description 'print compiler options.'
complete -c libpng16-config -l cppflags --description 'print pre-processor flags.'
complete -c libpng16-config -l cflags --description 'print preprocessor flags, I_opts, and compiler options.'
complete -c libpng16-config -l I_opts --description 'print "-I" include options.'
complete -c libpng16-config -l L_opts --description 'print linker "-L" flags for dynamic linking.'
complete -c libpng16-config -l R_opts --description 'print dynamic linker "-R" or "-rpath" flags.'
complete -c libpng16-config -l ldopts --description 'print linker options.'
complete -c libpng16-config -l ldflags --description 'print linker flags (ldopts, L_opts, R_opts, and libs).'
complete -c libpng16-config -l static --description 'revise subsequent outputs for static linking.'
complete -c libpng16-config -l help --description 'print this help and exit.'
complete -c libpng16-config -l version --description 'print version information AUTHOR This manpage has been written by Junichi Uek…'

