# libwacom-list-local-devices
# Autogenerated from man page /usr/share/man/man1/libwacom-list-local-devices.1.gz
complete -c libwacom-list-local-devices -l database --description 'Sets the data directory path to be used.'

