# linkicc
# Autogenerated from man page /usr/share/man/man1/linkicc.1.gz
complete -c linkicc -s 8 --description 'Creates 8-bit devicelink.'
complete -c linkicc -s b --description 'Black point compensation.'
complete -c linkicc -s c --description 'Precission (0=LowRes, 1=Normal, 2=Hi-res).  [defaults to 1].'
complete -c linkicc -s d --description 'Description text (quotes can be used).'
complete -c linkicc -s h --description 'Show summary of options and examples.'
complete -c linkicc -s i --description 'Input profile (defaults to sRGB).'
complete -c linkicc -s k --description 'Ink-limiting in % (CMYK only).'
complete -c linkicc -s o --description 'Output devicelink profile.  [defaults to \'devicelink. icm\'].'
complete -c linkicc -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute).'
complete -c linkicc -s x --description 'Creatively, guess deviceclass of resulting profile.'

