# lkbib
# Autogenerated from man page /usr/share/man/man1/lkbib.1.gz
complete -c lkbib -l help --description 'Display a usage message and exit.'
complete -c lkbib -s i --description 'When searching files for which no index exists, ignore the contents of fields…'
complete -c lkbib -s p --description 'Search R filename .  Multiple  -p options can be used.'
complete -c lkbib -s t --description 'Only require the first  n characters of keys to be given.  Initially  n is\\~6.'
complete -c lkbib -s v --description '.'
complete -c lkbib -l version --description 'Display version information and exit.  ENVIRONMENT REFER Default database.'

