# llvm-size-12
# Autogenerated from man page /usr/share/man/man1/llvm-size-12.1.gz
complete -c llvm-size-12 -l common --description 'When using Berkeley format, this is added to bss.'
complete -c llvm-size-12 -l help -l help-hidden --description '.'
complete -c llvm-size-12 -l help-list -l help-list-hidden --description '.'
complete -c llvm-size-12 -l version --description '.'
complete -c llvm-size-12 -s A --description '.'
complete -c llvm-size-12 -s B --description '.'
complete -c llvm-size-12 -s m -s m --description '.'
complete -c llvm-size-12 -l arch --description '.'
complete -c llvm-size-12 -l format --description '.'
complete -c llvm-size-12 -s l --description 'Print size in radix:.'
complete -c llvm-size-12 -s o --description '.'
complete -c llvm-size-12 -s d --description '.'
complete -c llvm-size-12 -s x --description '.'
complete -c llvm-size-12 -l radix --description '.'
complete -c llvm-size-12 -l totals --description '.'

