# llvm-ranlib-12
# Autogenerated from man page /usr/share/man/man1/llvm-ranlib-12.1.gz
complete -c llvm-ranlib-12 -s h -l help --description '.'
complete -c llvm-ranlib-12 -s v -l version --description '.'
complete -c llvm-ranlib-12 -s D --description '.'
complete -c llvm-ranlib-12 -s U --description '.'

