# lpadmin
# Autogenerated from man page /usr/share/man/man8/lpadmin.8.gz
complete -c lpadmin -s c --description 'Adds the named printer to class.'
complete -c lpadmin -s m --description 'Sets a standard PPD file for the printer from the model directory or using on…'
complete -c lpadmin -s o --description 'Specifies whether IPP supply level values should be reported.'
complete -c lpadmin -s R --description 'Deletes the named option from printer.'
complete -c lpadmin -s r --description 'Removes the named printer from class.'
complete -c lpadmin -s u --description 'Sets user-level access control on a destination.'
complete -c lpadmin -s v --description 'Sets the device-uri attribute of the printer queue.'
complete -c lpadmin -s D --description 'Provides a textual description of the destination.'
complete -c lpadmin -s E --description 'When specified before the -d, -p, or -x options, forces the use of TLS encryp…'
complete -c lpadmin -s L --description 'Provides a textual location of the destination.'
complete -c lpadmin -s i --description 'This option historically has been used to provide either a System V interface…'
complete -c lpadmin -s P --description 'Specifies a PostScript Printer Description (PPD) file to use with the printer.'

