# make_strings
# Autogenerated from man page /usr/share/man/man1/make_strings.1.gz
complete -c make_strings -l help --description 'Prints a short list of available options.'
complete -c make_strings -l verbose --description 'Prints additional information while processing.'
complete -c make_strings -s L --description 'Specify which languages to process.'
complete -c make_strings -l aggressive-import --description 'Activates  --aggresive-match and automatically removes "dummy" entries that a…'
complete -c make_strings -l aggressive-match --description 'This option will make  make_strings assume that matching keys should have mat…'
complete -c make_strings -l aggresive-match --description 'and automatically removes "dummy" entries that are added by importing .'
complete -c make_strings -l aggressive-remove --description 'Removes obsolete strings/keys.'

