# man-recode
# Autogenerated from man page /usr/share/man/man1/man-recode.1.gz
complete -c man-recode -s t -l to-code --description 'Convert manual pages to R encoding .'
complete -c man-recode -l suffix --description 'Form each output file name by appending  suffix to the input file name, after…'
complete -c man-recode -l in-place --description 'Overwrite each input file with the output, after removing any compression ext…'
complete -c man-recode -s q -l quiet --description 'Do not issue error messages when the page cannot be converted.'
complete -c man-recode -s d -l debug --description 'Print debugging information.'
complete -c man-recode -s h -l help --description 'Print a help message and exit.'
complete -c man-recode -s V -l version --description 'Display version information.  SEE ALSO iconv (1), man (1), manconv (1).'

