# manpath
# Autogenerated from man page /usr/share/man/man1/manpath.1.gz
complete -c manpath -s q -l quiet --description 'Do not issue warnings.'
complete -c manpath -s d -l debug --description 'Print debugging information.'
complete -c manpath -s c -l catpath --description 'Produce a catpath as opposed to a manpath.'
complete -c manpath -s g -l global --description 'Produce a manpath consisting of all paths named as "global" within the man-db…'
complete -c manpath -s m --description '--systems=system\\|[\\|,. \\|. \\|.'
complete -c manpath -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c manpath -s '?' -l help --description 'Print a help message and exit.'
complete -c manpath -l usage --description 'Print a short usage message and exit.'
complete -c manpath -l systems --description 'If this system has access to other operating system\'s manual hierarchies, thi…'
complete -c manpath -s V -l version --description 'Display version information.  ENVIRONMENT.'

