# mdsearch
# Autogenerated from man page /usr/share/man/man1/mdsearch.1.gz
complete -c mdsearch -s p -l path --description 'Server side path to search, defaults to "/".'
complete -c mdsearch -s L -l live --description 'Query remains running.'

