# migrate-pubring-from-classic-gpg
# Autogenerated from man page /usr/share/man/man1/migrate-pubring-from-classic-gpg.1.gz
complete -c migrate-pubring-from-classic-gpg -l default --description 'selects the standard GnuPG home directory (looking at $GNUPGHOME first, and f…'
complete -c migrate-pubring-from-classic-gpg -s h -l help -l usage --description 'Output a short usage information.'

