# mii-tool
# Autogenerated from man page /usr/share/man/man8/mii-tool.8.gz
complete -c mii-tool -s v -l verbose --description 'Display more detailed MII status information.'
complete -c mii-tool -s V -l version --description 'Display program version information.'
complete -c mii-tool -s R -l reset --description 'Reset the MII to its default configuration.'
complete -c mii-tool -s r -l restart --description 'Restart autonegotiation.'
complete -c mii-tool -s w -l watch --description 'Watch interface(s) and report changes in link status.'
complete -c mii-tool -s l -l log --description 'Used with -w, records link status changes in the system log instead of printi…'
complete -c mii-tool -s F -l force --description 'Disable autonegotiation, and force the MII to either 100baseTx-FD, 100baseTx-…'
complete -c mii-tool -s A -l advertise --description 'Enable and restart autonegotiation, and advertise only the specified media te…'
complete -c mii-tool -s p -l phy --description 'Override the MII address provided by kernel with value addr.'

