# mkinitramfs
# Autogenerated from man page /usr/share/man/man8/mkinitramfs.8.gz
complete -c mkinitramfs -s c --description 'Override the  COMPRESS setting in R initramfs. conf .'
complete -c mkinitramfs -s d --description 'Set an alternate configuration directory.'
complete -c mkinitramfs -s k --description 'Keep the temporary directory used to make the image.'
complete -c mkinitramfs -s o --description 'Write the image to R outfile .'
complete -c mkinitramfs -s r --description 'Override the  ROOT setting in R initramfs. conf .'
complete -c mkinitramfs -s v --description 'Set the verbose mode output.'
complete -c mkinitramfs -s h -l help --description 'Display usage information and exit.'

