# more
# Autogenerated from man page /usr/share/man/man1/more.1.gz
complete -c more -s d -l silent --description 'Prompt with "[Press space to continue, \'q\' to quit.'
complete -c more -s l -l logical --description 'Do not pause after any line containing a  ^L (form feed).'
complete -c more -s f -l no-pause --description 'Count logical lines, rather than screen lines (i. e.'
complete -c more -s p -l print-over --description 'Do not scroll.   Instead, clear the whole screen and then display the text.'
complete -c more -s c -l clean-print --description 'Do not scroll.'
complete -c more -s s -l squeeze --description 'Squeeze multiple blank lines into one.'
complete -c more -s u -l plain --description 'Suppress underlining.'
complete -c more -s n -l lines --description 'Specify the  number of lines per screenful.'
complete -c more -l help --description 'Display help text and exit.'
complete -c more -s V -l version --description 'Display version information and exit.'

