# nameif
# Autogenerated from man page /usr/share/man/man8/nameif.8.gz
complete -c nameif -s s --description 'argument is given all error messages go to the syslog.'
complete -c nameif -s c --description 'argument is given with a file name that file is read instead of /etc/mactab.'

