# netkit-ftp
# Autogenerated from man page /usr/share/man/man1/netkit-ftp.1.gz
complete -c netkit-ftp -s 4 --description 'Use only IPv4 to contact any host.'
complete -c netkit-ftp -s 6 --description 'Use IPv6 only.'
complete -c netkit-ftp -s p --description 'Use passive mode for data transfers.'
complete -c netkit-ftp -s i --description 'Turns off interactive prompting during multiple file transfers.'
complete -c netkit-ftp -s n --description 'Restrains netkit-ftp ftp from attempting \\*(Lqauto-login\\*(Rq upon initial co…'
complete -c netkit-ftp -s e --description 'Disables command editing and history support, if it was compiled into the net…'
complete -c netkit-ftp -s g --description 'Disables file name globbing.'
complete -c netkit-ftp -s v --description 'Verbose option forces netkit-ftp ftp to show all responses from the remote se…'
complete -c netkit-ftp -s d --description 'Enables debugging.'

