# netpbm
# Autogenerated from man page /usr/share/man/man1/netpbm.1.gz
complete -c netpbm -o quiet --description 'Suppress all informational messages that would otherwise be issued to  Standa…'
complete -c netpbm -o version --description 'Instead of doing anything else, report the version of the libpbm library link…'
complete -c netpbm -o exec --description 'option) and  xargs  are also useful for simple manipulation of groups of file…'

