# networkd-dispatcher
# Autogenerated from man page /usr/share/man/man8/networkd-dispatcher.8.gz
complete -c networkd-dispatcher -s h -l help --description 'Print command-line syntax and program options to stdout.'
complete -c networkd-dispatcher -s S -l script-dir --description 'Location under which to look for scripts.'
complete -c networkd-dispatcher -s T -l run-startup-triggers --description 'Generate events reflecting preexisting state and behavior on startup.'
complete -c networkd-dispatcher -s v -l verbose --description 'Increase verbosity by one level.  The default level is WARNING.'
complete -c networkd-dispatcher -s q -l quiet --description 'Decrease verbosity by one level.'

