# nm-initrd-generator
# Autogenerated from man page /usr/share/man/man8/nm-initrd-generator.8.gz
complete -c nm-initrd-generator -s c -l connections-dir --description 'Output connection directory.'
complete -c nm-initrd-generator -s i -l initrd-data-dir --description 'Output directory for initrd data (e. g.  hostname).'
complete -c nm-initrd-generator -s d -l sysfs-dir --description 'The sysfs mount point.'
complete -c nm-initrd-generator -s r -l run-config-dir --description 'Output directory for config files.'
complete -c nm-initrd-generator -s s -l stdout --description 'Dump connections to standard output.  Useful for debugging.'

