# ntfs-3g
# Autogenerated from man page /usr/share/man/man8/ntfs-3g.probe.8.gz
complete -c ntfs-3g -s r -l readonly --description 'Test if the volume can be mounted read-only.'
complete -c ntfs-3g -s w -l readwrite --description 'Test if the volume can be mounted read-write.'
complete -c ntfs-3g -s h -l help --description 'Display help and exit.'

