# ntfsfallocate
# Autogenerated from man page /usr/share/man/man8/ntfsfallocate.8.gz
complete -c ntfsfallocate -s f -l force --description 'This will override some sensible defaults, such as not using a mounted volume.'
complete -c ntfsfallocate -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfsfallocate -s l -l length --description 'This is a mandatory option to specify the number of bytes to preallocate.'
complete -c ntfsfallocate -s n -l no-size-change --description 'Do not change the apparent size of the file.'
complete -c ntfsfallocate -s N -l no-action --description 'Simulate the allocation without actually write to device.'
complete -c ntfsfallocate -s o -l offset --description 'Specify the offset in the file where preallocation starts.'
complete -c ntfsfallocate -s q -l quiet --description 'Suppress some debug/warning/error messages.'
complete -c ntfsfallocate -s v -l verbose --description 'Display more debug/warning/error messages.'
complete -c ntfsfallocate -s V -l version --description 'Show the version number, copyright and license of  ntfsfallocate .'
complete -c ntfsfallocate -o fv --description 'is equivalent to.'

