# ntfssecaudit
# Autogenerated from man page /usr/share/man/man8/ntfssecaudit.8.gz
complete -c ntfssecaudit -s h --description 'Displays in an human readable form the hexadecimal security descriptors saved…'
complete -c ntfssecaudit -s a --description 'Audits the volume : all the global security data on volume are scanned and er…'
complete -c ntfssecaudit -s r --description 'displays the security parameters of all files and subdirectories in directory…'
complete -c ntfssecaudit -s b --description 'Recursively extracts to standard output the NTFS ACLs of files in volume and …'
complete -c ntfssecaudit -s s --description 'Sets the NTFS ACLS as indicated in backup-file or standard input.'
complete -c ntfssecaudit -s u --description 'Displays a proposed contents for a user mapping file, based on the ownership …'

