# okular
# Autogenerated from man page /usr/share/man/man1/okular.1.gz
complete -c okular -s p -l page --description '.'
complete -c okular -l presentation --description '.'
complete -c okular -l print --description '.'
complete -c okular -l print-and-exit --description '.'
complete -c okular -l unique --description '.'
complete -c okular -l noraise --description '.'
complete -c okular -l find --description '.'

