# openapp
# Autogenerated from man page /usr/share/man/man1/openapp.1.gz
complete -c openapp -l find --description 'will print out the full path of the application executable which would be exe…'
complete -c openapp -l debug --description 'starts the application in the debugger.'
complete -c openapp -l library-combo --description 'Starts the application with the specified library combo.'
complete -c openapp -l gdb --description 'argument or through the  GDB shell variable.'
complete -c openapp -l help --description 'print above usage description.'

