# palmtopnm
# Autogenerated from man page /usr/share/man/man1/palmtopnm.1.gz
complete -c palmtopnm -o verbose --description 'Display various interesting information about the input file and process.'
complete -c palmtopnm -o transparent --description 'If the Palm pixmap has a transparent color set, the RGB value for that color …'
complete -c palmtopnm -o rendition --description 'Palm pixmaps may contain several different renditions of the same pixmap, wit…'
complete -c palmtopnm -o showhist --description 'Writes a histogram of colors in the input file to stderr.'
complete -c palmtopnm -o forceplain --description 'Force the output anymap to be in ASCII \'plain\' netpbm format.'

