# pam-auth-update
# Autogenerated from man page /usr/share/man/man8/pam-auth-update.8.gz
complete -c pam-auth-update -l package --description 'Indicate that the caller is a package maintainer script; lowers the priority …'
complete -c pam-auth-update -l enable --description 'Enable the specified profiles in system configuration.'
complete -c pam-auth-update -l remove --description 'Remove the specified profiles from the system configuration.'
complete -c pam-auth-update -l force --description 'option.'

