# pam_systemd
# Autogenerated from man page /usr/share/man/man8/pam_systemd.8.gz
complete -c pam_systemd -o auth --description 'auth      required   pam_deny. so.'
complete -c pam_systemd -o account --description 'account   sufficient pam_unix. so account   required   pam_permit. so.'
complete -c pam_systemd -o password --description 'password  sufficient pam_unix.'
complete -c pam_systemd -o session --description '.'

