# pastebinit
# Autogenerated from man page /usr/share/man/man1/pastebinit.1.gz
complete -c pastebinit -s a --description '.'
complete -c pastebinit -s b --description '.'
complete -c pastebinit -s E --description '.'
complete -c pastebinit -s f --description '.'
complete -c pastebinit -s h --description '.'
complete -c pastebinit -s i --description '.'
complete -c pastebinit -s l --description '.'
complete -c pastebinit -s j --description '.'
complete -c pastebinit -s m --description '.'
complete -c pastebinit -s t --description '.'
complete -c pastebinit -s P --description '.'
complete -c pastebinit -s u --description '.'
complete -c pastebinit -s p --description '.'
complete -c pastebinit -s v --description '.'

