# pbmreduce
# Autogenerated from man page /usr/share/man/man1/pbmreduce.1.gz
complete -c pbmreduce -o value --description 'flag.  OPTIONS.'
complete -c pbmreduce -o threshold --description 'flag can be used to specify simple thresholding.   This gives better.'

