# pbmtext
# Autogenerated from man page /usr/share/man/man1/pbmtext.1.gz
complete -c pbmtext -o font -o builtin --description 'By default, pbmtext uses a built-in font called bdf (about a 10 point Times-R…'
complete -c pbmtext -o space --description 'Add   pixels pixels of space between characters.'
complete -c pbmtext -s B -o lspace --description 'Add pixels pixels of space between lines.'
complete -c pbmtext -o alpha --description 'option.'
complete -c pbmtext -o invert --description 'option to  pnmcomp .'

