# pcre-config
# Autogenerated from man page /usr/share/man/man1/pcre-config.1.gz
complete -c pcre-config -l prefix --description 'Writes the directory prefix used in the PCRE installation for architecture in…'
complete -c pcre-config -l exec-prefix --description 'Writes the directory prefix used in the PCRE installation for architecture de…'
complete -c pcre-config -l version --description 'Writes the version of PCRE installed to standard output.'
complete -c pcre-config -l libs --description 'Writes to standard output the command line options required to link with PCRE…'
complete -c pcre-config -l libs-posix --description 'Writes to standard output the command line options required to link with the …'
complete -c pcre-config -l cflags --description 'Writes to standard output the command line options required to compile  files…'
complete -c pcre-config -l cflags-posix --description 'Writes to standard output the command line options required to compile files …'

