# pcxtoppm
# Autogenerated from man page /usr/share/man/man1/pcxtoppm.1.gz
complete -c pcxtoppm -o stdpalette --description 'Enforce the use of the internal colormap for files with 16 colors or less.'

