# pdfmom
# Autogenerated from man page /usr/share/man/man1/pdfmom.1.gz
complete -c pdfmom -o Tpdf --description 'option (which is the default), pdfmom processes files using groff\'s native PD…'
complete -c pdfmom -o Tps --description 'is given, processing is passed over to pdfroff , which uses groff \'s PostScri…'
complete -c pdfmom -o mpdfmark -o mom -l no-toc --description '.'
complete -c pdfmom -s m --description 'options when.'
complete -c pdfmom -s v --description 'option, pdfmom simply displays its version information and exits.'

