# peardev
# Autogenerated from man page /usr/share/man/man1/peardev.1.gz
complete -c peardev -s v --description 'increase verbosity level (default 1).'
complete -c peardev -s q --description 'be quiet, decrease verbosity level.'
complete -c peardev -s c --description 'find user configuration in file.'
complete -c peardev -s C --description 'find system configuration in file.'
complete -c peardev -s d --description 'set user config variable foo to bar.'
complete -c peardev -s D --description 'set system config variable foo to bar.'
complete -c peardev -s G --description 'start in graphical (Gtk) mode.'
complete -c peardev -s S --description 'store system configuration.'
complete -c peardev -s s --description 'store user configuration.'
complete -c peardev -s y --description 'unset  foo in the user configuration.'
complete -c peardev -s V --description 'version information.'
complete -c peardev -s h --description '.'
complete -c peardev -s '?' --description 'display help/usage.'

