# pecl
# Autogenerated from man page /usr/share/man/man1/pecl.1.gz
complete -c pecl -s v --description 'increase verbosity level (default 1).'
complete -c pecl -s q --description 'be quiet, decrease verbosity level.'
complete -c pecl -s c --description 'find user configuration in file.'
complete -c pecl -s C --description 'find system configuration in file.'
complete -c pecl -s d --description 'set user config variable foo to bar.'
complete -c pecl -s D --description 'set system config variable foo to bar.'
complete -c pecl -s G --description 'start in graphical (Gtk) mode.'
complete -c pecl -s S --description 'store system configuration.'
complete -c pecl -s s --description 'store user configuration.'
complete -c pecl -s y --description 'unset  foo in the user configuration.'
complete -c pecl -s V --description 'version information.'
complete -c pecl -s h --description '.'
complete -c pecl -s '?' --description 'display help/usage.'

