# pftp
# Autogenerated from man page /usr/share/man/man1/pftp.1.gz
complete -c pftp -s 4 --description 'Use only IPv4 to contact any host.'
complete -c pftp -s 6 --description 'Use IPv6 only.'
complete -c pftp -s p --description 'Use passive mode for data transfers.'
complete -c pftp -s i --description 'Turns off interactive prompting during multiple file transfers.'
complete -c pftp -s n --description 'Restrains pftp ftp from attempting \\*(Lqauto-login\\*(Rq upon initial connecti…'
complete -c pftp -s e --description 'Disables command editing and history support, if it was compiled into the pft…'
complete -c pftp -s g --description 'Disables file name globbing.'
complete -c pftp -s v --description 'Verbose option forces pftp ftp to show all responses from the remote server, …'
complete -c pftp -s d --description 'Enables debugging.'

