# pgmnorm
# Autogenerated from man page /usr/share/man/man1/pgmnorm.1.gz
complete -c pgmnorm -o bpercent --description 'and.'
complete -c pgmnorm -o wpercent --description 'flags, or you can specify the exact pixel values to be mapped by using the.'
complete -c pgmnorm -o bvalue --description 'and.'
complete -c pgmnorm -o wvalue --description 'flags.  Appropriate numbers for the flags can be gotten from the ppmhist tool.'
complete -c pgmnorm -o keephues --description 'option says to keep each pixel the same hue as it is in the input; just adjus…'
complete -c pgmnorm -o brightmax --description 'option says to use the intensity of the most intense RGB component of a pixel…'

