# pgmslice
# Autogenerated from man page /usr/share/man/man1/pgmslice.1.gz
complete -c pgmslice -o row --description 'Extract a row of pixels.'
complete -c pgmslice -o col --description 'Extract a column of pixels SEE ALSO pgm(5) AUTHOR pgmslice was written by Jos…'

