# pgmtopbm
# Autogenerated from man page /usr/share/man/man1/pgmtopbm.1.gz
complete -c pgmtopbm -o fs --description 'Also available are simple thresholding ( -threshold );.'
complete -c pgmtopbm -o cluster4 --description '.'
complete -c pgmtopbm -o cluster8 --description 'A space filling curve halftoning method using the Hilbert curve is also avail…'
complete -c pgmtopbm -o value --description 'flag alters the thresholding value for Floyd-Steinberg and simple thresholdin…'
complete -c pgmtopbm -o clump --description 'flag alters the number of pixels in a clump.'

