# phar7
# Autogenerated from man page /usr/share/man/man1/phar7.4.1.gz
complete -c phar7 -s f --description 'Specifies the phar file to work on.'
complete -c phar7 -s a --description 'Provide an alias name for the phar file.'
complete -c phar7 -s c --description 'Compression algorithm (see.'
complete -c phar7 -s i --description 'Specifies a regular expression for input files.'
complete -c phar7 -s l --description 'Number of preceding subdirectories to strip from file entries.'
complete -c phar7 -s x --description 'Regular expression for input files to exclude.'
complete -c phar7 -s e --description 'Name of entry to work on (must include PHAR internal directory name if any).'
complete -c phar7 -s k --description 'Subscription index to work on.'
complete -c phar7 -s m --description 'Meta data to store with entry (serialized php data).'
complete -c phar7 -s b --description 'Hash-bang line to start the archive (e. g.  #!/usr/bin/php).'
complete -c phar7 -s h --description 'Selects the hash algorithm (see.'
complete -c phar7 -s p --description 'Location of PHP_Archive class file (pear list-files PHP_Archive).'
complete -c phar7 -s s --description 'Select the stub file.'
complete -c phar7 -s y --description 'Private key for OpenSSL signing.'

