# phpize
# Autogenerated from man page /usr/share/man/man1/phpize.1.gz
complete -c phpize -l clean --description 'Remove all created files.'
complete -c phpize -l help --description 'Prints usage information.'
complete -c phpize -l version --description '.'
complete -c phpize -s v --description 'Prints API version information SEE ALSO php (1) VERSION INFORMATION This manp…'

