# phpize7
# Autogenerated from man page /usr/share/man/man1/phpize7.4.1.gz
complete -c phpize7 -l clean --description 'Remove all created files.'
complete -c phpize7 -l help --description 'Prints usage information.'
complete -c phpize7 -l version --description '.'
complete -c phpize7 -s v --description 'Prints API version information SEE ALSO php (1) VERSION INFORMATION This manp…'

