# pic2graph
# Autogenerated from man page /usr/share/man/man1/pic2graph.1.gz
complete -c pic2graph -o eqn --description 'Use  delimiters as the opening and closing characters that delimit  eqn direc…'
complete -c pic2graph -o format --description 'Write the image in R output-format , which must be understood by R \\%convert …'
complete -c pic2graph -l help --description 'Display a usage message and exit.'
complete -c pic2graph -o unsafe --description 'Run  groff in  unsafe mode, enabling the PIC command  sh to execute arbitrary…'
complete -c pic2graph -o trim --description 'option to the smallest possible bounding box that contains all the black pixe…'
complete -c pic2graph -s v --description '.'
complete -c pic2graph -l version --description 'Display version information and exit.  ENVIRONMENT %GROFF_TMPDIR.'

