# pidof
# Autogenerated from man page /usr/share/man/man8/pidof.8.gz
complete -c pidof -s s --description 'Single shot - this instructs the program to only return one pid.'
complete -c pidof -s c --description 'Only return process PIDs that are running with the same root directory.'
complete -c pidof -s n --description 'Avoid  stat (2) system function call on all binaries which are located on net…'
complete -c pidof -s q --description 'Do not display matched PIDs to standard out.'
complete -c pidof -s x --description 'Scripts too - this causes the program to also return process id\'s of shells r…'
complete -c pidof -s z --description 'Try to detect processes which are stuck in uninterruptible (D) or zombie (Z) …'
complete -c pidof -s d --description 'Tells pidof to use sep as an output separator if more than one PID is shown.'
complete -c pidof -s o --description 'Tells pidof to omit processes with that process id.'

