# pinentry-x11
# Autogenerated from man page /usr/share/man/man1/pinentry-x11.1.gz
complete -c pinentry-x11 -l version --description 'Print the program version and licensing information.'
complete -c pinentry-x11 -l help --description 'Print a usage message summarizing the most useful command-line options.'
complete -c pinentry-x11 -l debug -s d --description 'Turn on some debugging.   Mostly useful for the maintainers.'
complete -c pinentry-x11 -l enhanced -s e --description 'Ask for timeouts and insurance, too.'
complete -c pinentry-x11 -l no-global-grab -s g --description 'Grab the keyboard only when the window is focused.'
complete -c pinentry-x11 -l parent-wid --description 'Use window ID N as the parent window for positioning the window.'
complete -c pinentry-x11 -l display -l ttyname -l ttytype -l lc-type -l lc-messages --description 'These options are used to pass localization information to pinentry-gnome3.'

