# plank
# Autogenerated from man page /usr/share/man/man1/plank.1.gz
complete -c plank -s h -l help --description 'Show help options.'
complete -c plank -l help-all --description 'Show all help options.'
complete -c plank -l help-gapplication --description 'Show GApplication options.'
complete -c plank -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c plank -s d -l debug --description 'Enable debug logging.'
complete -c plank -s v -l verbose --description 'Enable verbose logging.'
complete -c plank -s n -l name --description 'The name of this dock.  Defaults to "dock1".'
complete -c plank -l preferences --description 'Show preferences dialog of the just started or already running instance.'
complete -c plank -s V -l version --description 'Show the application\'s version.'
complete -c plank -l display --description 'X display to use.'

