# plasmapkg2
# Autogenerated from man page /usr/share/man/man1/plasmapkg2.1.gz
complete -c plasmapkg2 -l hash --description 'Generate a SHA1 hash for the package at \\(lqpath\\(rq.'
complete -c plasmapkg2 -s g -l global --description 'For install or remove, operates on packages installed for all users.'
complete -c plasmapkg2 -s t -l type --description 'The type of package, e. g.'
complete -c plasmapkg2 -s i -l install --description 'Install the package at \\(lqpath\\(rq.'
complete -c plasmapkg2 -s s -l show --description 'Show information of package \\(lqname\\(rq.'
complete -c plasmapkg2 -s u -l upgrade --description 'Upgrade the package at \\(lqpath\\(rq.'
complete -c plasmapkg2 -s l -l list --description 'List installed packages.'
complete -c plasmapkg2 -l list-types --description 'Lists all known Package types that can be installed.'
complete -c plasmapkg2 -s r -l remove --description 'Remove the package named \\(lqname\\(rq.'
complete -c plasmapkg2 -s p -l packageroot --description 'Absolute path to the package root.'

