# pldd
# Autogenerated from man page /usr/share/man/man1/pldd.1.gz
complete -c pldd -s '?' -l help --description 'Display a help message and exit.'
complete -c pldd -l usage --description 'Display a short usage message and exit.'
complete -c pldd -s V -l version --description 'Display program version information and exit.'

