# pngtopnm
# Autogenerated from man page /usr/share/man/man1/pngtopnm.1.gz
complete -c pngtopnm -o verbose --description 'Display the format of the input file and the type of the output file.'
complete -c pngtopnm -o alpha --description 'Output the alpha channel or transparency mask of the image.'
complete -c pngtopnm -o mix --description 'Compose the image with the transparency or alpha mask against a the backgroun…'
complete -c pngtopnm -o background --description 'If no background color chunck is present in the   png-file, or when another c…'
complete -c pngtopnm -o gamma --description 'Converts the image to a new display-gamma value.'
complete -c pngtopnm -o text --description 'Writes the tEXt and zTXt chunks to a file, in a format as described in the  p…'
complete -c pngtopnm -o time --description 'Prints the tIME chunk to stderr.'

