# pnmarith
# Autogenerated from man page /usr/share/man/man1/pnmarith.1.gz
complete -c pnmarith -o difference --description 'calculates the absolute value of pnmarith -subtract pnmfile1 pnmfile2, i. e.'

