# pnmcat
# Autogenerated from man page /usr/share/man/man1/pnmcat.1.gz
complete -c pnmcat -o topbottom -o jleft --description 'would stack the anymaps on top of each other, flush with the left edge.'
complete -c pnmcat -o white --description 'and.'
complete -c pnmcat -o black --description 'flags specify what color to use to fill in the extra space when doing this ju…'

