# pnmcut
# Autogenerated from man page /usr/share/man/man1/pnmcut.1.gz
complete -c pnmcut -o left --description 'The column number of the leftmost column to be in the output.'
complete -c pnmcut -o right --description 'The column number of the rightmost column to be in the output, numbered the s…'
complete -c pnmcut -o top --description 'The row number of the topmost row to be in the output.'
complete -c pnmcut -o bottom --description 'The row number of the bottom-most row to be in the output, numbered the same …'
complete -c pnmcut -o width --description 'The number of columns to be in the output.   Must be positive.'
complete -c pnmcut -o height --description 'The number of rows to be in the output.   Must be positive.'
complete -c pnmcut -o pad --description 'If the rectangle you specify is not entirely within the input image,   pnmcut…'
complete -c pnmcut -s 1 --description '.'
complete -c pnmcut -o verbose --description 'Print information about the processing to Standard Error.'

