# pnmcrop
# Autogenerated from man page /usr/share/man/man1/pnmcrop.1.gz
complete -c pnmcrop -o white --description 'Take white to be the background color.'
complete -c pnmcrop -o black --description 'Take black to be the background color.'
complete -c pnmcrop -o sides --description 'Determine the background color from the colors of the four corners of  the in…'
complete -c pnmcrop -o left --description 'Remove any left border.'
complete -c pnmcrop -o right --description 'Remove any right border.'
complete -c pnmcrop -o top --description 'Remove any top border.'
complete -c pnmcrop -o bottom --description 'Remove any bottom border.'
complete -c pnmcrop -o verbose --description 'Print on Standard Error information about the processing, including exactly h…'

