# pnmgamma
# Autogenerated from man page /usr/share/man/man1/pnmgamma.1.gz
complete -c pnmgamma -o ungamma --description 'Apply the inverse of the specified transfer function (i. e.'
complete -c pnmgamma -o cieramp --description 'Use the CIE Rec.  709 gamma transfer function.   Note that it is true CIE Rec.'
complete -c pnmgamma -o srgbramp --description 'the transfer function defaults to a simple power function.'

