# pnmhisteq
# Autogenerated from man page /usr/share/man/man1/pnmhisteq.1.gz
complete -c pnmhisteq -o gray --description 'When processing a pixmap, only gray pixels (those with identical red, green, …'
complete -c pnmhisteq -o rmap --description 'Process the image using the luminosity map specified by the portable graymap …'
complete -c pnmhisteq -o wmap --description 'Creates a portable graymap,  mapfile, containing the luminosity map computed …'
complete -c pnmhisteq -o verbose --description 'Prints the histogram and luminosity map on standard error.'

