# pnmmontage
# Autogenerated from man page /usr/share/man/man1/pnmmontage.1.gz
complete -c pnmmontage -s '?' -o help --description 'Displays a (very) short usage message.'
complete -c pnmmontage -o header --description 'Tells  pnmmontage to write a C header file of the locations of the original i…'
complete -c pnmmontage -o prefix --description 'Tells  pnmmontage to use the specified prefix on all of the #defines it gener…'
complete -c pnmmontage -o quality --description 'Before attempting to place the subimages,  pnmmontage will calculate a minimu…'
complete -c pnmmontage -s q --description 'will find the best possible solution; however, it may take a very long time t…'
complete -c pnmmontage -s 0 -s 1 -s 9 --description 'These options control the quality at a higher level than.'
complete -c pnmmontage -o 'q;' --description '.'
complete -c pnmmontage -s 5 --description 'NOTES Using.'

