# pnmnorm
# Autogenerated from man page /usr/share/man/man1/pnmnorm.1.gz
complete -c pnmnorm -o bpercent --description 'and.'
complete -c pnmnorm -o wpercent --description 'flags, or you can specify the exact pixel values to be mapped by using the.'
complete -c pnmnorm -o bvalue --description 'and.'
complete -c pnmnorm -o wvalue --description 'flags.  Appropriate numbers for the flags can be gotten from the ppmhist tool.'
complete -c pnmnorm -o keephues --description 'option says to keep each pixel the same hue as it is in the input; just adjus…'
complete -c pnmnorm -o brightmax --description 'option says to use the intensity of the most intense RGB component of a pixel…'

