# pnmpaste
# Autogenerated from man page /usr/share/man/man1/pnmpaste.1.gz
complete -c pnmpaste -o replace --description 'The other, logical operations are only allowed if both input images are bitma…'

