# pnmrotate
# Autogenerated from man page /usr/share/man/man1/pnmrotate.1.gz
complete -c pnmrotate -o noantialias --description 'flag.   This does the shearing by moving pixels without changing their values.'

