# pnmscalefixed
# Autogenerated from man page /usr/share/man/man1/pnmscalefixed.1.gz
complete -c pnmscalefixed -o verbose --description 'option tells you how much distortion there is.'
complete -c pnmscalefixed -o nomix --description 'option.'

