# pnmsmooth
# Autogenerated from man page /usr/share/man/man1/pnmsmooth.1.gz
complete -c pnmsmooth -o size --description 'Specifies the size of the convolution matrix.    Default size is a 3x3 matrix.'
complete -c pnmsmooth -o dump --description 'Generates and saves the convolution file only.'

