# pnmshear
# Autogenerated from man page /usr/share/man/man1/pnmshear.1.gz
complete -c pnmshear -o noantialias --description 'flag.   This does the shearing by moving pixels without changing their values.'

