# pnmtopalm
# Autogenerated from man page /usr/share/man/man1/pnmtopalm.1.gz
complete -c pnmtopalm -o verbose --description 'Display the format of the output file.'
complete -c pnmtopalm -o depth --description 'Produce a file of depth  R N ,  where   N  must be either 1, 2, 4, 8, or 16.'
complete -c pnmtopalm -o maxdepth --description 'Produce a file of minimal depth, but in any case less than   N  bits wide.'
complete -c pnmtopalm -o offset --description 'Fill in the   nextDepthOffset  field in the file header, to provide for multi…'
complete -c pnmtopalm -o colormap --description 'Build a custom colormap and include it in the output file.'
complete -c pnmtopalm -o transparent --description 'Marks  one particular color as fully transparent.'
complete -c pnmtopalm -o rle-compression --description 'Specifies that the output Palm bitmap will use the Palm RLE compression schem…'
complete -c pnmtopalm -o scanline-compression --description 'Specifies that the output Palm bitmap will use the Palm scanline compression …'

