# pnmtotiffcmyk
# Autogenerated from man page /usr/share/man/man1/pnmtotiffcmyk.1.gz
complete -c pnmtotiffcmyk -o none -o packbits -o lzw -o predictor --description 'Tiff files can be compressed.'
complete -c pnmtotiffcmyk -o msb2lsb -o lsb2msb --description 'These flags control fill order (default is  -msb2lsb ).'
complete -c pnmtotiffcmyk -o rowsperstrip --description 'This sets the number of rows in an image strip (data in the Tiff files genera…'
complete -c pnmtotiffcmyk -o lowdotrange -o highdotrange --description 'These options set tag values that may be useful for printers.'
complete -c pnmtotiffcmyk -o knormal -o kremove -o konly --description 'These options modify the values written to the Tiff file after the conversion…'
complete -c pnmtotiffcmyk -o default -o negative --description '-negative selects a simple algorithm that generates a colour negative.'
complete -c pnmtotiffcmyk -o theta --description 'The basic conversion from RGB to CMY uses C = 1-R, M = 1-G, Y = 1-B.'
complete -c pnmtotiffcmyk -o gamma --description 'The black (K) component of the image is calculated as min(C,Y,M).'
complete -c pnmtotiffcmyk -o gammap --description 'This option controls the removal of CMY under K.'

