# pnmtofits
# Autogenerated from man page /usr/share/man/man1/pnmtofits.1.gz
complete -c pnmtofits -o min --description 'and .'
complete -c pnmtofits -o max --description 'can be used to set DATAMAX, DATAMIN, BSCALE and BZERO in the FITS header, but…'

