# pnmtops
# Autogenerated from man page /usr/share/man/man1/pnmtops.1.gz
complete -c pnmtops -o imagewidth --description '-imageheight Tells how wide and high you want the image on the page, in inche…'
complete -c pnmtops -o equalpixels --description 'This option causes the output image to have the same number of pixels as the …'
complete -c pnmtops -o scale --description 'tells how big you want the image on the page.'
complete -c pnmtops -o dpi --description 'This option specifies the dots per inch of your output device.'
complete -c pnmtops -o width --description 'br  -height These options specify the dimensions of the page on which the out…'
complete -c pnmtops -o turn --description '-noturn These options control whether the image gets turned 90 degrees.'
complete -c pnmtops -o rle --description '-runlength These identical options specify run-length compression.'
complete -c pnmtops -o nocenter --description 'By default,   pnmtops centers the image on the output page.'
complete -c pnmtops -o imageheight --description '.'
complete -c pnmtops -o height --description 'and.'
complete -c pnmtops -o nosetpage --description 'option.'
complete -c pnmtops -o noturn --description 'These options control whether the image gets turned 90 degrees.'
complete -c pnmtops -o runlength --description 'These identical options specify run-length compression.'
complete -c pnmtops -o center --description 'but it has no effect.'
complete -c pnmtops -o setpage --description 'pnmtops  can generate a "setpagedevice" directive to tell the printer/plotter…'

