# ppmcie
# Autogenerated from man page /usr/share/man/man1/ppmcie.1.gz
complete -c ppmcie -o rec709 -o cie -o ebu -o hdtv -o ntsc -o smpte --description 'Select a standard color system whose gamut to plot.'
complete -c ppmcie -o xy --description 'plot CIE 1931 x y chromaticities.  This is the default.'
complete -c ppmcie -o upvp --description 'plot u\' v\' 1976 chromaticities rather than CIE 1931 x y chromaticities.'
complete -c ppmcie -o red --description 'specifies the CIE R x " and " y co-ordinates of the red illuminant of a custo…'
complete -c ppmcie -o green --description 'specifies the CIE R x " and " y co-ordinates of the green illuminant of the c…'
complete -c ppmcie -o blue --description 'specifies the CIE R x " and " y co-ordinates of the blue illuminant of the co…'
complete -c ppmcie -o white --description 'specifies the CIE R x " and " y co-ordinates of the white point of the color …'
complete -c ppmcie -o size --description 'Create a pixmap of R edge " by " edge pixels.   The default is 512x512.'
complete -c ppmcie -o xsize -o width --description 'Sets the width of the generated image to  width pixels.'
complete -c ppmcie -o ysize -o height --description 'Sets the height of the generated image to  height pixels.'
complete -c ppmcie -o noblack --description 'Don\'t plot the black body chromaticity curve.'
complete -c ppmcie -o nowpoint --description 'Don\'t plot the color system\'s white point.'
complete -c ppmcie -o nolabel --description 'Omit the label.'
complete -c ppmcie -o noaxes --description 'Don\'t plot axes.'
complete -c ppmcie -o full --description 'option,  ppmcie reduces their intensity by 25% compared to the true hues in t…'

