# ppmchange
# Autogenerated from man page /usr/share/man/man1/ppmchange.1.gz
complete -c ppmchange -o closeness --description 'closeness is an integer per centage indicating how close to the color you spe…'
complete -c ppmchange -o remainder --description 'option, in which case they are all changed to the single specified color.'

