# ppmlabel
# Autogenerated from man page /usr/share/man/man1/ppmlabel.1.gz
complete -c ppmlabel -o angle --description 'Sets the angle of the baseline of subsequent text.'
complete -c ppmlabel -o background --description 'If the argument is  `` transparent \'\', text is drawn over the existing pixels…'
complete -c ppmlabel -o colour --description 'Sets the colour for subsequent text.'
complete -c ppmlabel -o file --description 'Reads text from the file  filename and draws it on successive lines.'
complete -c ppmlabel -o size --description 'Sets the height of the tallest characters above the baseline to  textsize pix…'
complete -c ppmlabel -o text --description 'Draws the given text string (which must be quoted if it contains spaces).'
complete -c ppmlabel -s x --description 'Sets the column at which subsequent text will be left justified.'
complete -c ppmlabel -s y --description 'Sets the row which will form the baseline of subsequent text.'

