# ppmtoicr
# Autogenerated from man page /usr/share/man/man1/ppmtoicr.1.gz
complete -c ppmtoicr -o windowname --description 'Output will be displayed in  name (Default is to use  ppmfile or "untitled" i…'
complete -c ppmtoicr -o expand --description 'Output will be expanded on display by factor   expand (For example, a value o…'
complete -c ppmtoicr -o display --description 'Output will be displayed on screen numbered   display.'
complete -c ppmtoicr -o rle --description 'Use run-length encoded format for display.'

