# ppmtopcx
# Autogenerated from man page /usr/share/man/man1/ppmtopcx.1.gz
complete -c ppmtopcx -o 24bit --description 'Produce a 24bit truecolor file, even if the pixmap has 256 colors or less.'
complete -c ppmtopcx -o packed --description 'Use "packed pixel" format for files with 16 colors or less: 1, 2, or 4 bits/p…'
complete -c ppmtopcx -o xpos --description '.'
complete -c ppmtopcx -o ypos --description 'These options set the position of the image in some field (e. g.'

