# ppmtoxpm
# Autogenerated from man page /usr/share/man/man1/ppmtoxpm.1.gz
complete -c ppmtoxpm -o name --description 'The   -name  option allows you to specify the prefix string which is printed …'
complete -c ppmtoxpm -o rgb --description 'option allows you to specify an X11 rgb text file for the lookup of color nam…'
complete -c ppmtoxpm -o alphamask --description 'This option names a PGM file to use as an alpha (transparency) mask.'
complete -c ppmtoxpm -o alphaout --description 'option to  xpmtoppm .'

