# ppmtogif
# Autogenerated from man page /usr/share/man/man1/ppmtogif.1.gz
complete -c ppmtogif -o interlace --description 'Produce an interlaced GIF file.'
complete -c ppmtogif -o sort --description 'Produces a GIF file with a sorted color map.'
complete -c ppmtogif -o map --description 'mapfile  Uses the colors found in the  mapfile to create the colormap in the …'
complete -c ppmtogif -o transparent --description 'ppmtogif marks the specified color as transparent in the GIF image.'
complete -c ppmtogif -o alpha --description 'This option names a PGM file that contains an alpha mask for the image.'
complete -c ppmtogif -o alphacolor --description 'See   -alpha .'
complete -c ppmtogif -o comment --description 'Include a comment in the GIF output with comment text  R text .'
complete -c ppmtogif -o floyd --description 'mapfile.'
complete -c ppmtogif -o nolzw --description 'This option causes the GIF output, and thus  ppmtogif , not to use LZW (Lempe…'

