# ppmtowinicon
# Autogenerated from man page /usr/share/man/man1/ppmtowinicon.1.gz
complete -c ppmtowinicon -o andpgms --description 'If this option is given, every second file is read as an "and mask" to be use…'
complete -c ppmtowinicon -o output --description 'File to write.   By default, the icon is written to stdout.'

