# ppmtompeg
# Autogenerated from man page /usr/share/man/man1/ppmtompeg.1.gz
complete -c ppmtompeg -o stat --description ': causes the encoder to append the statistics to the file stat_file.'
complete -c ppmtompeg -o quiet --description ': causes the program to not report remaining time for at least num_seconds se…'
complete -c ppmtompeg -o realquiet --description ': causes the encoder to run silently, with the only screen output being error…'
complete -c ppmtompeg -o no_frame_summary --description ': prevents the program from printing a summary line for each frame.'
complete -c ppmtompeg -o float_dct --description ': forces the encoder to use a more accurate, yet more computationally expensi…'
complete -c ppmtompeg -o gop --description ': causes the encoder to only encode the numbered GOP (first GOP is 0).'
complete -c ppmtompeg -o combine_gops --description ': causes the encoder to simply combine some GOP files into a single MPEG stre…'
complete -c ppmtompeg -o frames --description ': causes the encoder to only encode the frames from first_frame to last_frame…'
complete -c ppmtompeg -o combine_frames --description ': causes the encoder to simply combine some frames into a single MPEG stream.'
complete -c ppmtompeg -o nice --description ': causes the program to run any remote processes \'nicely.'
complete -c ppmtompeg -o max_machines --description ': causes the program to use no more than num_machines machines as slaves for …'
complete -c ppmtompeg -o snr --description ': print the signal-to-noise ratio.'
complete -c ppmtompeg -o mse --description ': computes the mean squared error per block.'
complete -c ppmtompeg -o bit_rate_info --description ': prints bit rate information into the file rate_file.'
complete -c ppmtompeg -o mv-histogram --description ': prints histogram of motion vectors as part of statistics.'

