# ppmtolj
# Autogenerated from man page /usr/share/man/man1/ppmtolj.1.gz
complete -c ppmtolj -o delta --description 'Apply delta row compression to reduce the size of the pcl file.'
complete -c ppmtolj -o gamma --description 'Gamma correct the image using the integet parameter as a gamma (default 0).'
complete -c ppmtolj -o float --description 'Suppresses positioning information.'
complete -c ppmtolj -o noreset --description 'Prevents writing of the reset sequence to the begining and end of the output.'
complete -c ppmtolj -o resolution --description 'Set the required output resolution 75|100|150|300|600 REFERENCES HP PCL 5 & C…'

