# ppmtosixel
# Autogenerated from man page /usr/share/man/man1/ppmtosixel.1.gz
complete -c ppmtosixel -o raw --description 'If specified, each pixel will be explicitly described in the image file.'
complete -c ppmtosixel -o margin --description 'If.'

