# ppmtoacad
# Autogenerated from man page /usr/share/man/man1/ppmtoacad.1.gz
complete -c ppmtoacad -o dxb --description 'An AutoCAD binary database import (. dxb) file is written.'
complete -c ppmtoacad -o poly --description 'If the  -dxb option is not specified, the output of  ppmtoacad is an AutoCAD …'
complete -c ppmtoacad -o background --description 'Most AutoCAD display drivers can be configured to use any available colour as…'
complete -c ppmtoacad -o white --description 'Since many AutoCAD users choose a white screen background, this option is pro…'
complete -c ppmtoacad -o aspect --description 'If the source pixmap had non-square pixels, the ratio of the pixel width to p…'
complete -c ppmtoacad -s 8 --description 'Restricts the colours in the output file to the 8 RGB shades.'

