# psicc
# Autogenerated from man page /usr/share/man/man1/psicc.1.gz
complete -c psicc -s b --description 'Black point compensation (CRD only).'
complete -c psicc -s i --description 'Input profile: Generates Color Space Array (CSA).'
complete -c psicc -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute).'
complete -c psicc -s o --description '.'
complete -c psicc -s u --description 'Do NOT generate resource name on CRD.'

