# psjoin
# Autogenerated from man page /usr/share/man/man1/psjoin.1.gz
complete -c psjoin -s a --description '.'
complete -c psjoin -s s --description '.'
complete -c psjoin -s p --description '.'
complete -c psjoin -s h --description '.'

