# puttygen
# Autogenerated from man page /usr/share/man/man1/puttygen.1.gz
complete -c puttygen -s t --description 'Specify a type of key to generate.'
complete -c puttygen -s b --description 'Specify the size of the key to generate, in bits.  Default is 2048.'
complete -c puttygen -s q --description 'Suppress the progress display when generating a new key.'
complete -c puttygen -l old-passphrase --description 'Specify a file name; the first line will be read from this file (removing any…'
complete -c puttygen -l random-device --description 'Specify device to read entropy from.'
complete -c puttygen -s C --description 'Specify a comment string to describe the key.'
complete -c puttygen -s P --description 'Indicate that you want to change the key\'s passphrase.'
complete -c puttygen -s O --description 'Specify the type of output you want puttygen to produce.'
complete -c puttygen -s o --description 'Specify the file where puttygen should write its output.'
complete -c puttygen -s l --description 'Synonym for `-O fingerprint\'.'
complete -c puttygen -s L --description 'Synonym for `-O public-openssh\'.'
complete -c puttygen -s p --description 'Synonym for `-O public\'.'
complete -c puttygen -l new-passphrase --description 'Specify a file name; the first line will be read from this file (removing any…'
complete -c puttygen -s h -l help --description 'Display a message summarizing the available options.'
complete -c puttygen -s V -l version --description 'Display the version of PuTTYgen.'
complete -c puttygen -l pgpfp --description 'Display the fingerprints of the PuTTY PGP Master Keys, to aid in verifying ne…'

