# py3compile
# Autogenerated from man page /usr/share/man/man1/py3compile.1.gz
complete -c py3compile -l version --description 'show program\\(aqs version number and exit.'
complete -c py3compile -s h -l help --description 'show this help message and exit.'
complete -c py3compile -s f -l force --description 'force rebuild of byte-code files even if timestamps are up-to-date.'
complete -c py3compile -s O --description 'byte-compile to . pyo files.'
complete -c py3compile -s q -l quiet --description 'be quiet.'
complete -c py3compile -s v -l verbose --description 'turn verbose mode on.'
complete -c py3compile -s p -l package --description 'specify Debian package name whose files should be bytecompiled.'
complete -c py3compile -s V --description 'force private modules to be bytecompiled with Python 3 version from given ran…'
complete -c py3compile -s X -l exclude --description 'exclude items that match given REGEXPR.'
complete -c py3compile -o '4.0' --description '.'

