# py3clean
# Autogenerated from man page /usr/share/man/man1/py3clean.1.gz
complete -c py3clean -l version --description 'show program\\(aqs version number and exit.'
complete -c py3clean -s h -l help --description 'show this help message and exit.'
complete -c py3clean -s v -l verbose --description 'turn verbose more one.'
complete -c py3clean -s q -l quiet --description 'be quiet.'
complete -c py3clean -s p -l package --description 'specify Debian package name to clean.'
complete -c py3clean -s V --description 'specify Python 3 version to clean.'

