# py3rsa-keygen
# Autogenerated from man page /usr/share/man/man1/py3rsa-keygen.1.gz
complete -c py3rsa-keygen -s h -l help --description 'show help message and exit.'
complete -c py3rsa-keygen -l pubout --description 'output filename for the public key.'
complete -c py3rsa-keygen -s o -l out --description 'output filename for the private key.'
complete -c py3rsa-keygen -l form --description 'key format of the private and public keys - default PEM AUTHOR ,py3rsa-keygen…'

