# py3rsa-verify
# Autogenerated from man page /usr/share/man/man1/py3rsa-verify.1.gz
complete -c py3rsa-verify -s h -l help --description 'show help message and exit.'
complete -c py3rsa-verify -s i -l input --description 'name of the signed file to verify.  Read from stdin if not specified.'
complete -c py3rsa-verify -l keyform --description 'key format of the public key - default PEM EXIT STATUS 0 if signature can be …'

