# py3rsa-sign
# Autogenerated from man page /usr/share/man/man1/py3rsa-sign.1.gz
complete -c py3rsa-sign -s h -l help --description 'show help message and exit.'
complete -c py3rsa-sign -s i -l input --description 'name of the file to sign.  read from stdin if not specified.'
complete -c py3rsa-sign -l output --description 'name of the file to write the signature to.'
complete -c py3rsa-sign -l keyform --description 'key format of the private key - default PEM AUTHOR ,py3rsa-sign was written b…'

