# py3rsa-decrypt
# Autogenerated from man page /usr/share/man/man1/py3rsa-decrypt.1.gz
complete -c py3rsa-decrypt -s h -l help --description 'show help message and exit.'
complete -c py3rsa-decrypt -s i -l input --description 'name of the file to decrypt.  read from stdin if not specified.'
complete -c py3rsa-decrypt -s o -l output --description 'name of the file to write the decrypted file to.'
complete -c py3rsa-decrypt -l keyform --description 'key format of the private key - default PEM AUTHOR ,py3rsa-decrypt was writte…'

