# py3rsa-priv2pub
# Autogenerated from man page /usr/share/man/man1/py3rsa-priv2pub.1.gz
complete -c py3rsa-priv2pub -s h -l help --description 'show help message and exit.'
complete -c py3rsa-priv2pub -s i -l input --description 'input filename.  Read from stdin if not specified.'
complete -c py3rsa-priv2pub -l output --description 'output filename.  write to stdout of not specified.'
complete -c py3rsa-priv2pub -l inform --description 'key format of input - default PEM.'
complete -c py3rsa-priv2pub -l outform --description 'key format of output - default PEM AUTHOR ,py3rsa-priv2pub was written by Syb…'

