# py3versions
# Autogenerated from man page /usr/share/man/man1/py3versions.1.gz
complete -c py3versions -s d -l default --description 'Show the default python3 version.'
complete -c py3versions -s s -l supported --description 'Show the supported python3 versions.'
complete -c py3versions -s r -l requested --description 'Reads the value of the  X-Python3-Version field in the source section of a co…'
complete -c py3versions -s i -l installed --description 'Show the installed supported python3 versions.'
complete -c py3versions -s v -l version --description 'Limit the output to the version numbers of the python3 versions.'
complete -c py3versions -s h -l help --description 'Print a help text.  SEE ALSO Python policy.  AUTHOR Matthias Klose.'

