# pyjwt3
# Autogenerated from man page /usr/share/man/man1/pyjwt3.1.gz
complete -c pyjwt3 -l version --description 'show program\'s version number and exit.'
complete -c pyjwt3 -s h -l help --description 'show this help message and exit.'
complete -c pyjwt3 -s n -l no-verify --description 'ignore signature verification on decode.'
complete -c pyjwt3 -l key --description 'set the secret key to sign with.'
complete -c pyjwt3 -l alg --description 'set crypto algorithm to sign with.  default=HS256 .'

