# pysetup3
# Autogenerated from man page /usr/share/man/man1/pysetup3.9.1.gz
complete -c pysetup3 -l verbose -s v --description 'run verbosely (default).'
complete -c pysetup3 -l quiet -s q --description 'run quietly (turns verbosity off).'
complete -c pysetup3 -l dry-run -s n --description 'don\'t actually do anything.'
complete -c pysetup3 -l help -s h --description 'show detailed help message.'
complete -c pysetup3 -l no-user-cfg --description 'ignore pydistutils. cfg in your home directory.'
complete -c pysetup3 -l version --description 'Display the version.'

