# python3
# Autogenerated from man page /usr/share/man/man1/python3.9-config.1.gz
complete -c python3 -l abiflags --description 'print the the ABI flags as specified by PEP 3149.'
complete -c python3 -l cflags --description 'print the C compiler flags.'
complete -c python3 -l ldflags --description 'print the flags that should be passed to the linker.'
complete -c python3 -l includes --description 'similar to --cflags but only with -I options (path to python header files).'
complete -c python3 -l libs --description 'similar to --ldflags but only with -l options (used libraries).'
complete -c python3 -l prefix --description 'prints the prefix (base directory) under which python can be found.'
complete -c python3 -l exec-prefix --description 'print the prefix used for executable program directories (such as bin, sbin, …'
complete -c python3 -l extension-suffix --description 'print the extension suffix used for binary extensions.'

