# qtchooser
# Autogenerated from man page /usr/share/man/man1/qtchooser.1.gz
complete -c qtchooser -o list-versions --description '.'
complete -c qtchooser -o print-env --description '.'
complete -c qtchooser -o qt --description '.'
complete -c qtchooser -o run-tool --description '.'

