# rarp
# Autogenerated from man page /usr/share/man/man8/rarp.8.gz
complete -c rarp -s V --description 'Display the version of RARP in use.'
complete -c rarp -s v --description 'Tell the user what is going on by being verbose.'
complete -c rarp -s t --description 'When setting or reading the RARP table, this optional parameter tells  rarp w…'
complete -c rarp -l list --description 'Lists the entries in the RARP table.'
complete -c rarp -l delete --description 'Remove all RARP entries for the specified host.'
complete -c rarp -s a --description '.'
complete -c rarp -s d --description '.'
complete -c rarp -s s --description '.'
complete -c rarp -l set --description 'Create a RARP address mapping entry for host hostname with hardware address s…'

