# rawtoppm
# Autogenerated from man page /usr/share/man/man1/rawtoppm.1.gz
complete -c rawtoppm -o headerskip --description 'If the file has a header, you can use this flag to skip over it.'
complete -c rawtoppm -o rowskip --description 'If there is padding at the ends of the rows, you can skip it with this flag.'
complete -c rawtoppm -o rgb -o rbg -o grb -o gbr -o brg -o bgr --description 'These flags let you specify alternate color orders.   The default is  -rgb .'
complete -c rawtoppm -o interpixel -o interrow --description 'These flags let you specify how the colors are interleaved.  The default is.'
complete -c rawtoppm -o interplane --description 'flag  - all the red pixels, then all the green, then all the blue - would be …'

