# remmina
# Autogenerated from man page /usr/share/man/man1/remmina.1.gz
complete -c remmina -s h --description 'Show help options.'
complete -c remmina -s a --description 'Show about dialog.'
complete -c remmina -s c --description 'Connect directly either to a desktop using options described in a file, or a …'
complete -c remmina -s e --description 'Open and edit desktop connection using options described by file, file type c…'
complete -c remmina -s k --description 'Start Remmina in kiosk mode (thin client).'
complete -c remmina -s n --description 'Create a new connection profile.'
complete -c remmina -s p --description 'Show preferences dialog page.'
complete -c remmina -s x --description 'Execute the plugin.'
complete -c remmina -s q --description 'Quit the application.'
complete -c remmina -s s --description 'Use default server name (for \\fB\\-\\-new\\fR).'
complete -c remmina -s t --description 'Use default protocol (for \\fB\\-\\-new\\fR).'
complete -c remmina -s i --description 'Start as tray icon.'
complete -c remmina -s v --description 'Show the application\'s version --update-profile\\fR Modify connection profile,…'

