# rotatelogs
# Autogenerated from man page /usr/share/man/man8/rotatelogs.8.gz
complete -c rotatelogs -s l --description 'Causes the use of local time rather than GMT as the base for the interval or …'
complete -c rotatelogs -s L --description 'PP Causes a hard link to be made from the current logfile to the specified li…'
complete -c rotatelogs -s p --description 'If given, rotatelogs will execute the specified program every time a new log …'
complete -c rotatelogs -s f --description 'Causes the logfile to be opened immediately, as soon as rotatelogs starts, in…'
complete -c rotatelogs -s D --description 'Creates the parent directories of the path that the log file will be placed i…'
complete -c rotatelogs -s t --description 'Causes the logfile to be truncated instead of rotated.'
complete -c rotatelogs -s v --description 'Produce verbose output on STDERR.'
complete -c rotatelogs -s e --description 'Echo logs through to stdout.'
complete -c rotatelogs -s c --description 'Create log file for each interval, even if empty.'
complete -c rotatelogs -s n --description 'Use a circular list of filenames without timestamps.'

