# runc-restore
# Autogenerated from man page /usr/share/man/man8/runc-restore.8.gz
complete -c runc-restore -l image-path --description '.'
complete -c runc-restore -l work-path --description '.'
complete -c runc-restore -l tcp-established --description '.'
complete -c runc-restore -l ext-unix-sk --description '.'
complete -c runc-restore -l shell-job --description '.'
complete -c runc-restore -l file-locks --description '.'
complete -c runc-restore -l manage-cgroups-mode --description '.'
complete -c runc-restore -l bundle -s b --description '.'
complete -c runc-restore -l detach -s d --description '.'
complete -c runc-restore -l pid-file --description '.'
complete -c runc-restore -l no-subreaper --description '.'
complete -c runc-restore -l no-pivot --description '.'
complete -c runc-restore -l empty-ns --description '.'
complete -c runc-restore -l auto-dedup --description '.'
complete -c runc-restore -l lazy-pages --description '.'
complete -c runc-restore -l lsm-profile --description 'OPTION DETAILS.'

