# runc
# Autogenerated from man page /usr/share/man/man8/runc.8.gz
complete -c runc -l debug --description '.'
complete -c runc -l log --description '.'
complete -c runc -l log-format --description '.'
complete -c runc -l root --description '.'
complete -c runc -l criu --description '.'
complete -c runc -l systemd-cgroup --description '.'
complete -c runc -l rootless --description '.'
complete -c runc -l help -s h --description '.'
complete -c runc -l version -s v --description '.'

