# runc-run
# Autogenerated from man page /usr/share/man/man8/runc-run.8.gz
complete -c runc-run -l bundle -s b --description '.'
complete -c runc-run -l console-socket --description '.'
complete -c runc-run -l detach -s d --description '.'
complete -c runc-run -l pid-file --description '.'
complete -c runc-run -l no-subreaper --description '.'
complete -c runc-run -l no-pivot --description '.'
complete -c runc-run -l no-new-keyring --description '.'
complete -c runc-run -l preserve-fds --description '.'

