# runc-create
# Autogenerated from man page /usr/share/man/man8/runc-create.8.gz
complete -c runc-create -l bundle -s b --description '.'
complete -c runc-create -l console-socket --description '.'
complete -c runc-create -l pid-file --description '.'
complete -c runc-create -l no-pivot --description '.'
complete -c runc-create -l no-new-keyring --description '.'
complete -c runc-create -l preserve-fds --description '.'

