# runc-exec
# Autogenerated from man page /usr/share/man/man8/runc-exec.8.gz
complete -c runc-exec -l console --description '.'
complete -c runc-exec -l cwd --description '.'
complete -c runc-exec -l env -s e --description '.'
complete -c runc-exec -l tty -s t --description '.'
complete -c runc-exec -l user -s u --description '.'
complete -c runc-exec -l additional-gids -s g --description '.'
complete -c runc-exec -l process -s p --description '.'
complete -c runc-exec -l detach -s d --description '.'
complete -c runc-exec -l pid-file --description '.'
complete -c runc-exec -l process-label --description '.'
complete -c runc-exec -l apparmor --description '.'
complete -c runc-exec -l no-new-privs --description '.'
complete -c runc-exec -l cap -s c --description '.'
complete -c runc-exec -l no-subreaper --description '.'
complete -c runc-exec -l preserve-fds --description '.'

