# runc-update
# Autogenerated from man page /usr/share/man/man8/runc-update.8.gz
complete -c runc-update -l resources -s r --description '.'
complete -c runc-update -l blkio-weight --description '.'
complete -c runc-update -l cpu-period --description '.'
complete -c runc-update -l cpu-quota --description '.'
complete -c runc-update -l cpu-rt-period --description '.'
complete -c runc-update -l cpu-rt-runtime --description '.'
complete -c runc-update -l cpu-share --description '.'
complete -c runc-update -l cpuset-cpus --description '.'
complete -c runc-update -l cpuset-mems --description '.'
complete -c runc-update -l memory --description '.'
complete -c runc-update -l memory-reservation --description '.'
complete -c runc-update -l memory-swap --description '.'
complete -c runc-update -l pids-limit --description '.'
complete -c runc-update -l l3-cache-schema --description '.'
complete -c runc-update -l mem-bw-schema --description '.'

