# runc-checkpoint
# Autogenerated from man page /usr/share/man/man8/runc-checkpoint.8.gz
complete -c runc-checkpoint -l image-path --description '.'
complete -c runc-checkpoint -l work-path --description '.'
complete -c runc-checkpoint -l parent-path --description '.'
complete -c runc-checkpoint -l leave-running --description '.'
complete -c runc-checkpoint -l tcp-established --description '.'
complete -c runc-checkpoint -l ext-unix-sk --description '.'
complete -c runc-checkpoint -l shell-job --description '.'
complete -c runc-checkpoint -l lazy-pages --description '.'
complete -c runc-checkpoint -l status-fd --description '.'
complete -c runc-checkpoint -l page-server --description '.'
complete -c runc-checkpoint -l file-locks --description '.'
complete -c runc-checkpoint -l pre-dump --description '.'
complete -c runc-checkpoint -l manage-cgroups-mode --description '.'
complete -c runc-checkpoint -l empty-ns --description '.'
complete -c runc-checkpoint -l auto-dedup --description '.'

