# sane-find-scanner
# Autogenerated from man page /usr/share/man/man1/sane-find-scanner.1.gz
complete -c sane-find-scanner -s '?' -s h -l help --description 'Prints a short usage message.'
complete -c sane-find-scanner -s v --description 'Verbose output.'
complete -c sane-find-scanner -s q --description 'Be quiet.  Print only the devices, no comments.'
complete -c sane-find-scanner -s p --description 'Probe parallel port scanners.'
complete -c sane-find-scanner -s f --description 'Force opening all explicitly given devices as SCSI and USB devices.'
complete -c sane-find-scanner -s F --description 'filename is a file that contains USB descriptors in the format of /proc/bus/u…'

