# sbattach
# Autogenerated from man page /usr/share/man/man1/sbattach.1.gz
complete -c sbattach -l attach --description 'set <sigfile> as the boot image\'s signature table.'
complete -c sbattach -l detach --description 'copy the boot image\'s signature table to <sigfile>.'
complete -c sbattach -l remove --description 'remove the boot image\'s signature table from the original file.'
complete -c sbattach -l signum --description 'signature to operate on (defaults to first).'

