# sbsiglist
# Autogenerated from man page /usr/share/man/man1/sbsiglist.1.gz
complete -c sbsiglist -l owner --description 'Signature owner GUID.'
complete -c sbsiglist -l type --description 'Signature type.  One of: x509 sha256.'
complete -c sbsiglist -l output --description 'write signed data to <file> (default <sig-file>. siglist).'

