# sbsign
# Autogenerated from man page /usr/share/man/man1/sbsign.1.gz
complete -c sbsign -l engine --description 'use the specified engine to load the key.'
complete -c sbsign -l key --description 'signing key (PEM-encoded RSA private key).'
complete -c sbsign -l cert --description 'certificate (x509 certificate).'
complete -c sbsign -l detached --description 'write a detached signature, instead of a signed binary.'
complete -c sbsign -l output --description 'write signed data to <file> (default <efi-boot-image>.'

