# sbvarsign
# Autogenerated from man page /usr/share/man/man1/sbvarsign.1.gz
complete -c sbvarsign -l engine --description 'use the specified engine to load the key.'
complete -c sbvarsign -l key --description 'signing key (PEM-encoded RSA private key).'
complete -c sbvarsign -l cert --description 'certificate (x509 certificate).'
complete -c sbvarsign -l include-attrs --description 'include attrs at beginning of output file.'
complete -c sbvarsign -l guid --description 'EFI GUID for the variable.'
complete -c sbvarsign -l attr --description 'variable attributes.'
complete -c sbvarsign -l output --description 'write signed data to <file> (default <var-data-file>. signed).'

