# scan-view-12
# Autogenerated from man page /usr/share/man/man1/scan-view-12.1.gz
complete -c scan-view-12 -s h -l help --description 'show this help message and exit.'
complete -c scan-view-12 -l host --description 'Host interface to listen on.  (default=127. 0. 0. 1).'
complete -c scan-view-12 -l port --description 'Port to listen on.  (default=8181).'
complete -c scan-view-12 -l debug --description 'Print additional debugging information.'
complete -c scan-view-12 -l auto-reload --description 'Automatically update module for each request.'
complete -c scan-view-12 -l no-browser --description 'Don\'t open a webbrowser on startup.'
complete -c scan-view-12 -l allow-all-hosts --description 'Allow connections from any host (access restricted to "127. 0. 0.'

