# scriptreplay
# Autogenerated from man page /usr/share/man/man1/scriptreplay.1.gz
complete -c scriptreplay -s I -l log-in --description 'File containing script\'s terminal input.'
complete -c scriptreplay -s O -l log-out --description 'File containing script\'s terminal output.'
complete -c scriptreplay -s B -l log-io --description 'File containing script\'s terminal output and input.'
complete -c scriptreplay -s t -l timing --description 'File containing script\'s timing output.'
complete -c scriptreplay -s T -l log-timing --description 'This is an alias for -t, maintained for compatibility with  script (1) comman…'
complete -c scriptreplay -s s -l typescript --description 'File containing script\'s terminal output.   Deprecated alias to --log-out.'
complete -c scriptreplay -s c -l cr-mode --description 'Specifies how to use the CR (0x0D, carriage return) character from log files.'
complete -c scriptreplay -s d -l divisor --description 'Speed up the replay displaying this  number of times.'
complete -c scriptreplay -s m -l maxdelay --description 'Set the maximum delay between updates to  number of seconds.'
complete -c scriptreplay -l summary --description 'Display details about the session recorded in the specified timing file and e…'
complete -c scriptreplay -s x -l stream --description 'Forces  scriptreplay to print only the specified stream.'
complete -c scriptreplay -s V -l version --description 'Display version information and exit.'
complete -c scriptreplay -s h -l help --description 'Display help text and exit.  EXAMPLES.'

