# sddm-greeter
# Autogenerated from man page /usr/share/man/man1/sddm-greeter.1.gz
complete -c sddm-greeter -l theme --description 'Specify theme full path.'
complete -c sddm-greeter -l socket --description 'Specify the socket used to communicate with sddm daemon.'
complete -c sddm-greeter -l test-mode --description 'Start greeter in test mode.'
complete -c sddm-greeter -l help -s h --description 'Show help message and exit.'

