# sddm
# Autogenerated from man page /usr/share/man/man1/sddm.1.gz
complete -c sddm -l test-mode --description 'Start daemon in test mode.'
complete -c sddm -l example-config --description 'Print the complete current configuration to stdout.'
complete -c sddm -l help -s h --description 'Show help message and exit.'

