# sdl2-config
# Autogenerated from man page /usr/share/man/man1/sdl2-config.1.gz
complete -c sdl2-config -l cflags --description 'Print the compiler flags that are necessary to compile a program or library t…'
complete -c sdl2-config -l exec-prefix --description 'If DIR is not specified, print the exec prefix of the current SDL installatio…'
complete -c sdl2-config -l libs --description 'Print the linker flags that are necessary to link a program that uses SDL.'
complete -c sdl2-config -l static-libs --description 'Print the linker flags that are necessary to statically link a program that u…'
complete -c sdl2-config -l prefix --description 'If DIR is not specified, print the prefix of the current SDL installation.'
complete -c sdl2-config -l version --description 'Prints the currently installed version of SDL on standard output.  EXAMPLES.'

