# seahorse
# Autogenerated from man page /usr/share/man/man1/seahorse.1.gz
complete -c seahorse -s '?' -l help --description 'Prints a short help text and exits.'
complete -c seahorse -l help-all --description 'Show all help options.'
complete -c seahorse -l help-gtk --description 'Show all GTK options.'
complete -c seahorse -s v -l version --description '.'
complete -c seahorse -l display --description '.'

