# session-migration
# Autogenerated from man page /usr/share/man/man1/session-migration.1.gz
complete -c session-migration -l dry-run --description 'This parameter enables to run the session-migration tool without really launc…'
complete -c session-migration -l filefilename --description 'This parameter, followed by a path or filename, tells sesions-migration to on…'
complete -c session-migration -l help --description 'Display a quick command help.'
complete -c session-migration -l file --description 'This parameter, followed by a path or filename, tells sesions-migration to on…'
complete -c session-migration -l verbose --description 'Show a lot of verbose information.'

