# setvtrgb
# Autogenerated from man page /usr/share/man/man8/setvtrgb.8.gz
complete -c setvtrgb -s C -l console --description 'the console device to be used;.'
complete -c setvtrgb -s h -l help --description 'Prints usage message and exits.'
complete -c setvtrgb -s V -l version --description 'Prints version number and exists.'

