# shtool-platform
# Autogenerated from man page /usr/share/man/man1/shtool-platform.1.gz
complete -c shtool-platform -s F -l format --description 'This option controls the output formatting of this program.'
complete -c shtool-platform -s S -l sep --description 'This option sets the word separation string for the platform information stri…'
complete -c shtool-platform -s C -l conc --description 'This option sets the word concatenation string for the platform information s…'
complete -c shtool-platform -s L -l lower --description 'This options enforces conversion of the output to all lower case.'
complete -c shtool-platform -s U -l upper --description 'This options enforces conversion of the output to all upper case.'
complete -c shtool-platform -s v -l verbose --description 'This option enforces verbose versions of all expansion constructs in format s…'
complete -c shtool-platform -s c -l concise --description 'This option enforces concise versions of all expansion constructs in format s…'
complete -c shtool-platform -s n -l no-newline --description 'This option omits the usual trailing newline character in the output.'
complete -c shtool-platform -s t -l type --description 'This option is a meta option which internally sets options -F, -S, -C, -L, -U…'
complete -c shtool-platform -s d -l debug --description 'This option enables some internal debugging messages.'
complete -c shtool-platform -s V -l version --description 'This option outputs the version information of shtool platform only.'

