# shtool-mkln
# Autogenerated from man page /usr/share/man/man1/shtool-mkln.1.gz
complete -c shtool-mkln -s t -l trace --description 'Enable the output of the essential shell commands which are executed.'
complete -c shtool-mkln -s f -l force --description 'Force the creation of the link even if it exists.'

