# shtool-path
# Autogenerated from man page /usr/share/man/man1/shtool-path.1.gz
complete -c shtool-path -s s -l suppress --description 'Suppress output.'
complete -c shtool-path -s r -l reverse --description 'Transform a forward path to a subdirectory into a reverse path.'
complete -c shtool-path -s d -l dirname --description 'Output the directory name of str.'
complete -c shtool-path -s b -l basename --description 'Output the base name of str.'
complete -c shtool-path -s m -l magic --description 'Enable advanced magic search for "\\f(CW\\*(C`perl\\*(C\'\\*(L" and \\*(R"\\f(CW\\*(C…'

