# shtool-install
# Autogenerated from man page /usr/share/man/man1/shtool-install.1.gz
complete -c shtool-install -s v -l verbose --description 'Display some processing information.'
complete -c shtool-install -s t -l trace --description 'Enable the output of the essential shell commands which are executed.'
complete -c shtool-install -s d -l mkdir --description 'To maximize \\s-1BSD\\s0 compatibility, the \\s-1BSD "\\s0shtool \\f(CW\\*(C`instal…'
complete -c shtool-install -s c -l copy --description 'Copy the file to the target path.  Default is to move.'
complete -c shtool-install -s C -l compare-copy --description 'Same as -c except if the destination file already exists and is identical to …'
complete -c shtool-install -s s -l strip --description 'This option strips program executables during the installation, see strip\\|(1…'
complete -c shtool-install -s m -l mode --description 'The file mode applied to the target, see chmod\\|(1).'
complete -c shtool-install -s o -l owner --description 'The file owner name or id applied to the target, see chown\\|(1).'
complete -c shtool-install -s g -l group --description 'The file group name or id applied to the target, see chgrp\\|(1).'

