# snice
# Autogenerated from man page /usr/share/man/man1/snice.1.gz
complete -c snice -s f -l fast --description 'Fast mode.   This option has not been implemented.'
complete -c snice -s i -l interactive --description 'Interactive use.   You will be asked to approve each action.'
complete -c snice -s l -l list --description 'List all signal names.'
complete -c snice -s L -l table --description 'List all signal names in a nice table.'
complete -c snice -s n -l no-action --description 'No action; perform a simulation of events that would occur but do not actuall…'
complete -c snice -s v -l verbose --description 'Verbose; explain what is being done.'
complete -c snice -s w -l warnings --description 'Enable warnings.   This option has not been implemented.'
complete -c snice -s h -l help --description 'Display help text and exit.'
complete -c snice -s V -l version --description 'Display version information.'
complete -c snice -s t -l tty --description 'The next expression is a terminal (tty or pty).'
complete -c snice -s u -l user --description 'The next expression is a username.'
complete -c snice -s p -l pid --description 'The next expression is a process ID number.'
complete -c snice -s c -l command --description 'The next expression is a command name.'
complete -c snice -l ns --description 'Match the processes that belong to the same namespace as pid.'
complete -c snice -l nslist --description 'list which namespaces will be considered for the --ns option.'

