# spice-vdagentd
# Autogenerated from man page /usr/share/man/man1/spice-vdagentd.1.gz
complete -c spice-vdagentd -s h --description 'Print a short description of all command line options.'
complete -c spice-vdagentd -s d --description 'Log debug messages (use twice for extra info).'
complete -c spice-vdagentd -s f --description 'Treat uinput device as fake; no ioctls.'
complete -c spice-vdagentd -s o --description 'The daemon will exit after processing a single session.'
complete -c spice-vdagentd -s s --description 'Set virtio serial port (default: /dev/virtio-ports/com. redhat. spice. 0).'
complete -c spice-vdagentd -s u --description 'Set uinput device (default: /dev/uinput).'
complete -c spice-vdagentd -s x --description 'Don\'t daemonize.'
complete -c spice-vdagentd -s X --description 'Disable session info usage, spice-vdagentd needs to know which spice-vdagent …'

