# spice-vdagent
# Autogenerated from man page /usr/share/man/man1/spice-vdagent.1.gz
complete -c spice-vdagent -s h --description 'Print a short description of all command line options.'
complete -c spice-vdagent -s d --description 'Log debug messages.'
complete -c spice-vdagent -s s --description 'Set virtio serial port (default: /dev/virtio-ports/com. redhat. spice. 0).'
complete -c spice-vdagent -s x --description 'Don\'t daemonize.'
complete -c spice-vdagent -s f --description 'Set directory where to save files send from the client, this can be either an…'
complete -c spice-vdagent -s o --description 'Disable/enable opening the file save directory with xdg-open (showing the dir…'

