# sqldiff
# Autogenerated from man page /usr/share/man/man1/sqldiff.1.gz
complete -c sqldiff -l changset --description 'Do not write changes to standard output.'
complete -c sqldiff -l lib -s L --description 'Load the shared library or DLL file  LIBRARY into SQLite prior to computing t…'
complete -c sqldiff -l primarykey --description 'Use the schema-defined PRIMARY KEY instead of the rowid to pair rows in the s…'
complete -c sqldiff -l schema --description 'Show only differences in the schema not the table content.'
complete -c sqldiff -l summary --description 'Show how many rows have changed on each table, but do not show the actual cha…'
complete -c sqldiff -l table --description 'Show only the differences in content for R TABLE , not for the entire databas…'
complete -c sqldiff -l transaction --description 'Wrap SQL output in a single large transaction.'
complete -c sqldiff -l vtab --description 'Add support for handling FTS3, FTS5 and rtree virtual tables.'

