# stl2gts
# Autogenerated from man page /usr/share/man/man1/stl2gts.1.gz
complete -c stl2gts -s r -l revert --description 'Revert face normals.'
complete -c stl2gts -s n -l nomerge --description 'Do not merge vertices.'
complete -c stl2gts -s v -l verbose --description 'Display surface statistics.'
complete -c stl2gts -s h -l help --description 'Display the help and exit.'

