# sudo_sendlog
# Autogenerated from man page /usr/share/man/man8/sudo_sendlog.8.gz
complete -c sudo_sendlog -s A --description 'Only send the accept event, not the I/O associated with the log.'
complete -c sudo_sendlog -s b --description 'The path to a certificate authority bundle file, in PEM format, to use instea…'
complete -c sudo_sendlog -s c --description 'The path to the client\'s certificate file in PEM format.'
complete -c sudo_sendlog -l help --description 'Display a short help message to the standard output and exit.'
complete -c sudo_sendlog -s h --description 'Connect to the specified host instead of localhost.'
complete -c sudo_sendlog -s i --description 'Use the specified iolog-id when restarting a log transfer.'
complete -c sudo_sendlog -s k --description 'The path to the client\'s private key file in PEM format.'
complete -c sudo_sendlog -s n --description 'If specified, the server\'s certificate will not be verified during the TLS ha…'
complete -c sudo_sendlog -s p --description 'Use the specified network port when connecting to the log server instead of t…'
complete -c sudo_sendlog -s r --description 'Restart an interrupted connection to the log server.'
complete -c sudo_sendlog -s R --description 'Send a reject event for the command using the specified reject-reason, even t…'
complete -c sudo_sendlog -s t --description 'Open number simultaneous connections to the log server and send the specified…'
complete -c sudo_sendlog -s V --description 'Print the sudo_sendlog version and exit.'

