# sudo_logsrvd
# Autogenerated from man page /usr/share/man/man8/sudo_logsrvd.8.gz
complete -c sudo_logsrvd -s f --description 'Read configuration from file instead of the default, /etc/sudo_logsrvd. conf.'
complete -c sudo_logsrvd -s h --description 'Display a short help message to the standard output and exit.'
complete -c sudo_logsrvd -s n --description 'Run sudo_logsrvd in the foreground instead of detaching from the terminal and…'
complete -c sudo_logsrvd -s R --description 'For each message, there is a percentage chance that the server will drop the …'
complete -c sudo_logsrvd -s V --description 'Print the sudo_logsrvd version and exit.'

