# synaptic
# Autogenerated from man page /usr/share/man/man8/synaptic.8.gz
complete -c synaptic -s f -l filter-file --description 'specify an alternative filter settings file.'
complete -c synaptic -s i -l initial-filter --description 'apply the filter with number int at startup.'
complete -c synaptic -s o -l option --description 'set an internal option (experts only).'

