# systemd-suspend-then-hibernate
# Autogenerated from man page /usr/share/man/man8/systemd-suspend-then-hibernate.service.8.gz
complete -c systemd-suspend-then-hibernate -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-suspend-then-hibernate -l version --description 'Print a short version string and exit.'

