# systemd-tmpfiles-setup
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles-setup.service.8.gz
complete -c systemd-tmpfiles-setup -l create --description 'If this option is passed, all files and directories marked with f, F, w, d, D…'
complete -c systemd-tmpfiles-setup -l clean --description 'If this option is passed, all files and directories with an age parameter con…'
complete -c systemd-tmpfiles-setup -l remove --description 'If this option is passed, the contents of directories marked with D or R, and…'
complete -c systemd-tmpfiles-setup -l user --description 'Execute "user" configuration, i. e.  tmpfiles.'
complete -c systemd-tmpfiles-setup -l boot --description 'Also execute lines with an exclamation mark.'
complete -c systemd-tmpfiles-setup -l prefix --description 'Only apply rules with paths that start with the specified prefix.'
complete -c systemd-tmpfiles-setup -l exclude-prefix --description 'Ignore rules with paths that start with the specified prefix.'
complete -c systemd-tmpfiles-setup -s E --description 'A shortcut for "--exclude-prefix=/dev --exclude-prefix=/proc --exclude-prefix…'
complete -c systemd-tmpfiles-setup -l root --description 'Takes a directory path as an argument.'
complete -c systemd-tmpfiles-setup -l image --description 'Takes a path to a disk image file or block device node.'
complete -c systemd-tmpfiles-setup -l replace --description 'When this option is given, one ore more positional arguments must be specifie…'
complete -c systemd-tmpfiles-setup -l cat-config --description 'Copy the contents of config files to standard output.'
complete -c systemd-tmpfiles-setup -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-tmpfiles-setup -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-tmpfiles-setup -l version --description 'Print a short version string and exit.'

