# systemd-socket-proxyd
# Autogenerated from man page /usr/share/man/man8/systemd-socket-proxyd.8.gz
complete -c systemd-socket-proxyd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-socket-proxyd -l version --description 'Print a short version string and exit.'
complete -c systemd-socket-proxyd -l connections-max -s c --description 'Sets the maximum number of simultaneous connections, defaults to 256.'
complete -c systemd-socket-proxyd -l exit-idle-time --description 'Sets the time before exiting when there are no connections, defaults to infin…'

