# systemd-fsckd
# Autogenerated from man page /usr/share/man/man8/systemd-fsckd.8.gz
complete -c systemd-fsckd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-fsckd -l version --description 'Print a short version string and exit.'

