# systemd-bless-boot
# Autogenerated from man page /usr/share/man/man8/systemd-bless-boot.8.gz
complete -c systemd-bless-boot -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-bless-boot -l version --description 'Print a short version string and exit.'

