# systemd-networkd-wait-online
# Autogenerated from man page /usr/share/man/man8/systemd-networkd-wait-online.8.gz
complete -c systemd-networkd-wait-online -s i -l interface --description 'Network interface to wait for before deciding if the system is online.'
complete -c systemd-networkd-wait-online -l ignore --description 'Network interfaces to be ignored when deciding if the system is online.'
complete -c systemd-networkd-wait-online -s o -l operational-state --description 'Takes a minimum operational state and an optional maximum operational state.'
complete -c systemd-networkd-wait-online -l any --description 'Even if several interfaces are in configuring state, systemd-networkd-wait-on…'
complete -c systemd-networkd-wait-online -l timeout --description 'Fail the service if the network is not online by the time the timeout elapses.'
complete -c systemd-networkd-wait-online -s q -l quiet --description 'Suppress log messages.'
complete -c systemd-networkd-wait-online -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-networkd-wait-online -l version --description 'Print a short version string and exit.'

