# systemd-binfmt
# Autogenerated from man page /usr/share/man/man8/systemd-binfmt.8.gz
complete -c systemd-binfmt -l unregister --description 'If passed, instead of registering configured binary formats in the kernel, th…'
complete -c systemd-binfmt -l cat-config --description 'Copy the contents of config files to standard output.'
complete -c systemd-binfmt -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-binfmt -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-binfmt -l version --description 'Print a short version string and exit.'

