# systemd-id128
# Autogenerated from man page /usr/share/man/man1/systemd-id128.1.gz
complete -c systemd-id128 -s p -l pretty --description 'Generate output as programming language snippets.'
complete -c systemd-id128 -s a -l app-specific --description 'With this option, an identifier that is the result of hashing the application…'
complete -c systemd-id128 -s u -l uuid --description 'Generate output as an UUID formatted in the "canonical representation", with …'
complete -c systemd-id128 -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-id128 -l version --description 'Print a short version string and exit.'

