# systemd-sysctl
# Autogenerated from man page /usr/share/man/man8/systemd-sysctl.8.gz
complete -c systemd-sysctl -l prefix --description 'Only apply rules with the specified prefix.'
complete -c systemd-sysctl -l cat-config --description 'Copy the contents of config files to standard output.'
complete -c systemd-sysctl -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-sysctl -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-sysctl -l version --description 'Print a short version string and exit.'

