# systemd-udevd-control
# Autogenerated from man page /usr/share/man/man8/systemd-udevd-control.socket.8.gz
complete -c systemd-udevd-control -s d -l daemon --description 'Detach and run in the background.'
complete -c systemd-udevd-control -s D -l debug --description 'Print debug messages to standard error.'
complete -c systemd-udevd-control -s c -l children-max --description 'Limit the number of events executed in parallel.'
complete -c systemd-udevd-control -s e -l exec-delay --description 'Delay the execution of RUN instructions by the given number of seconds.'
complete -c systemd-udevd-control -s t -l event-timeout --description 'Set the number of seconds to wait for events to finish.'
complete -c systemd-udevd-control -s s -l timeout-signal --description 'Set the signal which systemd-udevd will send to forked off processes after re…'
complete -c systemd-udevd-control -s N -l resolve-names --description 'Specify when systemd-udevd should resolve names of users and groups.'
complete -c systemd-udevd-control -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-udevd-control -l version --description 'Print a short version string and exit.'

