# telnet
# Autogenerated from man page /usr/share/man/man1/telnet.1.gz
complete -c telnet -s 4 --description 'Force IPv4 address resolution.'
complete -c telnet -s 6 --description 'Force IPv6 address resolution.'
complete -c telnet -s 8 --description 'Request 8-bit operation.'
complete -c telnet -s E --description 'Disables the escape character functionality; that is, sets the escape charact…'
complete -c telnet -s L --description 'Specifies an 8-bit data path on output.'
complete -c telnet -s a --description 'Attempt automatic login.'
complete -c telnet -s b --description 'Use bind(2) on the local socket to bind it to a specific local address.'
complete -c telnet -s d --description 'Sets the initial value of the debug toggle to TRUE.'
complete -c telnet -s r --description 'Emulate rlogin 1.  In this mode, the default escape character is a tilde.'
complete -c telnet -s S --description 'Sets the IP type-of-service (TOS) option for the telnet connection to the val…'
complete -c telnet -s e --description 'Sets the escape character to escapechar.'
complete -c telnet -s l --description 'Specify user as the user to log in as on the remote system.'
complete -c telnet -s n --description 'Opens tracefile for recording trace information.'

