# tgatoppm
# Autogenerated from man page /usr/share/man/man1/tgatoppm.1.gz
complete -c tgatoppm -l alphaout --description 'tgatoppm  creates a PGM (portable graymap) file containing the alpha channel …'
complete -c tgatoppm -l headerdump --description 'Causes the header information to be dumped to stderr.'

