# thermald
# Autogenerated from man page /usr/share/man/man8/thermald.8.gz
complete -c thermald -s h -l help --description 'Show help options.'
complete -c thermald -l version --description 'Print thermald version and exit.'
complete -c thermald -l no-daemon --description 'Don\'t become a daemon: Default is daemon mode.'
complete -c thermald -l loglevel --description 'log severity: info level and up.'
complete -c thermald -l poll-interval --description 'Poll interval in seconds: Poll for zone temperature changes.'
complete -c thermald -l dbus-enable --description 'Enable Dbus.'
complete -c thermald -l exclusive-control --description 'Act as exclusive thermal controller.'
complete -c thermald -l ignore-cpuid-check --description 'Ignore cpuid check for supported CPU models.'
complete -c thermald -l config-file --description 'Specify thermal-conf. xml path and ignore default thermal-conf. xml.'
complete -c thermald -l ignore-default-control --description 'Ignore default CPU temperature control.  Strictly follow thermal-conf.'
complete -c thermald -l workaround-enabled --description 'Enable special workarounds.'
complete -c thermald -l disable-active-power --description 'Disable active power management.  This will not set active power limits.'
complete -c thermald -l adaptive --description 'Use DPTF adaptive tables when present.'

