# thinkjettopbm
# Autogenerated from man page /usr/share/man/man1/thinkjettopbm.1.gz
complete -c thinkjettopbm -s d --description 'option turns on debugging messages which are written to the standard error st…'

