# tifftopnm
# Autogenerated from man page /usr/share/man/man1/tifftopnm.1.gz
complete -c tifftopnm -o alphaout --description 'tifftopnm  creates a PGM (portable graymap) file containing the alpha channel…'
complete -c tifftopnm -o respectfillorder --description 'By default,   tifftopnm  ignores the "fillorder" tag in the TIFF input, which…'
complete -c tifftopnm -o headerdump --description 'Dump TIFF file information to stderr.'

