# time
# Autogenerated from man page /usr/share/man/man1/time.1.gz
complete -c time -s o -l output --description 'Write the resource use statistics to  FILE instead of to the standard error s…'
complete -c time -s a -l append --description 'Append the resource use information to the output file instead of overwriting…'
complete -c time -s f -l format --description 'Use  FORMAT as the format string that controls the output of  time .'
complete -c time -l help --description 'Print a summary of the command line options and exit.'
complete -c time -s p -l portability --description 'Use the following format string, for conformance with POSIX standard 1003.'
complete -c time -s v -l verbose --description 'Use the built-in verbose format, which displays each available piece of infor…'
complete -c time -l quiet --description 'Do not report the status of the program even if it is different from zero.'
complete -c time -s V -l version --description 'Print the version number of time and exit.'

