# tracepath
# Autogenerated from man page /usr/share/man/man8/tracepath.8.gz
complete -c tracepath -s 4 --description 'Use IPv4 only.'
complete -c tracepath -s 6 --description 'Use IPv6 only.'
complete -c tracepath -s n --description 'Print primarily IP addresses numerically.'
complete -c tracepath -s b --description 'Print both: Host names and IP addresses.'
complete -c tracepath -s l --description 'Sets the initial packet length to pktlen instead of 65535 for IPv4 or 128000 …'
complete -c tracepath -s m --description 'Set maximum hops (or maximum TTLs) to max_hops instead of 30.'
complete -c tracepath -s p --description 'Sets the initial destination port to use.'
complete -c tracepath -s V --description 'Print version and exit.'

