# transfig
# Autogenerated from man page /usr/share/man/man1/transfig.1.gz
complete -c transfig -s m --description 'set the magnification at which the figure is rendered (default 1. 0).'
complete -c transfig -s f --description 'set the default font family used for text objects (default "rm").'
complete -c transfig -s s --description 'set the default font size (in points) for text objects (default 11*mag).'
complete -c transfig -s M -s T --description 'The default names are "Makefile" and "transfig. tex", respectively.'
complete -c transfig -s o --description 'pass the specified option string through to fig2dev.'

