# transmission-qt
# Autogenerated from man page /usr/share/man/man1/transmission-qt.1.gz
complete -c transmission-qt -s h --description 'Show help options.'
complete -c transmission-qt -s g --description 'Where to look for configuration files.'
complete -c transmission-qt -s m --description 'Start minimized in notification area.'
complete -c transmission-qt -s p --description 'Port to use when connecting to an existing session.'
complete -c transmission-qt -s r --description 'Connect to an existing session at the specified hostname.'
complete -c transmission-qt -s u --description 'Username to use when connecting to an existing session.'
complete -c transmission-qt -s v --description 'Show version number and exit.'
complete -c transmission-qt -s w --description 'Password to use when connecting to an existing session El Pp Multiple .'

