# transform
# Autogenerated from man page /usr/share/man/man1/transform.1.gz
complete -c transform -s r -l rx --description 'Rotate around x-axis . RI ( ANGLE in degrees).'
complete -c transform -s m -l ry --description 'Rotate around y-axis.'
complete -c transform -l rz --description 'Rotate around z-axis.'
complete -c transform -s s -l scale --description 'Scale by R FACTOR .'
complete -c transform -s R -l sx --description 'Scale x-axis by R FACTOR .'
complete -c transform -s M -l sy --description 'Scale y-axis by R FACTOR .'
complete -c transform -s N -l sz --description 'Scale z-axis by R FACTOR .'
complete -c transform -s t -l tx --description 'Translate of  V along x-axis.'
complete -c transform -s u -l ty --description 'Translate of  V along y-axis.'
complete -c transform -s w -l tz --description 'Translate of  V along z-axis.'
complete -c transform -s i -l revert --description 'Turn surface inside out.'
complete -c transform -s o -l normalize --description 'Fit the resulting surface in a cube of size 1 centered at the origin.'
complete -c transform -s v -l verbose --description 'Print statistics about the surface.'
complete -c transform -s h -l help --description 'Display the help and exit.'

