# transicc
# Autogenerated from man page /usr/share/man/man1/transicc.1.gz
complete -c transicc -s '%' --description 'use percent % of ink.'
complete -c transicc -s b --description 'Black point compensation.'
complete -c transicc -s c --description 'Precalculates transform.'
complete -c transicc -s i --description 'Input profile (defaults to sRGB).'
complete -c transicc -s l --description 'Transform by device-link profile.'
complete -c transicc -s n --description 'Terse output, intended for pipe usage.'
complete -c transicc -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute).'
complete -c transicc -s v --description 'Verbose.'
complete -c transicc -s w --description 'Use 16 bits.'
complete -c transicc -s x --description 'Hexadecimal.'
complete -c transicc -s o --description '.'

