# transset
# Autogenerated from man page /usr/share/man/man1/transset.1.gz
complete -c transset -o display --description 'This option specifies the server to use; see X(7). PP.'
complete -c transset -s h -l help --description 'This option displays a help message and exits. PP.'
complete -c transset -s t -l toggle --description 'This option forces a toggle of opacity.'
complete -c transset -s c -l click --description 'This option selects the target window by waiting for the user to click the mo…'
complete -c transset -s p -l point --description 'This option selects the window currently under the cursor to be the target.'
complete -c transset -s a -l actual --description 'This option selects the window that currently has input focus to be the targe…'
complete -c transset -s n -l name --description 'This option selects the target window by name, where name is matched as a reg…'
complete -c transset -l no-regex --description 'This option disables treating the name argument to --name as a regular expres…'
complete -c transset -s i -l id --description 'This option selects the target window by window id. PP.'
complete -c transset -l inc --description 'This option increases the window opacity by the given opacity argument. PP.'
complete -c transset -l dec --description 'This option decreases the window opacity by the given opacity argument. PP.'
complete -c transset -s m -l min --description 'This option sets the minimum possible opacity value.'
complete -c transset -s x -l max --description 'This option sets the maximum possible opacity value.'
complete -c transset -s v -l verbose --description 'This option prints some additional debug info as the program operates. PP.'
complete -c transset -s V -l version --description 'This option prints the program version number and exits.'

