# ucfr
# Autogenerated from man page /usr/share/man/man1/ucfr.1.gz
complete -c ucfr -s h -l help --description 'Print a short usage message.'
complete -c ucfr -s n -l no-action --description 'Dry run.'
complete -c ucfr -s d -l debug --description 'Set the debug level to the (optional) level  n (n defaults to 1).'
complete -c ucfr -s p -l purge --description 'Removes all vestiges of the association between the named package and the con…'
complete -c ucfr -s v -l verbose --description 'Make the script be very verbose about setting internal variables.'
complete -c ucfr -s f -l force --description 'This option forces operations requested even if the configuration file in con…'
complete -c ucfr -l state-dir --description 'Set the state directory to /path/to/dir instead of the default /var/lib/ucf.'
complete -c ucfr -s w --description 'foo | cut.'

