# udisksd
# Autogenerated from man page /usr/share/man/man8/udisksd.8.gz
complete -c udisksd -l help --description 'Show help options.'
complete -c udisksd -l replace --description 'Replace existing daemon.'
complete -c udisksd -l debug --description 'Print debug or informational messages on stdout/stderr.'
complete -c udisksd -l no-sigint --description 'Do not handle SIGINT for controlled shutdown.'
complete -c udisksd -l force-load-modules --description 'Activate modules on startup.'

