# udisksctl
# Autogenerated from man page /usr/share/man/man1/udisksctl.1.gz
complete -c udisksctl -s t -l filesystem-type --description '.'
complete -c udisksctl -s o -l options --description '.'
complete -c udisksctl -l force --description 'can be used to request that the device is unmounted even if active references…'
complete -c udisksctl -s f --description '.'
complete -c udisksctl -l key-file --description '.'
complete -c udisksctl -l file --description '.'
complete -c udisksctl -s r -l read-only --description '.'
complete -c udisksctl -l offset --description '.'
complete -c udisksctl -s s -l size --description '.'
complete -c udisksctl -s b -l block-device --description '.'
complete -c udisksctl -s p -l object-path --description '.'
complete -c udisksctl -s d -l drive --description '.'
complete -c udisksctl -l no-user-interaction --description 'can be used to request that no interaction (such as the user being presented …'

