# unar
# Autogenerated from man page /usr/share/man/man1/unar.1.gz
complete -c unar -s o -o output-directory --description 'The directory to write the contents of the archive to.'
complete -c unar -s f -o force-overwrite --description 'Always overwrite files when a file to be unpacked already exists on disk.'
complete -c unar -s r -o force-rename --description 'Always rename files when a file to be unpacked already exists on disk.'
complete -c unar -s s -o force-skip --description 'Always skip files when a file to be unpacked already exists on disk.'
complete -c unar -s d -o force-directory --description 'Always create a containing directory for the contents of the unpacked archive.'
complete -c unar -s D -o no-directory --description 'Never create a containing directory for the contents of the unpacked archive.'
complete -c unar -s p -o password --description 'The password to use for decrypting protected archives.'
complete -c unar -s e -o encoding --description 'The encoding to use for filenames in the archive, when it is not known.'
complete -c unar -s E -o password-encoding --description 'The encoding to use for the password for the archive, when it is not known.'
complete -c unar -s i -o indexes --description 'Instead of specifying the files to list as filenames or wildcard patterns, sp…'
complete -c unar -o nr -o no-recursion --description 'Do not attempt to extract archives contained in other archives.'
complete -c unar -s t -o copy-time --description 'Copy the file modification time from the archive file to the containing direc…'
complete -c unar -s k -o forks --description 'How to handle Mac OS resource forks.'
complete -c unar -s q -o quiet --description 'Run in quiet mode.'
complete -c unar -s v -o version --description 'Print version and exit.'
complete -c unar -s h -o help --description 'Display help information.  SEE ALSO lsar (1).'

