# unattended-upgrades
# Autogenerated from man page /usr/share/man/man8/unattended-upgrades.8.gz
complete -c unattended-upgrades -s h -l help --description 'help output.'
complete -c unattended-upgrades -s d -l debug --description 'extra debug output into /var/log/unattended-upgrades/unattended-upgrades. log.'
complete -c unattended-upgrades -l apt-debug --description 'detailed APT/LibAPT output for debugging.'
complete -c unattended-upgrades -s v -l verbose --description 'show verbose output.'
complete -c unattended-upgrades -l dry-run --description 'Just simulate installing updates, do not actually do it.'
complete -c unattended-upgrades -l minimal-upgrade-steps --description 'perform upgrade in minimal steps (cancel with SIGINT).'
complete -c unattended-upgrades -l no-minimal-upgrade-steps --description 'do not perform upgrade in minimal steps.'

