# unmkinitramfs
# Autogenerated from man page /usr/share/man/man8/unmkinitramfs.8.gz
complete -c unmkinitramfs -s h --description 'Display usage information and exit.'
complete -c unmkinitramfs -s v --description 'Display verbose messages about extraction.  USAGE EXAMPLES.'

