# unshield
# Autogenerated from man page /usr/share/man/man1/unshield.1.gz
complete -c unshield -s c --description 'Only list/extract this component.'
complete -c unshield -s d --description 'Extract files to DIRECTORY.'
complete -c unshield -s D --description 'Set debug log level 0 - No logging (default) 1 - Errors only 2 - Errors and w…'
complete -c unshield -s g --description 'Only list/extract this file group.'
complete -c unshield -s h --description 'Show help message.'
complete -c unshield -s j --description 'Junk paths (do not make directories).'
complete -c unshield -s L --description 'Make file and directory names lowercase.'
complete -c unshield -s n --description 'Never overwrite files.'
complete -c unshield -s o --description 'Always overwrite files.'
complete -c unshield -s O --description 'Use old compression.'
complete -c unshield -s r --description 'Save raw data (do not decompress).'
complete -c unshield -s R --description 'Don\'t do any conversion to file and directory names when extracting.'
complete -c unshield -s v --description 'Be verbose.'
complete -c unshield -s V --description 'Print version information . SS "Commands:".'

