# update-catalog
# Autogenerated from man page /usr/share/man/man8/update-catalog.8.gz
complete -c update-catalog -l add --description 'Adds an entry for the  ordinary_catalog in the R centralized_catalog .'
complete -c update-catalog -l remove --description 'Removes the entry for the  ordinary_catalog from the R centralized_catalog .'
complete -c update-catalog -l update-super --description 'Regenerates the SGML super catalog from the contents of the R /etc/sgml direc…'
complete -c update-catalog -l quiet --description 'Prevents the usual diagnostic output.'
complete -c update-catalog -l test --description 'Prevents the update of the catalog and writes the resulting SGML catalog to s…'
complete -c update-catalog -l version --description 'Displays the version information and exits.'
complete -c update-catalog -l help --description 'Display the usage information and exits.'

