# update-alternatives
# Autogenerated from man page /usr/share/man/man1/update-alternatives.1.gz
complete -c update-alternatives -l altdir --description 'Specifies the alternatives directory, when this is to be different from the d…'
complete -c update-alternatives -l admindir --description 'Specifies the administrative directory, when this is to be different from the…'
complete -c update-alternatives -l instdir --description 'Specifies the installation directory where alternatives links will be created…'
complete -c update-alternatives -l root --description 'Specifies the root directory (since version 1. 20. 1).'
complete -c update-alternatives -l log --description 'Specifies the log file (since version 1. 15.'
complete -c update-alternatives -l force --description 'Allow replacing or dropping any real file that is installed where an alternat…'
complete -c update-alternatives -l skip-auto --description 'Skip configuration prompt for alternatives which are properly configured in a…'
complete -c update-alternatives -l quiet --description 'Do not generate any comments unless errors occur.'
complete -c update-alternatives -l verbose --description 'Generate more comments about what is being done.'

