# update-initramfs
# Autogenerated from man page /usr/share/man/man8/update-initramfs.8.gz
complete -c update-initramfs -s k --description 'Set the specific kernel version for whom the initramfs will be generated.'
complete -c update-initramfs -s c --description 'This mode creates a new initramfs.'
complete -c update-initramfs -s u --description 'This mode updates an existing initramfs.'
complete -c update-initramfs -s d --description 'This mode deletes an existing initramfs.'
complete -c update-initramfs -s v --description 'This option increases the amount of information you are given during the chos…'
complete -c update-initramfs -s b --description 'Set an different bootdir for the image creation.'
complete -c update-initramfs -s h -l help --description 'Print a short help page describing the available options in update-initramfs.'

