# update-xmlcatalog
# Autogenerated from man page /usr/share/man/man8/update-xmlcatalog.8.gz
complete -c update-xmlcatalog -l add --description 'Adds the entry to the root \\s-1XML\\s0 catalog file, a package \\s-1XML\\s0 cata…'
complete -c update-xmlcatalog -l del --description 'Deletes the entry from the root \\s-1XML\\s0 catalog file, the package \\s-1XML\\…'
complete -c update-xmlcatalog -l file --description 'Indicates a local filename.'
complete -c update-xmlcatalog -l id --description 'Indicates the \\s-1XML\\s0 catalog file entry identifier.'
complete -c update-xmlcatalog -l local --description 'Indicates a local \\s-1XML\\s0 catalog file.'
complete -c update-xmlcatalog -l package --description 'Indicates a package \\s-1XML\\s0 catalog file.'
complete -c update-xmlcatalog -l root --description 'Indicates the root \\s-1XML\\s0 catalog file.'
complete -c update-xmlcatalog -l type --description 'Indicates the \\s-1XML\\s0 catalog file entry type (public, system, uri).'
complete -c update-xmlcatalog -l help --description 'Displays the usage information.'
complete -c update-xmlcatalog -l verbose --description 'Optional switch to make a verbose output.'

