# update-passwd
# Autogenerated from man page /usr/share/man/man8/update-passwd.8.gz
complete -c update-passwd -s p -l passwd-master --description 'Use FILE as the master copy of the passwd database.'
complete -c update-passwd -s g -l group-master --description 'Use FILE as the master copy of the group database.'
complete -c update-passwd -s P -l passwd --description 'Use FILE as the system passwd database.  The default value is R /etc/passwd .'
complete -c update-passwd -s S -l shadow --description 'Use FILE as the system shadow database.  The default value is R /etc/shadow .'
complete -c update-passwd -s G -l group --description 'Use FILE as the system group database.  The default value is R /etc/group .'
complete -c update-passwd -s s -l sanity-check --description 'Only perform sanity-checks but don\'t do anything.'
complete -c update-passwd -s v -l verbose --description 'Give detailed information about what we are doing.'
complete -c update-passwd -s n -l dry-run --description 'Don\'t do anything but only show what we would do.'
complete -c update-passwd -s L -l no-locking --description 'Don\'t attempt to lock the account database.'
complete -c update-passwd -s h -l help --description 'Show a summary of how to use  update-passwd .'
complete -c update-passwd -s V -l version --description 'Show the version number ENVIRONMENT.'

