# update-ieee-data
# Autogenerated from man page /usr/share/man/man8/update-ieee-data.8.gz
complete -c update-ieee-data -s q --description 'Be quiet.  Do not output messages.'
complete -c update-ieee-data -s f --description 'Force the update, even if the file is newer than 5 days.'

