# update-locale
# Autogenerated from man page /usr/share/man/man8/update-locale.8.gz
complete -c update-locale -l help --description 'Display an help message and exit.'
complete -c update-locale -l reset --description 'Variables which are not set on command-line are cleared out.'
complete -c update-locale -l locale-file --description 'Define file containing locale variables.   (Default:  /etc/default/locale ).'

