# usb-creator-kde
# Autogenerated from man page /usr/share/man/man8/usb-creator-kde.8.gz
complete -c usb-creator-kde -s i -l iso --description 'Provide a source image to pre\\(hypopulate the UI.'
complete -c usb-creator-kde -s h -l help --description 'Print a summary of command line options and exit.'
complete -c usb-creator-kde -s v -l version --description 'Print the current version and exit.'

