# validate-json
# Autogenerated from man page /usr/share/man/man1/validate-json.1.gz
complete -c validate-json -l dump-schema --description 'Output full schema and exit . HP --dump-schema-url Output URL of schema.'
complete -c validate-json -l verbose --description 'Show additional output.'
complete -c validate-json -l quiet --description 'Suppress all output.'
complete -c validate-json -l dump-schema-url --description '.'
complete -c validate-json -s h -l help --description 'Show this help.'

