# vigr
# Autogenerated from man page /usr/share/man/man8/vigr.8.gz
complete -c vigr -s g -l group --description 'Edit group database.'
complete -c vigr -s h -l help --description 'Display help message and exit.'
complete -c vigr -s p -l passwd --description 'Edit passwd database.'
complete -c vigr -s q -l quiet --description 'Quiet mode.'
complete -c vigr -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c vigr -s s -l shadow --description 'Edit shadow or gshadow database.'
complete -c vigr -l root --description '.'

