# x86_64-linux-gnu-python3-config
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-python3-config.1.gz
complete -c x86_64-linux-gnu-python3-config -l abiflags --description 'print the the ABI flags as specified by PEP 3149.'
complete -c x86_64-linux-gnu-python3-config -l cflags --description 'print the C compiler flags.'
complete -c x86_64-linux-gnu-python3-config -l ldflags --description 'print the flags that should be passed to the linker.'
complete -c x86_64-linux-gnu-python3-config -l includes --description 'similar to --cflags but only with -I options (path to python header files).'
complete -c x86_64-linux-gnu-python3-config -l libs --description 'similar to --ldflags but only with -l options (used libraries).'
complete -c x86_64-linux-gnu-python3-config -l prefix --description 'prints the prefix (base directory) under which python can be found.'
complete -c x86_64-linux-gnu-python3-config -l exec-prefix --description 'print the prefix used for executable program directories (such as bin, sbin, …'
complete -c x86_64-linux-gnu-python3-config -l extension-suffix --description 'print the extension suffix used for binary extensions.'
complete -c x86_64-linux-gnu-python3-config -l help --description 'print the usage message.'

