# x86_64-linux-gnu-lto-dump-10
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-lto-dump-10.1.gz
complete -c x86_64-linux-gnu-lto-dump-10 -o list --description 'Dumps list of details of functions and variables.'
complete -c x86_64-linux-gnu-lto-dump-10 -o demangle --description 'Dump the demangled output.'
complete -c x86_64-linux-gnu-lto-dump-10 -o defined-only --description 'Dump only the defined symbols.'
complete -c x86_64-linux-gnu-lto-dump-10 -o print-value --description 'Dump initial values of the variables.'
complete -c x86_64-linux-gnu-lto-dump-10 -o name-sort --description 'Sort the symbols alphabetically.'
complete -c x86_64-linux-gnu-lto-dump-10 -o size-sort --description 'Sort the symbols according to size.'
complete -c x86_64-linux-gnu-lto-dump-10 -o reverse-sort --description 'Dump the symbols in reverse order.'
complete -c x86_64-linux-gnu-lto-dump-10 -o no-sort --description 'Dump the symbols in order of occurrence.'
complete -c x86_64-linux-gnu-lto-dump-10 -o symbol --description 'Dump the details of specific symbol.'
complete -c x86_64-linux-gnu-lto-dump-10 -o objects --description 'Dump the details of \\s-1LTO\\s0 objects.'
complete -c x86_64-linux-gnu-lto-dump-10 -o type-stats --description 'Dump the statistics of tree types.'
complete -c x86_64-linux-gnu-lto-dump-10 -o tree-stats --description 'Dump the statistics of trees.'
complete -c x86_64-linux-gnu-lto-dump-10 -o gimple-stats --description 'Dump the statistics of gimple statements.'
complete -c x86_64-linux-gnu-lto-dump-10 -o dump-level --description 'For deciding the optimization level of body.'
complete -c x86_64-linux-gnu-lto-dump-10 -o dump-body --description 'Dump the specific gimple body.'

