# x86_64-linux-gnu-dwp
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-dwp.1.gz
complete -c x86_64-linux-gnu-dwp -s h -l help --description 'Print this help message.'
complete -c x86_64-linux-gnu-dwp -s e -l exec --description 'Get list of dwo files from EXE (defaults output to EXE. dwp).'
complete -c x86_64-linux-gnu-dwp -s o -l output --description 'Set output dwp file name.'
complete -c x86_64-linux-gnu-dwp -s v -l verbose --description 'Verbose output.'
complete -c x86_64-linux-gnu-dwp -l verify-only --description 'Verify output file against exec file.'
complete -c x86_64-linux-gnu-dwp -s V -l version --description 'Print version number REPORTING BUGS Report bugs to <http://www. sourceware.'

