# xls2csv
# Autogenerated from man page /usr/share/man/man1/xls2csv.1.gz
complete -c xls2csv -s x --description 'print unknown Unicode chars as xNNNN, rather than as question marks.'
complete -c xls2csv -s l --description 'list known charsets and exit successfully.'
complete -c xls2csv -s c --description 'cell separator char.  By default - comma.'
complete -c xls2csv -s b --description 'sheet break string.'
complete -c xls2csv -s g --description 'number of decimal digits in the numbers.'
complete -c xls2csv -s q --description 'set quote mode.  In quote mode 0 cell contents is never quoted.'
complete -c xls2csv -s d --description '- specifies destination charset name.'
complete -c xls2csv -s s --description '- specifies source charset.'
complete -c xls2csv -s f --description '- specifies date/time format to use for output of all Excel date and time  va…'

