# xtotroff
# Autogenerated from man page /usr/share/man/man1/xtotroff.1.gz
complete -c xtotroff -l help --description 'Display a usage message and exit.'
complete -c xtotroff -s r --description 'Set the resolution for all font patterns in R font-map .'
complete -c xtotroff -s s --description 'Set the point size for all font patterns in R font-map .'
complete -c xtotroff -s v --description '.'
complete -c xtotroff -l version --description 'Display version information and exit.'

