# Xwayland
# Autogenerated from man page /usr/share/man/man1/Xwayland.1.gz
complete -c Xwayland -o eglstream --description 'Use EGLStream backend for NVidia GPUs.'
complete -c Xwayland -o initfd --description 'Add the given fd as a listen socket for initialization of X clients.'
complete -c Xwayland -o listen --description 'deprecated, use -listenfd instead.'
complete -c Xwayland -o listenfd --description 'Add given fd as a listen socket.'
complete -c Xwayland -o rootless --description 'Run Xwayland rootless, so that X clients integrate seamlessly with Wayland cl…'
complete -c Xwayland -o shm --description 'Force the shared memory backend instead of glamor (if available) for passing …'
complete -c Xwayland -o verbose --description 'Sets the verbosity level for information printed on stderr.'
complete -c Xwayland -o version --description 'Show the server version and exit.'
complete -c Xwayland -o wm --description 'This option is used by the Wayland server to pass Xwayland the socket where t…'

