#!/bin/sh

xrdb ~/.Xresources &				# set the font and colors
#wall &								# wallpaper
#compton &							# compositing
pulseaudio -D							# enable if system uses pulseaudio
dwmstatus &							# Statusbar
exec dwm							# WM (Fallback)
