#!/bin/bash

# -----------------------------------------------------------------------------
#
#  this script sends a desktop notification when the current battery level
#  drops below the specified low_level.
#
# -----------------------------------------------------------------------------

low_level=20
high_level=80
sleep=600

battery_level=$(acpi - b | grep -P -o "[0-9]+(?=%)")

while true; do
	if [[ $battery_level -lt $low_level ]]; then
		eval "notify-send -i battery-low 'Low battery'"
	fi

	if [[ $battery_level -gt $high_level ]]; then
		eval "notify-send -i battery 'Battery charged'"
	fi

	sleep $sleep
done