#! /bin/bash

declare -a targets=(
    ~/.xsession-errors
    ~/.wget-hsts
    ~/.python_history
    ~/.node_repl_history
    ~/.sudo_as_admin_successful
    ~/.lesshst
    ~/.copilot/logs/*
    ~/.gradle/tmp/*
    ~/.npm/_logs/*
    ~/.npm/_cacache/tmp/*
    ~/.cache/thumbnails
    ~/.cache/kcrash-metadata
    ~/.cache/kwin/qmlcache/*
    ~/.cache/dolphin/qmlcache/*
    ~/.cache/drkonqi/qmlcache/*
    ~/.cache/plasmashell/qmlcache/*
)

SIZE=0;
for target in ${targets[@]}; do
    if [[ -e "$target" ]]; then
        target_size=$(du -sk "$target" | cut -f1);
    	SIZE=$(( SIZE + target_size));
        rm -rvf $target;
    fi
done

echo "total cleaned: ${SIZE} KB.";
