#! /bin/python3
import io


def get_colors(lines = 3, text="      ") -> str:
    b = io.StringIO()
    reset = "\033[0m"

    for line in range(0, lines):
        for color in range(40, 48):
            b.write(f"\033[1;{color}m{text}{reset} ")
        b.write("\n")

    return b.getvalue()


if __name__ == "__main__":
    output = get_colors()
    print(f"\n{output}")
