#! /bin/bash

actions="flatpak run com.google.Chrome
flatpak run org.mozilla.firefox
tilix
flatpak run com.sublimetext.three
thunar
flatpak run com.bitwarden.desktop
flatpak run rest.insomnia.Insomnia
/opt/Beekeeper\ Studio/beekeeper-studio
filezilla
remmina
pavucontrol"
result=$(echo "$actions" | dmenu -l 12 -h 30 -w 500 -x 10 -y 10)
cmd=$(echo "$result")
[ -n "$cmd" ] && eval setsid setsid "$cmd"
