#! /bin/bash

BIN_PATH=~/.java/bin;
if [[ ! -e "$BIN_PATH" ]]; then
    mkdir -p $BIN_PATH;
fi

case "$1" in
    "help" | "h")
        echo "usage: jx <run(r) | install(i)> <package-name>";
    ;;

    "install" | "i")
        if (( $# < 2 )); then
            echo "error: source and target name not provided." >&2;
        elif (( $# < 3 )); then
            echo "error: target name not provided." >&2;
        fi

        SRC=$2;
        TARGET_NAME=$3;
        TARGET_PATH="$BIN_PATH/$TARGET_NAME";
        if [[ ! -f "$SRC" ]]; then
            echo "error: provided source file does not exist." >&2;
            return 1;
        fi

        if [[ -e "$TARGET_PATH" ]]; then
            echo "info: updating package.";
        else
            echo "info: installing package.";
        fi
        cp $SRC $TARGET_PATH;
    ;;

    "list" | "l")
        ls $BIN_PATH;
    ;;

    "run" | "r")
        if (( $# < 2 )); then
            echo "error: package name not provided." >&2;
        fi

        PKG=$2;
        PKG_PATH="$BIN_PATH/$PKG";
        if [[ ! -e "$PKG_PATH" ]]; then
            echo "error: package not found." >&2;
        else
            java -jar $PKG_PATH "${@:3}";
        fi
    ;;

    *)
        echo "error: please provide a command to continue." >&2;
    ;;
esac
