#! /bin/python3

import sys
import subprocess


COLOR_RED = "\x1b[31m"
COLOR_BLUE = "\x1b[34m"
COLOR_RESET = "\x1b[0m"


def exit(msg: str) -> None:
    print(f"{COLOR_RED}error: {msg}.{COLOR_RESET}", file=sys.stderr)
    sys.exit(1)


def exec(cmd: list[str]) -> None:
    status = subprocess.run(cmd)
    if status.returncode != 0:
        exit("command failed")


def is_flatpak_installed() -> bool:
    status = subprocess.run(["which", "flatpak"], capture_output=True)
    return status.returncode == 0


def pkgs_search(pkg: str) -> None:
    exec(["apt-cache", "search", pkg])


def pkgs_update() -> None:
    print(f"{COLOR_BLUE}Updating package lists.{COLOR_RESET}")
    exec(["sudo", "apt-get", "update"])

    print(f"\n{COLOR_BLUE}Upgrading packages.{COLOR_RESET}")
    exec(["sudo", "apt-get", "upgrade", "-y"])
    if is_flatpak_installed():
        print(f"\n{COLOR_BLUE}Updating flatpaks.{COLOR_RESET}")
        exec(["flatpak", "update", "-y"])


def pkgs_install(pkgs: list[str]) -> None:
    cmd = ["sudo", "apt-get", "install", "-y"] + pkgs
    exec(cmd)


def pkgs_clean() -> None:
    exec(["sudo", "apt-get", "autoremove", "--purge", "-y"])


def pkgs_remove(pkgs: list[str]) -> None:
    exec(["sudo", "apt-get", "remove", "-y"] + pkgs)
    pkgs_clean()


def process_cmd(cmd: str, argc: int, argv: list[str]) -> None:
    match cmd:
        case "search" | "s":
            if argc < 1:
                exit("please provide a package name to search")

            if argc > 2:
                exit("can only search one package at a time")

            pkg = argv[1]
            pkgs_search(pkg)

        case "update" | "u":
            pkgs_update()

        case "install" | "i":
            if argc < 1:
                exit("please provide at-least one package name to install")

            pkgs = argv[1:]
            pkgs_install(pkgs)

        case "clean" | "c":
            pkgs_clean()

        case "remove" | "r":
            if argc < 1:
                exit("please provide at-least one package name to remove")

            pkgs = argv[1:]
            pkgs_remove(pkgs)

        case _:
            exit("invalid command")


def main(argc: int, argv: list[str]) -> None:
    if argc < 1:
        exit("please provide a command")

    cmd = argv[0]
    process_cmd(cmd, argc, argv)


if __name__ == "__main__":
    argv = sys.argv[1:]
    argc = len(argv)
    try:
        main(argc, argv)
    except KeyboardInterrupt:
        print("ctrl_c: exiting...")
    except Exception as ex:
        exit(str(ex))
