#! /bin/python3

import sys
import subprocess
from typing import Protocol


COLOR_RESET = "\033[0m"
COLOR_RED = "\033[31m"
COLOR_BLUE = "\033[34m"


def execute(cmd: list[str]) -> None:
    print(f"\n{COLOR_BLUE}running: {' '.join(cmd)}{COLOR_RESET}")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        sys.exit(1)


def command_exists(cmd: str) -> bool:
    result = subprocess.run(["which", cmd], capture_output=True, text=True)
    return result.returncode == 0


def print_help() -> None:
    help = """
usage: pkg [COMMAND] [PACKAGES]

commands:
    help             (h)   display this help message and exit.
    search           (s)   search for a single package.
    install          (i)   install new packages.
    update           (u)   update installed packages.
    remove           (r)   remove provided packages.
    clean            (c)   remove orphan packages.
    """.lstrip()
    print(help)


class PM(Protocol):
    def exists() -> bool: ...
    def search(pkg: str) -> None: ...
    def install(pkgs: list[str]) -> None: ...
    def remove(pkgs: list[str]) -> None: ...
    def update() -> None: ...
    def clean() -> None: ...


class Apt(PM):
    def exists(self) -> str:
        return command_exists("apt-get")

    def search(self, pkg: str) -> None:
        cmd = ["apt-cache", "search"]
        execute(cmd + [pkg])

    def install(self, pkgs: list[str]) -> None:
        cmd = ["sudo", "apt-get", "install", "-y"]
        execute(cmd + pkgs)

    def remove(self, pkgs: list[str]) -> None:
        cmd = ["sudo", "apt-get", "remove", "-y"]
        execute(cmd + pkgs)

    def update(self) -> None:
        UPDATE_CMD = ["sudo", "apt-get", "update", "-y"]
        execute(UPDATE_CMD)
        UPGRADE_CMD = ["sudo", "apt-get", "upgrade", "-y"]
        execute(UPGRADE_CMD)
        DIST_UPGRADE_CMD = ["sudo", "apt-get", "dist-upgrade", "-y"]
        execute(DIST_UPGRADE_CMD)

    def clean(self) -> None:
        cmd = ["sudo", "apt-get", "autoremove", "--purge", "-y"]
        execute(cmd)


class Flatpak(PM):
    def exists(self) -> str:
        return command_exists("flatpak")

    def search(self, pkg: str) -> None:
        cmd = ["flatpak", "search"]
        execute(cmd + [pkg])

    def install(self, pkgs: list[str]) -> None:
        cmd = ["sudo", "flatpak", "install", "flathub", "-y"]
        execute(cmd + pkgs)

    def remove(self, pkgs: list[str]) -> None:
        cmd = ["sudo", "flatpak", "uninstall", "--delete-data"]
        execute(cmd + pkgs)

    def update(self) -> None:
        cmd = ["sudo", "flatpak", "update", "-y"]
        execute(cmd)

    def clean(self) -> None:
        cmd = ["sudo", "flatpak", "uninstall", "--unused"]
        execute(cmd)


class PmManager:
    pms: list[PM]

    def __init__(self, pms: list[PM]) -> None:
        self.pms = pms

    def get(self) -> PM | None:
        supported_pms: list[PM] = []
        for pm in self.pms:
            if pm.exists():
                supported_pms.append(pm)
        return supported_pms

    def search(self, pms: list[PM], pkg: str) -> None:
        for pm in pms:
            pm.search(pkg)

    def install(self, pms: list[PM], pkgs: list[str]) -> None:
        for pm in pms:
            pm.install(pkgs)
            return

    def update(self, pms: list[PM]) -> None:
        for pm in pms:
            pm.update()

    def remove(self, pms: list[PM], pkgs: list[str]) -> None:
        for pm in pms:
            pm.remove(pkgs)
            return

    def clean(self, pms: list[PM]) -> None:
        for pm in pms:
            pm.clean()


def main(args: list[str]) -> None:
    if len(args) < 2:
        raise Exception("please provide a command to continue")

    pmm = PmManager(pms=[Apt(), Flatpak()])
    supported_pms = pmm.get()
    cmd_raw = args[1]

    match cmd_raw:
        case "help" | "h":
            return print_help()

        case "search" | "s":
            if len(args) > 3:
                raise Exception("can only search for one package at a time")
            pkg = args[2]
            return pmm.search(supported_pms, pkg)

        case "install" | "i":
            if len(args) < 3:
                raise Exception("please provide at least one package to install")
            pkgs = args[2:]
            return pmm.install(supported_pms, pkgs)

        case "update" | "u":
            return pmm.update(supported_pms)

        case "remove" | "r":
            if len(args) < 3:
                raise Exception("please provide at least one package to remove")
            pkgs = args[2:]
            return pmm.remove(supported_pms, pkgs)

        case "clean" | "c":
            return pmm.clean(supported_pms)

        case _:
            raise Exception(f"invalid command: '{cmd_raw}'")


if __name__ == "__main__":
    args = sys.argv[:]
    try:
        main(args)
    except KeyboardInterrupt:
        print("\nctrl+c: exiting...")
    except Exception as ex:
        print(f"{COLOR_RED}error: {str(ex)}.{COLOR_RESET}")
