#! /bin/python3

from dataclasses import dataclass
import subprocess
import os
import sys
import tempfile
import shutil
from typing import Protocol


# -------------------------------------------------------------------------------------------------------
#
#  configurations.
#
# -------------------------------------------------------------------------------------------------------
BASE_PACKAGES = [
    "kakoune",
    "make",
    "cmake",
    "network-manager",
    "net-tools",
    "bwm-ng",
    "tty-clock",
    "jq",
    "curl",
    "axel",
    "wget",
    "zip",
    "dtrx",
    "git",
    "htop",
    "redshift",
    "dfc",
    "mtr",
    "tmux",
    "xterm",
    "acpi",
    "lm-sensors",
    "p7zip",
    "fonts-jetbrains-mono",
    "fonts-roboto",
    "fonts-firacode",
    "zoxide",
    "pkg-config",
    "rsync",
    "scrot",
]

COMMON_APPS = [
    "gimp",
    "transmission-qt",
    "mpv",
    "gparted",
    "bleachbit",
    "synaptic",
]

FLATPAK_PACKAGES = [
    "com.brave.Browser",
    "com.bitwarden.desktop",
    "io.beekeeperstudio.Studio",
]

VSCODE_VERSION = "1.107.18627"

DOCKER_PACKAGES = ["docker.io", "docker-compose"]

GO_VERSION = "1.26.2"
GO_PACKAGES = [
    "golang.org/x/tools/gopls@latest",
    "github.com/go-delve/delve/cmd/dlv@latest",
    "github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest",
    "github.com/nametake/golangci-lint-langserver@latest",
]

NODE_VERSION = "25"
NODE_GLOBAL_DEPS = ["npm", "typescript-language-server"]

PYTHON_SYS_PACKAGES = ["python3-pip", "python3-venv", "pipx"]
PYTHON_PIP_PACKAGES = ["pyright", "ruff", "mypy"]

XORG_PACKAGES = [
    "foot",  
    "thunar",
    "viewnior",
	"pavucontrol",
    "mousepad",
    "gnome-themes-extra",
    "labwc",
    "swaybg",
    "swayidle",
    "waybar",
    "grim",  # screenshot.
    "swaylock",
    "brightnessctl",
    # "nwg-look", # lxappearance alternative.
]


# -------------------------------------------------------------------------------------------------------
#
#  helper variables and functions.
#
# -------------------------------------------------------------------------------------------------------
COLOR_RESET = "\033[0m"
COLOR_BLACK = "\033[30m"
COLOR_RED = "\033[31m"
COLOR_BLUE = "\033[34m"


class IConfig(Protocol):
    def name(self) -> str: ...
    def apply(self) -> None: ...


def confirm(message: str) -> bool:
    raw = input(f"{COLOR_BLUE}{message}? [y/n] {COLOR_RESET}")
    return raw.lower().strip() == "y"


def exec(cmd: list[str]) -> None:
    print(f"{COLOR_BLUE}running: {' '.join(cmd)}{COLOR_RESET}")
    subprocess.run(cmd)


def current_user() -> str:
    user = os.getenv("USER")
    if user is None:
        raise Exception("failed to read $USER from environment")
    return user.strip()


def get_home() -> str:
    home = os.getenv("HOME")
    if home is None:
        raise Exception("failed to read $HOME from environment")
    return home.strip()


# -------------------------------------------------------------------------------------------------------
#
#  configurations container classes.
#
# -------------------------------------------------------------------------------------------------------


@dataclass
class SystemPackagesConfig(IConfig):
    base_packages: list[str]
    common_apps: list[str]

    def name(self) -> str:
        return "System packages"

    def __update_pm_mirrors(self) -> None:
        exec(["sudo", "apt-get", "update", "-y"])

    def __install_packagse(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y"] + self.base_packages
        exec(cmd)

    def __install_common_apps(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y"] + self.common_apps
        exec(cmd)

    def apply(self) -> None:
        if confirm("Update mirrors"):
            self.__update_pm_mirrors()

        if confirm("Install base packages"):
            self.__install_packagse()

        if confirm("Install common apps"):
            self.__install_common_apps()


@dataclass
class FlatpakConfig(IConfig):
    packages: list[str]

    def name(self) -> str:
        return "Flatpak"

    def __install_support(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y", "flatpak"]
        exec(cmd)

    def __add_default_repo(self) -> None:
        cmd = [
            "sudo",
            "flatpak",
            "remote-add",
            "--if-not-exists",
            "flathub",
            "https://dl.flathub.org/repo/flathub.flatpakrepo",
        ]
        exec(cmd)

    def __install_flatpaks(self) -> None:
        cmd = ["sudo", "flatpak", "install", "flathub", "-y"] + self.packages
        exec(cmd)

    def apply(self) -> None:
        if confirm("Install flatpak support"):
            self.__install_support()
            self.__add_default_repo()

        if confirm("Install flatpaks"):
            self.__install_flatpaks()


@dataclass
class DockerConfig(IConfig):
    system_packages: list[str]

    def name(self) -> str:
        return "Docker"

    def __install_support(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y"] + self.system_packages
        exec(cmd)

    def __add_docker_group(self) -> None:
        cmd = ["sudo", "groupadd", "docker"]
        exec(cmd)

    def __add_to_group(self) -> None:
        user = current_user()
        cmd = ["sudo", "usermod", "-aG", "docker", user]
        exec(cmd)

    def apply(self) -> None:
        if confirm("Install docker support"):
            self.__install_support()
            self.__add_docker_group()
            self.__add_to_group()


@dataclass
class FishConfig(IConfig):
    def name(self) -> str:
        return "Fish (shell)"

    def __install_support(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y", "fish"]
        exec(cmd)

    def __whereis_fish(self) -> str:
        result = subprocess.run(["which", "fish"], capture_output=True)
        return result.stdout.decode("utf-8").strip()

    def apply(self) -> None:
        if confirm("Install fish shell"):
            self.__install_support()
            fish_location = self.__whereis_fish()
            user = current_user()
            cmd = ["sudo", "usermod", "-s", fish_location, user]
            exec(cmd)


@dataclass
class GoConfig(IConfig):
    version: str
    packages: list[str]

    def name(self) -> str:
        return "Golang"

    def __download_tarball(self) -> tuple[str, str]:
        filename = f"go{self.version}.linux-amd64.tar.gz"
        url = f"https://go.dev/dl/{filename}"
        download_path = os.path.join(tempfile.gettempdir(), filename)

        if not os.path.exists(download_path):
            cmd = ["wget", url, "-O", download_path]
            exec(cmd)

        return (download_path, filename)

    def __extract_tarball(self, filepath: str, filename: str) -> None:
        out_dir = os.path.join(get_home(), ".local")
        out_fullpath = os.path.join(out_dir, "go")

        if os.path.exists(out_fullpath):
            shutil.rmtree(out_fullpath)

        cmd = ["tar", "-xvzf", filepath, "-C", out_dir]
        exec(cmd)

    def __install_packages(self) -> None:
        gopath = os.path.join(get_home(), ".local", "go", "bin", "go")
        for pkg in self.packages:
            cmd = [gopath, "install", "-v", pkg]
            exec(cmd)

    def apply(self) -> None:
        if confirm("Install go"):
            download_path, filename = self.__download_tarball()
            self.__extract_tarball(download_path, filename)

        if confirm("Install go packages"):
            self.__install_packages()


@dataclass
class NodeJsConfig(IConfig):
    version: str
    global_deps: list[str]

    def name(self) -> str:
        return "NodeJs"

    def __download_installer(self) -> str:
        out_filename = "nodesource_setup.sh"
        out_filepath = os.path.join(tempfile.gettempdir(), out_filename)
        if not os.path.exists(out_filepath):
            cmd = [
                "curl",
                "-sL",
                f"https://deb.nodesource.com/setup_{self.version}.x",
                "-o",
                out_filepath,
            ]
            exec(cmd)
        return out_filepath

    def __install_sources(self, installer_path: str) -> None:
        cmd = ["sudo", "bash", installer_path]
        exec(cmd)

    def __install_support(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y", "nodejs"]
        exec(cmd)

    def __set_configs(self) -> None:
        home = get_home()
        exec(["npm", "config", "set", f"prefix={home}/.npm"])
        exec(["npm", "config", "set", "min-release-age=7"])
        exec(["npm", "config", "set", "ignore-scripts=true"])

    def __install_global_packages(self) -> None:
        cmd = ["npm", "i", "-g"] + self.global_deps
        exec(cmd)

    def apply(self) -> None:
        if confirm("Install nodejs"):
            installer_path = self.__download_installer()
            self.__install_sources(installer_path)
            self.__install_support()
            self.__set_configs()

        if confirm("Install global dependencies"):
            self.__install_global_packages()


@dataclass
class PythonConfig(IConfig):
    system_packages: list[str]
    pip_packages: list[str]

    def name(self) -> str:
        return "Python"

    def __install_support(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y"] + self.system_packages
        exec(cmd)

    def __install_pip_packages(self) -> None:
        cmd = ["pipx", "install", "--force"] + self.pip_packages
        exec(cmd)

    def apply(self) -> None:
        if confirm("Install python support"):
            self.__install_support()

        if confirm("Install pip packages"):
            self.__install_pip_packages()


@dataclass
class XorgConfig(IConfig):
    system_packages: list[str]

    def name(self) -> str:
        return "Xorg"

    def __install_packages(self) -> None:
        cmd = ["sudo", "apt-get", "install", "-y"] + self.system_packages
        exec(cmd)

    def __should_append(self) -> bool:
        with open("/etc/environment", "wt") as file:
            for line in file:
                if line.startsWith("FREETYPE_PROPERTIES="):
                    return False
        return True

    def __improve_font_rendering(self) -> None:
        if self.__should_append():
            target_file = "/etc/environment"
            content = """FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0" """
            cmd = f"echo '{content}' | sudo tee -a {target_file} > /dev/null"
            subprocess.run(cmd, shell=True, check=True)

    def apply(self) -> None:
        if confirm("Install xorg packages"):
            self.__install_packages()

        if confirm("Improve font rendering"):
            self.__improve_font_rendering()


@dataclass
class SymlinksConfig(IConfig):
    def name(self) -> str:
        return "Symlinks"

    def __link_files(self, src_path: str, target_path) -> None:
        dir_entries = os.listdir(src_path)
        if not os.path.exists(target_path):
            os.mkdir(target_path)

        for entry in dir_entries:
            src = os.path.join(src_path, entry)
            dst = os.path.join(target_path, entry)

            if os.path.exists(dst):
                if os.path.islink(dst):
                    os.remove(dst)
                else:
                    backup = os.path.join(target_path, f"{entry}.old")
                    if os.path.exists(backup):
                        os.remove(backup)
                    os.rename(dst, backup)

            print(f"linking: {dst}")
            os.symlink(src, dst)

    def apply(self) -> None:
        if confirm("Link config files"):
            """link $HOME files"""
            target_dir = get_home()
            home_configs = os.path.join(os.getcwd(), "configs", "home")
            self.__link_files(home_configs, target_dir)

            """ link XDG_CONFIG files """
            target_dir = os.path.join(target_dir, ".config")
            xdg_configs = os.path.join(os.getcwd(), "configs", "config")
            self.__link_files(xdg_configs, target_dir)


@dataclass
class VscodeConfig(IConfig):
    version: str

    def name(self) -> str:
        return "VSCode"

    def __download(self) -> str:
        filename = f"codium_{self.version}_amd64.deb"
        url = f"https://github.com/VSCodium/vscodium/releases/download/{self.version}/{filename}"
        download_path = os.path.join(tempfile.gettempdir(), filename)
        cmd = ["wget", url, "-O", download_path]
        exec(cmd)
        return download_path

    def __install(self, download_path: str) -> None:
        cmd = ["sudo", "dpkg", "-i", download_path]
        exec(cmd)

    def apply(self) -> None:
        if confirm("Install VSCodium"):
            download_path = self.__download()
            self.__install(download_path)


# -------------------------------------------------------------------------------------------------------
#
#  configuration driver class.
#
# -------------------------------------------------------------------------------------------------------


class Config:
    symlink: SymlinksConfig
    system_packages: SystemPackagesConfig
    flatpak: FlatpakConfig
    docker: DockerConfig
    fish: FishConfig
    vscode: VscodeConfig
    go: GoConfig
    nodejs: NodeJsConfig
    python: PythonConfig
    xorg: XorgConfig
    __steps: list[IConfig]

    def __init__(self) -> None:
        self.system_packages = SystemPackagesConfig(BASE_PACKAGES, COMMON_APPS)
        self.flatpak = FlatpakConfig(FLATPAK_PACKAGES)
        self.docker = DockerConfig(DOCKER_PACKAGES)
        self.fish = FishConfig()
        self.vscode = VscodeConfig(VSCODE_VERSION)
        self.go = GoConfig(GO_VERSION, GO_PACKAGES)
        self.nodejs = NodeJsConfig(NODE_VERSION, NODE_GLOBAL_DEPS)
        self.python = PythonConfig(PYTHON_SYS_PACKAGES, PYTHON_PIP_PACKAGES)
        self.xorg = XorgConfig(XORG_PACKAGES)
        self.symlink = SymlinksConfig()

        self.__steps = [
            self.symlink,
            self.system_packages,
            self.xorg,
            self.flatpak,
            self.docker,
            self.fish,
            self.vscode,
            self.go,
            self.nodejs,
            self.python,
        ]

    def __parse_selection(self, selection: str) -> list[int]:
        if selection == "q" or selection == "Q":
            print(f"{COLOR_BLACK}Exiting...{COLOR_RESET}")
            sys.exit(0)

        pieces = selection.split(",")
        try:
            return [int(piece.strip()) for piece in pieces]
        except Exception:
            raise Exception("invalid selection")

    def __print_menu(self) -> list[int]:
        print(f"{COLOR_BLUE}Please select an options:{COLOR_RESET}")
        idx = 1
        for step in self.__steps:
            print(f"{idx:2d}. {step.name()}")
            idx += 1

        print(" q: Quit")
        selection = input(
            f"{COLOR_BLUE}Selection (separate with commas): {COLOR_RESET}"
        ).strip()
        return self.__parse_selection(selection)

    def __apply_selected(self, selection: list[int]) -> None:
        for s in selection:
            if s < 1 or s > len(self.__steps):
                raise Exception("invalid selection")

            target_step = self.__steps[s - 1]
            if not target_step:
                raise Exception("invalid selection")
            target_step.apply()

    def __apply_all(self) -> None:
        for step in self.__steps:
            step.apply()

    def __apply_configs(self) -> None:
        selection = self.__print_menu()
        if len(selection) == 0:
            self.__apply_all()
            return
        self.__apply_selected(selection)

    def execute(self) -> None:
        while True:
            self.__apply_configs()


# -------------------------------------------------------------------------------------------------------
#
#  script entrypoint.
#
# -------------------------------------------------------------------------------------------------------

if __name__ == "__main__":
    try:
        Config().execute()
    except KeyboardInterrupt:
        print(f"{COLOR_BLACK}\nctrl+c: Exiting...{COLOR_RESET}")
    except Exception as ex:
        print(f"{COLOR_RED}Error: {str(ex)}.{COLOR_RESET}")
