#! /bin/python3

import sys
import subprocess
from enum import Enum, auto

CURSOR_SIZE = 24
FONT_NAME = "Roboto 11"
MONO_FONT_NAME = "JetBrains Mono 10"

THEME_DARK = "Adwaita-dark"
ICON_DARK = "ePapirus-Dark"
CURSOR_DARK = "DMZ-Black"

THEME_LIGHT = "Adwaita"
ICON_LIGHT = "ePapirus"
CURSOR_LIGHT = "DMZ-White"


class ThemeMode(Enum):
    Light = auto()
    Dark = auto()

    @classmethod
    def from_string(cls, raw: str):
        match raw:
            case "light":
                return ThemeMode.Light

            case "dark":
                return ThemeMode.Dark

            case _:
                raise Exception(f"invalid theme mode: {raw}")


def set_ui() -> None:
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "font-name",
            f"{FONT_NAME}",
        ]
    )

    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "monospace-font-name",
            f"{MONO_FONT_NAME}",
        ]
    )

    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "cursor-size",
            f"{CURSOR_SIZE}",
        ]
    )


def set_theme(mode: ThemeMode) -> None:

    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "gtk-theme",
            f"'{THEME_LIGHT if mode == ThemeMode.Light else THEME_DARK}'",
        ]
    )
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "icon-theme",
            f"'{ICON_LIGHT if mode == ThemeMode.Light else ICON_DARK}'",
        ]
    )
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "cursor-theme",
            f"'{CURSOR_LIGHT if mode == ThemeMode.Light else CURSOR_DARK}'",
        ]
    )
    subprocess.run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "color-scheme",
            f"{'prefer-light' if mode == ThemeMode.Light else 'prefer-dark'}",
        ]
    )


def main(args: list[str]) -> None:
    if len(args) != 1:
        raise Exception(
            "Please provide a theme mode to continue (allowed values: light, dark)."
        )

    parsed_mode = ThemeMode.from_string(args[0])
    set_theme(parsed_mode)
    set_ui()
    print("[info] theme set successfully.")


if __name__ == "__main__":
    args = sys.argv[1:]
    try:
        main(args)
    except KeyboardInterrupt:
        print("[ctrl+c]: exiting...")
    except Exception as e:
        print(f"[error] {str(e)}")
