#! /bin/lua

-- exit program with error message and status code.
function exit(message)
    io.stderr:write("error: " .. message .. "\n")
    os.exit(1)
end

-- execute shell command.
function exec(cmd)
    local s = os.execute(cmd)
    return s == true
end

-- take input from user.
function prompt(message)
    io.write(message)
    return io.read()
end

function print_help()
    local help = [[
usage: wifi [COMMAND] [PACKAGES]

commands:
  help        display this help message and exit.
  status      current network connection status.
  list        list devices and connection names.
  add         add a new wifi.
  connect     connect to an already added conncection.
  delete      delete a wifi connection.
    ]]

    print(help)
    return true
end

-- get details of currently connected wifi.
function get_status()
    return exec("nmcli dev status")
end

-- list added connections.
function list_connections()
	return exec("nmcli con show")
end

-- add a new connection.
function add_connection()
	local ssid = prompt("Wifi name: ")
	local password = prompt("Password: ")
	return exec("nmcli dev wifi connect " .. ssid .. " password" .. password)
end

-- connect to an already added connection.
function wifi_connect()
	if #arg < 2 then
    	exit("please provide a wifi connection name")
	end
	
	local ssid = arg[1]
    return exec("nmcli conn up " .. ssid)
end

-- remove an added connection.
function wifi_delete()
	if #arg < 2 then
    	exit("please provide a wifi connection name")
	end
	
	local ssid = arg[1]
	return exec("nmcli conn del " .. ssid)
end

-- execute the user-provided command.
function process_cmd(cmd)
	if cmd == "help" or cmd == "h" then
    	return print_help()
	elseif cmd == "status" or cmd == "s" then
    	return get_status()
	elseif cmd == "list" or cmd == "l" then
    	return list_connections()
	elseif cmd == "add" or cmd == "a" then
    	return add_connection()
	elseif cmd == "connect" or cmd == "c" then
    	return wifi_connect()
	elseif cmd == "delete" or cmd == "d" then
    	return wifi_delete()
	else
    	exit("invalid command")
    end
end

-- program entrypoint.
function main()
	local cmd = arg[1]
	if cmd == nil then
    	exit("please provide a command to continue.")
	end

	local success = process_cmd(cmd)
	if not success then
    	exit("failed to complete command.")
	end
end


main()
