theme = "base16_transparent"

[editor]
line-number = "absolute"
mouse = true
auto-completion = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
