theme = "solarized_light"

[editor]
line-number = "absolute"
mouse = true
auto-completion = true
rulers = [80]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "--INSERT--"
mode.select = "SELECT"
