theme = "term16_light"

[editor]
line-number = "absolute"
mouse = true
auto-completion = true
rulers = [80]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "bar"

[editor.indent-guides]
character = "▏"
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "--INSERT--"
mode.select = "SELECT"

[keys.normal]
";" = "command_mode"
