[[language]]
name = "python"
auto-format = true
language-servers = [
    {name = "pyright"},
    {name = "ruff-lsp"},
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}

[[language]]
name = "cpp"
auto-format = true
file-types = ["cpp", "hpp", "c", "h", "cc"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"]}

[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "(elixir|ex)"
shebangs = ["elixir"]
roots = ["mix.exs", "mix.lock"]
comment-token = "#"
language-servers = [ "elixir-ls" ]
indent = { tab-width = 2, unit = "  " }
auto-format = true
