[[language]]
name = "python"
auto-format = true
language-servers = [
    {name = "pyright"},
    {name = "ruff"},
    {name = "mypy"}
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "cpp"
auto-format = true
file-types = ["cpp", "hpp", "c", "h", "cc"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "clang-format", args = ["--style=Microsoft"]}

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"]}

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"]}

[[language]]
name = "ocaml"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  "--enable-outside-detected-project",
] }

