[[language]]
name = "python"
auto-format = true
language-servers = [
    {name = "pyright"},
    {name = "ruff-lsp"},
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}

[[language]]
name = "cpp"
auto-format = true
file-types = ["cpp", "hpp", "c", "h", "cc"]
formatter = { command = "clang-format", args = ["--style=Microsoft"]}

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"]}

[[language]]
name = "go"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-servers = [ "gopls", "golangci-lint-langserver" ]
