#!/bin/python

import math
import subprocess
import sys

DEFAULT_PERC: float = 0.9
MIN_VALUE: int = 40000
MAX_VALUE: int = 65535


def get_value(perc: float) -> int:
    value = MIN_VALUE + (MAX_VALUE - MIN_VALUE) * perc
    return math.floor(value)    


def set_brightness(perc: float) -> None:
    value = get_value(perc)
    subprocess.run(["xbrightness", f"{value}"])


def parse_perc(input: str) -> float:
	try:
		perc = float(input)
		if perc > 1 or perc < 0:
			return DEFAULT_PERC
		return perc
	except Exception as ex:
		return DEFAULT_PERC


def main(args: list[str]) -> None:
	perc: float = DEFAULT_PERC
	if len(args) == 2:
		perc = parse_perc(args[1])

	print(f"Brightness: {perc * 100.0}%")
	set_brightness(perc)


if __name__ == "__main__":
	args = sys.argv
	main(args)
