#!/usr/bin/python3

import os
import sys
from PIL import Image


def get_filename(file: str, ext: str) -> str:
    pieces = file.split(".")
    if len(pieces) != 2:
        return f"{file}.{ext}"

    return f"{pieces[0]}.{ext}"


def main(args: list[str]) -> None:
    if len(args) == 1:
        base_path = args[0]
    else:
        base_path = os.getcwd()

    files = os.listdir(base_path)

    for file in files:
        full_path = os.path.join(base_path, file)
        image = Image.open(full_path)
        image = image.convert("RGB")

        out_dir = os.path.join(base_path, "out")
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)

        out_path = os.path.join(out_dir, get_filename(file, "jpg"))
        print("[Done] ", out_path)
        image.save(out_path)


if __name__ == "__main__":
    args = sys.argv[1:]
    try:
        main(args)
    except Exception as err:
        print("Error", err)
    except KeyboardInterrupt:
        print("Ctrl+c: exiting program...")
