#! /bin/bash

# View the information
system_info() {
f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'

cat << EOF
$bld

$f7 OS            $f4$f1 Ubuntu$f2 x64
$f7 Page          $f4 moeenn.deviantart.com
$f7 Github        $f4 github.com/moeenn
$f7 WM            $f4 Gnome
$f7 Gtk           $f4 Arc
$f7 Icons         $f4 Papirus Icons
$f7 Font          $f4 UI: Ubuntu
$f7               $f4 Shell: Ubuntu
$rst
EOF

}

# View the colors
term_colors()
{
    echo "  ";for i in {0..7}; do echo -en " \e[0;3${i}m████\e[0m"; done;
    echo "  ";for i in {0..7}; do echo -en " \e[1;3${i}m████\e[0m"; done; echo;
    echo "  "
}
