font=JetBrains Mono:size=10
# font-bold=<bold variant of regular font>
# font-italic=<italic variant of regular font>
# font-bold-italic=<bold+italic variant of regular font>
# font-size-adjustment=0.5
line-height=20
# letter-spacing=0
# horizontal-letter-offset=0
# vertical-letter-offset=0
# underline-offset=<font metrics>
# underline-thickness=<font underline thickness>
# box-drawings-uses-font-glyphs=no
# dpi-aware=no

# initial-window-size-pixels=700x500  # Or,
initial-window-size-chars=130x24
# initial-window-mode=windowed
pad=10x10             
# resize-delay-ms=100

[scrollback]
lines=2000
# multiplier=3.0

[cursor]
style=underline
blink=no

[colors]
foreground=d8dbd9
background=1d1f21

# Regular colors
regular0=000000 # black
regular1=cc6666 # red
regular2=b5bd68 # green
regular3=de935f # yellow
regular4=81a2be # blue
regular5=b294bb # magenta
regular6=8abeb7 # cyan
regular7=c5c8c6 # white
# Bright colors
bright0=666666 # bright black
bright1=cc6666 # bright red
bright2=b5bd68 # bright green
bright3=de935f # bright yellow
bright4=81a2be # bright blue
bright5=b294bb # bright magenta
bright6=8abeb7 # bright cyan
bright7=26292b # bright white

# commit=Return
# find-prev=Control+r
# find-next=Control+s
# cursor-left=Left Control+b
# cursor-left-word=Control+Left Mod1+b
# cursor-right=Right Control+f
# cursor-right-word=Control+Right Mod1+f
# cursor-home=Home Control+a
# cursor-end=End Control+e
# delete-prev=BackSpace
# delete-prev-word=Mod1+BackSpace Control+BackSpace
# delete-next=Delete
# delete-next-word=Mod1+d Control+Delete
# extend-char=Shift+Right
# extend-to-word-boundary=Control+w Control+Shift+Right
# extend-to-next-whitespace=Control+Shift+w
# extend-line-down=Shift+Down
# extend-backward-char=Shift+Left
# extend-backward-to-word-boundary=Control+Shift+Left
# extend-backward-to-next-whitespace=none
# extend-line-up=Shift+Up
# clipboard-paste=Control+v Control+Shift+v Control+y XF86Paste
# primary-paste=Shift+Insert
# unicode-input=none
# scrollback-up-page=Shift+Page_Up
# scrollback-up-half-page=none
# scrollback-up-line=none
# scrollback-down-page=Shift+Page_Down
# scrollback-down-half-page=none
# scrollback-down-line=none
# scrollback-home=none
# scrollback-end=none
