#! /bin/sh

# Colors are specifiee in following formats:
# 1. #RRGGBB
# 2. #AARRGGBB

fg='#abafbb'
bg='#800E0E0E'
uline='#B9924A'
font='-*-drift-*-*-*-*-10-*-*-*-*-*-*-*'
geom='1366x24'

lemonbar -f $font -F $fg -g $geom -B $bg -U $uline -u 2
