[colors.primary]
background = '0x1d2021'
foreground = '0xd4be98'

# Normal colors
[colors.normal]
black   = '0x32302f'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

# Bright colors
[colors.bright]
black   = '0x32302f'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[cursor.style]
shape = "Underline"

[font]
size = 8.0

[font.bold]
family = "Fira Code"
style = "Retina"

[font.glyph_offset]
x = 0
y = 5

[font.normal]
family = "Fira Code"
style = "Retina"

[font.offset]
x = 0
y = 10

[window.padding]
x = 10
y = 10
