[window]
opacity = 1.0
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal.family = "JetBrains Mono"
size = 9.0
offset.x = 0
offset.y = 5
glyph_offset.y = 3

[cursor]
style = { shape = "Underline" }

[colors.primary]
background = '#faf4ed'
foreground = '#575279'

[colors.cursor]
text = '#575279'
cursor = '#cecacd'

[colors.vi_mode_cursor]
text = '#575279'
cursor = '#cecacd'

[colors.selection]
text = '#575279'
background = '#dfdad9'

[colors.normal]
black = '#f2e9e1'
red = '#b4637a'
green = '#286983'
yellow = '#ea9d34'
blue = '#56949f'
magenta = '#907aa9'
cyan = '#d7827e'
white = '#575279'

[colors.bright]
black = '#9893a5'
red = '#b4637a'
green = '#286983'
yellow = '#ea9d34'
blue = '#56949f'
magenta = '#907aa9'
cyan = '#d7827e'
white = '#575279'

[colors.hints]
start = { foreground = '#797593', background = '#fffaf3' }
end = { foreground = '#9893a5', background = '#fffaf3' }
