[env]
TERM = "alacritty"

[window]
opacity = 1.0
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal.family = "JetBrains Mono"
size = 9.0
offset.x = 0
offset.y = 5
glyph_offset.y = 3

[cursor]
style = { shape = "Underline" }

[colors.primary]
background = '#fdf6e3'
foreground = '#5c6a72'

# Normal colors
[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

# Bright Colors
[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'
