[window]
opacity = 1.0
padding.x = 4
padding.y = 4
decorations = "Full"
decorations_theme_variant = "Light" # "Light"

[font]
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
size = 8
offset.x = 0
offset.y = 8
glyph_offset.y = 4

[cursor]
style = { shape = "block" }

[colors.primary]
background = "#f9f9f9"
foreground = "#2a2c33"

[colors.cursor]
cursor = "#bbbbbb"

[colors.normal]
black = "#000000"
red = "#de3e35"
green = "#3f953a"
yellow = "#d2b67c"
blue = "#2f5af3"
magenta = "#950095"
cyan = "#3f953a"
white = "#bbbbbb"

[colors.bright]
black = "#000000"
red = "#de3e35"
green = "#3f953a"
yellow = "#d2b67c"
blue = "#2f5af3"
magenta = "#950095"
cyan = "#3f953a"
white = "#ededed"
